In [11]:
from sklearn import tree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn import model_selection
from sklearn.model_selection import GridSearchCV
from sklearn import metrics
import pandas as pd
import numpy as np

dataset_ecoli = pd.read_csv('ecoli.data', sep=',')
print("\nDataset ecoli:")
dataset_ecoli


Dataset ecoli:


mcg   gvh   lip  chg   aac  alm1  alm2  resultado
0    0.49  0.29  0.48  0.5  0.56  0.24  0.35          1
1    0.07  0.40  0.48  0.5  0.54  0.35  0.44          1
2    0.56  0.40  0.48  0.5  0.49  0.37  0.46          1
3    0.59  0.49  0.48  0.5  0.52  0.45  0.36          1
4    0.23  0.32  0.48  0.5  0.55  0.25  0.35          1
5    0.67  0.39  0.48  0.5  0.36  0.38  0.46          1
6    0.29  0.28  0.48  0.5  0.44  0.23  0.34          1
7    0.21  0.34  0.48  0.5  0.51  0.28  0.39          1
8    0.20  0.44  0.48  0.5  0.46  0.51  0.57          1
9    0.42  0.40  0.48  0.5  0.56  0.18  0.30          1
10   0.42  0.24  0.48  0.5  0.57  0.27  0.37          1
11   0.25  0.48  0.48  0.5  0.44  0.17  0.29          1
12   0.39  0.32  0.48  0.5  0.46  0.24  0.35          1
13   0.51  0.50  0.48  0.5  0.46  0.32  0.35          1
14   0.22  0.43  0.48  0.5  0.48  0.16  0.28          1
15   0.25  0.40  0.48  0.5  0.46  0.44  0.52          1
16   0.34  0.45  0.48  0.5  0.38  0.24  0.35          1
17   0.44  0.27  0.48  0.5  0.55  0.52  0.58          1
18   0.23  0.40  0.48  0.5  0.39  0.28  0.38          1
19   0.41  0.57  0.48  0.5  0.39  0.21  0.32          1
20   0.40  0.45  0.48  0.5  0.38  0.22  0.00          1
21   0.31  0.23  0.48  0.5  0.73  0.05  0.14          1
22   0.51  0.54  0.48  0.5  0.41  0.34  0.43          1
23   0.30  0.16  0.48  0.5  0.56  0.11  0.23          1
24   0.36  0.39  0.48  0.5  0.48  0.22  0.23          1
25   0.29  0.37  0.48  0.5  0.48  0.44  0.52          1
26   0.25  0.40  0.48  0.5  0.47  0.33  0.42          1
27   0.21  0.51  0.48  0.5  0.50  0.32  0.41          1
28   0.43  0.37  0.48  0.5  0.53  0.35  0.44          1
29   0.43  0.39  0.48  0.5  0.47  0.31  0.41          1
..    ...   ...   ...  ...   ...   ...   ...        ...
306  0.63  0.71  0.48  0.5  0.60  0.40  0.39          8
307  0.71  0.86  0.48  0.5  0.40  0.54  0.32          8
308  0.68  0.78  0.48  0.5  0.43  0.44  0.42          8
309  0.64  0.84  0.48  0.5  0.37  0.45  0.40          8
310  0.74  0.47  0.48  0.5  0.50  0.57  0.42          8
311  0.75  0.84  0.48  0.5  0.35  0.52  0.33          8
312  0.63  0.65  0.48  0.5  0.39  0.44  0.35          8
313  0.69  0.67  0.48  0.5  0.30  0.39  0.24          8
314  0.70  0.71  0.48  0.5  0.42  0.84  0.85          8
315  0.69  0.80  0.48  0.5  0.46  0.57  0.26          8
316  0.64  0.66  0.48  0.5  0.41  0.39  0.20          8
317  0.63  0.80  0.48  0.5  0.46  0.31  0.29          8
318  0.66  0.71  0.48  0.5  0.41  0.50  0.35          8
319  0.69  0.59  0.48  0.5  0.46  0.44  0.52          8
320  0.68  0.67  0.48  0.5  0.49  0.40  0.34          8
321  0.64  0.78  0.48  0.5  0.50  0.36  0.38          8
322  0.62  0.78  0.48  0.5  0.47  0.49  0.54          8
323  0.76  0.73  0.48  0.5  0.44  0.39  0.39          8
324  0.64  0.81  0.48  0.5  0.37  0.39  0.44          8
325  0.29  0.39  0.48  0.5  0.52  0.40  0.48          8
326  0.62  0.83  0.48  0.5  0.46  0.36  0.40          8
327  0.56  0.54  0.48  0.5  0.43  0.37  0.30          8
328  0.69  0.66  0.48  0.5  0.41  0.50  0.25          8
329  0.69  0.65  0.48  0.5  0.63  0.48  0.41          8
330  0.43  0.59  0.48  0.5  0.52  0.49  0.56          8
331  0.74  0.56  0.48  0.5  0.47  0.68  0.30          8
332  0.71  0.57  0.48  0.5  0.48  0.35  0.32          8
333  0.61  0.60  0.48  0.5  0.44  0.39  0.38          8
334  0.59  0.61  0.48  0.5  0.42  0.42  0.37          8
335  0.74  0.74  0.48  0.5  0.31  0.53  0.52          8

[336 rows x 8 columns]

In [12]:
dataset_ecoli.columns

Index(['mcg', 'gvh', 'lip', 'chg', 'aac', 'alm1', 'alm2', 'resultado'], dtype='object')

In [13]:
ecoli_values = dataset_ecoli.iloc[:,0:7].values
print("\nEcoli features:\n")
print(ecoli_values)


Ecoli features:

[[0.49 0.29 0.48 ... 0.56 0.24 0.35]
 [0.07 0.4  0.48 ... 0.54 0.35 0.44]
 [0.56 0.4  0.48 ... 0.49 0.37 0.46]
 ...
 [0.61 0.6  0.48 ... 0.44 0.39 0.38]
 [0.59 0.61 0.48 ... 0.42 0.42 0.37]
 [0.74 0.74 0.48 ... 0.31 0.53 0.52]]


In [14]:
ecoli_classes = dataset_ecoli.iloc[:,7].values
print("\nEcoli classes:\n")
print(ecoli_classes)
print("\nEcoli classes shape:")
print(ecoli_classes.shape)


Ecoli classes:

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3
 4 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 7 7 7 7 7 8 8 8 8 8 8 8 8 8 8 8 8
 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8
 8 8 8]

Ecoli classes shape:
(336,)


In [15]:
kf = model_selection.StratifiedKFold(n_splits = 2)
arvore_decisao = tree.DecisionTreeClassifier(criterion='entropy', splitter='best', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, random_state=None, max_leaf_nodes=None, min_impurity_decrease=0.0, min_impurity_split=None, class_weight=None, presort='deprecated', ccp_alpha=0.0)
vizinhos_proximos = KNeighborsClassifier(n_neighbors=3, weights = 'distance')
naive_bayes_gaussian = GaussianNB()
regressao_logistica = LogisticRegression(penalty='l2', dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='saga', max_iter=100, multi_class='auto', verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)
rede_neural = MLPClassifier(hidden_layer_sizes=(5,), activation="logistic", max_iter= 300, alpha=0.001, solver="sgd", tol=1e-4, verbose=True, learning_rate_init=.01)

In [16]:
predicted_classes = dict()
predicted_classes['arvore_decisao'] = np.zeros(ecoli_classes.shape)
predicted_classes['vizinhos_proximos'] = np.zeros(ecoli_classes.shape)
predicted_classes['naive_bayes_gaussian'] = np.zeros(ecoli_classes.shape)
predicted_classes['regressao_logistica'] = np.zeros(ecoli_classes.shape)
predicted_classes['rede_neural'] = np.zeros(ecoli_classes.shape)

In [17]:

for train, test in kf.split(ecoli_values, ecoli_classes):
    data_train, target_train = ecoli_values[train], ecoli_classes[train]
    data_test, target_test = ecoli_values[test], ecoli_classes[test]

    arvore_decisao = arvore_decisao.fit(data_train, target_train)
    arvore_decisao_predicted = arvore_decisao.predict(data_test)
    predicted_classes['arvore_decisao'][test] = arvore_decisao_predicted

    vizinhos_proximos = vizinhos_proximos.fit(data_train, target_train)
    vizinhos_proximos_predicted = vizinhos_proximos.predict(data_test)
    predicted_classes['vizinhos_proximos'][test] = vizinhos_proximos_predicted

    naive_bayes_gaussian = naive_bayes_gaussian.fit(data_train, target_train)
    naive_bayes_gaussian_predicted = naive_bayes_gaussian.predict(data_test)
    predicted_classes['naive_bayes_gaussian'][test] = naive_bayes_gaussian_predicted

    regressao_logistica = regressao_logistica.fit(data_train, target_train)
    regressao_logistica_predicted = regressao_logistica.predict(data_test)
    predicted_classes['regressao_logistica'][test] = regressao_logistica_predicted

    rede_neural = rede_neural.fit(data_train, target_train)
    rede_neural_predicted = rede_neural.predict(data_test)
    predicted_classes['rede_neural'][test] = rede_neural_predicted

Iteration 1, loss = 1.92771055
Iteration 2, loss = 1.92184157
Iteration 3, loss = 1.91361579
Iteration 4, loss = 1.90341394
Iteration 5, loss = 1.89160245
Iteration 6, loss = 1.87852738
Iteration 7, loss = 1.86451007
Iteration 8, loss = 1.84984423
Iteration 9, loss = 1.83479426
Iteration 10, loss = 1.81959450
Iteration 11, loss = 1.80444912
Iteration 12, loss = 1.78953281
Iteration 13, loss = 1.77499170
Iteration 14, loss = 1.76094487
Iteration 15, loss = 1.74748598
Iteration 16, loss = 1.73468522
Iteration 17, loss = 1.72259138
Iteration 18, loss = 1.71123404
Iteration 19, loss = 1.70062584
Iteration 20, loss = 1.69076476
Iteration 21, loss = 1.68163639
Iteration 22, loss = 1.67321616
Iteration 23, loss = 1.66547143
Iteration 24, loss = 1.65836350
Iteration 25, loss = 1.65184943
Iteration 26, loss = 1.64588369
Iteration 27, loss = 1.64041961
Iteration 28, loss = 1.63541064
Iteration 29, loss = 1.63081137
Iteration 30, loss = 1.62657838
Iteration 31, loss = 1.62267085
Iteration 32, los

/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [18]:
for classificador in predicted_classes.keys():
    print("================================================================================================")
    print("Resultados do classificador %s\n%s\n"
          %(classificador, metrics.classification_report(ecoli_classes, predicted_classes[classificador])))
    print("Matriz de confusão: \n%s\n\n\n" % metrics.confusion_matrix(ecoli_classes, predicted_classes[classificador]))



Resultados do classificador rede_neural
              precision    recall  f1-score   support

           1       0.43      1.00      0.60       143
           2       0.00      0.00      0.00        77
           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00         2
           5       0.00      0.00      0.00        35
           6       0.00      0.00      0.00        20
           7       0.00      0.00      0.00         5
           8       0.00      0.00      0.00        52

    accuracy                           0.43       336
   macro avg       0.05      0.12      0.07       336
weighted avg       0.18      0.43      0.25       336


Matriz de confusão: 
[[143   0   0   0   0   0   0   0]
 [ 77   0   0   0   0   0   0   0]
 [  2   0   0   0   0   0   0   0]
 [  2   0   0   0   0   0   0   0]
 [ 35   0   0   0   0   0   0   0]
 [ 20   0   0   0   0   0   0   0]
 [  5   0   0   0   0   0   0   0]
 [ 52   0   0   0   0   0   0   0]]



Res

/home/larissa/.local/lib/python3.5/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
