In [1]:
from sklearn import tree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn import model_selection
from sklearn.model_selection import GridSearchCV
from sklearn import metrics
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier

dataset_ecoli = pd.read_csv('ecoli.data', sep=',')
print("\nDataset ecoli:")
dataset_ecoli


Dataset ecoli:


mcg   gvh   lip  chg   aac  alm1  alm2  resultado
0    0.49  0.29  0.48  0.5  0.56  0.24  0.35          1
1    0.07  0.40  0.48  0.5  0.54  0.35  0.44          1
2    0.56  0.40  0.48  0.5  0.49  0.37  0.46          1
3    0.59  0.49  0.48  0.5  0.52  0.45  0.36          1
4    0.23  0.32  0.48  0.5  0.55  0.25  0.35          1
5    0.67  0.39  0.48  0.5  0.36  0.38  0.46          1
6    0.29  0.28  0.48  0.5  0.44  0.23  0.34          1
7    0.21  0.34  0.48  0.5  0.51  0.28  0.39          1
8    0.20  0.44  0.48  0.5  0.46  0.51  0.57          1
9    0.42  0.40  0.48  0.5  0.56  0.18  0.30          1
10   0.42  0.24  0.48  0.5  0.57  0.27  0.37          1
11   0.25  0.48  0.48  0.5  0.44  0.17  0.29          1
12   0.39  0.32  0.48  0.5  0.46  0.24  0.35          1
13   0.51  0.50  0.48  0.5  0.46  0.32  0.35          1
14   0.22  0.43  0.48  0.5  0.48  0.16  0.28          1
15   0.25  0.40  0.48  0.5  0.46  0.44  0.52          1
16   0.34  0.45  0.48  0.5  0.38  0.24  0.35          1
17   0.44  0.27  0.48  0.5  0.55  0.52  0.58          1
18   0.23  0.40  0.48  0.5  0.39  0.28  0.38          1
19   0.41  0.57  0.48  0.5  0.39  0.21  0.32          1
20   0.40  0.45  0.48  0.5  0.38  0.22  0.00          1
21   0.31  0.23  0.48  0.5  0.73  0.05  0.14          1
22   0.51  0.54  0.48  0.5  0.41  0.34  0.43          1
23   0.30  0.16  0.48  0.5  0.56  0.11  0.23          1
24   0.36  0.39  0.48  0.5  0.48  0.22  0.23          1
25   0.29  0.37  0.48  0.5  0.48  0.44  0.52          1
26   0.25  0.40  0.48  0.5  0.47  0.33  0.42          1
27   0.21  0.51  0.48  0.5  0.50  0.32  0.41          1
28   0.43  0.37  0.48  0.5  0.53  0.35  0.44          1
29   0.43  0.39  0.48  0.5  0.47  0.31  0.41          1
..    ...   ...   ...  ...   ...   ...   ...        ...
306  0.63  0.71  0.48  0.5  0.60  0.40  0.39          8
307  0.71  0.86  0.48  0.5  0.40  0.54  0.32          8
308  0.68  0.78  0.48  0.5  0.43  0.44  0.42          8
309  0.64  0.84  0.48  0.5  0.37  0.45  0.40          8
310  0.74  0.47  0.48  0.5  0.50  0.57  0.42          8
311  0.75  0.84  0.48  0.5  0.35  0.52  0.33          8
312  0.63  0.65  0.48  0.5  0.39  0.44  0.35          8
313  0.69  0.67  0.48  0.5  0.30  0.39  0.24          8
314  0.70  0.71  0.48  0.5  0.42  0.84  0.85          8
315  0.69  0.80  0.48  0.5  0.46  0.57  0.26          8
316  0.64  0.66  0.48  0.5  0.41  0.39  0.20          8
317  0.63  0.80  0.48  0.5  0.46  0.31  0.29          8
318  0.66  0.71  0.48  0.5  0.41  0.50  0.35          8
319  0.69  0.59  0.48  0.5  0.46  0.44  0.52          8
320  0.68  0.67  0.48  0.5  0.49  0.40  0.34          8
321  0.64  0.78  0.48  0.5  0.50  0.36  0.38          8
322  0.62  0.78  0.48  0.5  0.47  0.49  0.54          8
323  0.76  0.73  0.48  0.5  0.44  0.39  0.39          8
324  0.64  0.81  0.48  0.5  0.37  0.39  0.44          8
325  0.29  0.39  0.48  0.5  0.52  0.40  0.48          8
326  0.62  0.83  0.48  0.5  0.46  0.36  0.40          8
327  0.56  0.54  0.48  0.5  0.43  0.37  0.30          8
328  0.69  0.66  0.48  0.5  0.41  0.50  0.25          8
329  0.69  0.65  0.48  0.5  0.63  0.48  0.41          8
330  0.43  0.59  0.48  0.5  0.52  0.49  0.56          8
331  0.74  0.56  0.48  0.5  0.47  0.68  0.30          8
332  0.71  0.57  0.48  0.5  0.48  0.35  0.32          8
333  0.61  0.60  0.48  0.5  0.44  0.39  0.38          8
334  0.59  0.61  0.48  0.5  0.42  0.42  0.37          8
335  0.74  0.74  0.48  0.5  0.31  0.53  0.52          8

[336 rows x 8 columns]

In [2]:
dataset_ecoli.columns

Index(['mcg', 'gvh', 'lip', 'chg', 'aac', 'alm1', 'alm2', 'resultado'], dtype='object')

In [3]:
ecoli_values = dataset_ecoli.iloc[:,0:7].values
print("\nEcoli features:\n")
print(ecoli_values)


Ecoli features:

[[0.49 0.29 0.48 ... 0.56 0.24 0.35]
 [0.07 0.4  0.48 ... 0.54 0.35 0.44]
 [0.56 0.4  0.48 ... 0.49 0.37 0.46]
 ...
 [0.61 0.6  0.48 ... 0.44 0.39 0.38]
 [0.59 0.61 0.48 ... 0.42 0.42 0.37]
 [0.74 0.74 0.48 ... 0.31 0.53 0.52]]


In [4]:
ecoli_classes = dataset_ecoli.iloc[:,7].values
print("\nEcoli classes:\n")
print(ecoli_classes)
print("\nEcoli classes shape:")
print(ecoli_classes.shape)


Ecoli classes:

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3
 4 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 7 7 7 7 7 8 8 8 8 8 8 8 8 8 8 8 8
 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8
 8 8 8]

Ecoli classes shape:
(336,)


In [5]:
kfold_treinamento = model_selection.StratifiedKFold(n_splits=5, shuffle=True, random_state=None)
kfold_ajuste_parametros = model_selection.StratifiedKFold(n_splits=3, shuffle=True, random_state=None)

In [6]:
arvore_decisao = DecisionTreeClassifier()
print("====== Iniciando busca pelos melhores parâmetros do algoritmo Arvore de decisao no dataset Ecoli ....\n")
param_dist = {'max_depth':list(np.arange(1,10)), 'min_samples_split':list(np.arange(1,10)) ,'criterion':['entropy'], 'splitter':['best','random']}
grid_search = GridSearchCV(arvore_decisao, param_grid=param_dist, cv=kfold_ajuste_parametros, scoring='accuracy', refit=False)
grid_search.fit(ecoli_values, ecoli_classes)
decisionTreeBestParams = grid_search.best_params_
print("Decision Tree: %s \n\n" % decisionTreeBestParams)

====== Iniciando busca pelos melhores parâmetros do algoritmo Arvore de decisao no dataset Ecoli ....

Decision Tree: {'splitter': 'best', 'criterion': 'entropy', 'max_depth': 5} 




/home/larissa/.local/lib/python3.5/site-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=3.
  % (min_groups, self.n_splits)), UserWarning)


In [7]:
knn_vizinhos_proximos = KNeighborsClassifier()
print("====== Iniciando busca pelos melhores parâmetros do algoritmo KNN no dataset Ecoli ....\n")
param_dist = {'n_neighbors':[3,5,7,9], 'metric':['euclidean', 'manhattan'], 'weights':['uniform', 'distance']} #Parâmetros testados
grid_search = GridSearchCV(knn_vizinhos_proximos, param_grid=param_dist, cv=kfold_ajuste_parametros, scoring='accuracy', refit=False)
grid_search.fit(ecoli_values, ecoli_classes)
knnBestParams = grid_search.best_params_
print("KNN: %s \n\n" % knnBestParams)

====== Iniciando busca pelos melhores parâmetros do algoritmo KNN no dataset Ecoli ....

KNN: {'n_neighbors': 8, 'metric': 'euclidean', 'weights': 'distance'} 




/home/larissa/.local/lib/python3.5/site-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=3.
  % (min_groups, self.n_splits)), UserWarning)


In [8]:
regressao_logistica = LogisticRegression()
print("====== Iniciando busca pelos melhores parâmetros do algoritmo Regressao logistica no dataset Ecoli ....\n")
param_dist = {'penalty':['l2','l1'], 'max_iter':[200,300,400,500],'solver':['liblinear','sag','saga']} #Parâmetros testados
grid_search = GridSearchCV(regressao_logistica, param_grid=param_dist, cv=kfold_ajuste_parametros, scoring='accuracy', refit=False)
grid_search.fit(ecoli_values, ecoli_classes)
regressao_logistica_param = grid_search.best_params_
print("Regressão logistica: %s \n\n" % regressao_logistica_param)

====== Iniciando busca pelos melhores parâmetros do algoritmo Regressao logistica no dataset Ecoli ....

Regressão logistica: {'penalty': 'none', 'solver': 'saga', 'tol': 0.0001, 'max_iter': 300} 




/home/larissa/.local/lib/python3.5/site-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=3.
  % (min_groups, self.n_splits)), UserWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_ite

In [ ]:
rede_neural = MLPClassifier()
print("====== Iniciando busca pelos melhores parâmetros do algoritmo Redes neurais no dataset Teaching ....\n")
param_dist = {'hidden_layer_sizes':list(np.arange(10,20)),'activation':['logistic','identity','tanh'], 'max_iter':[100,200,300,400],'alpha':[0.0001,0.001, 0.01, 0.1], 'solver':['sgd','adam']}
grid_search = GridSearchCV(rede_neural, param_grid=param_dist, cv=kfold_ajuste_parametros, scoring='accuracy', refit=False)
grid_search.fit(ecoli_values, ecoli_classes)
redes_neurais_param = grid_search.best_params_
print("Redes neurais: %s \n\n" % redes_neurais_param)

====== Iniciando busca pelos melhores parâmetros do algoritmo Redes neurais no dataset Teaching ....



/home/larissa/.local/lib/python3.5/site-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=3.
  % (min_groups, self.n_splits)), UserWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  % self.max_iter, Convergenc

In [ ]:
predicted_classes = dict()
predicted_classes['arvore_decisao'] = np.zeros(ecoli_classes.shape)
predicted_classes['vizinhos_proximos'] = np.zeros(ecoli_classes.shape)
predicted_classes['naive_bayes_gaussian'] = np.zeros(ecoli_classes.shape)
predicted_classes['regressao_logistica'] = np.zeros(ecoli_classes.shape)
predicted_classes['rede_neural'] = np.zeros(ecoli_classes.shape)

arvore_decisao_best_param = DecisionTreeClassifier(**decisionTreeBestParams)
knn_vizinhos_proximos_best_param = KNeighborsClassifier(**knnBestParams)
naive_bayes_gaussian = GaussianNB()
regressao_logistica_best_param = LogisticRegression(**regressao_logistica_param)
rede_neural_best_param = MLPClassifier(**redes_neurais_param)

In [ ]:
for train, test in kfold_treinamento.split(ecoli_values, ecoli_classes):
    data_train, target_train = ecoli_values[train], ecoli_classes[train]
    data_test, target_test = ecoli_values[test], ecoli_classes[test]

    arvore_decisao = arvore_decisao.fit(data_train, target_train)
    arvore_decisao_predicted = arvore_decisao.predict(data_test)
    predicted_classes['arvore_decisao'][test] = arvore_decisao_predicted

    vizinhos_proximos = vizinhos_proximos.fit(data_train, target_train)
    vizinhos_proximos_predicted = vizinhos_proximos.predict(data_test)
    predicted_classes['vizinhos_proximos'][test] = vizinhos_proximos_predicted

    naive_bayes_gaussian = naive_bayes_gaussian.fit(data_train, target_train)
    naive_bayes_gaussian_predicted = naive_bayes_gaussian.predict(data_test)
    predicted_classes['naive_bayes_gaussian'][test] = naive_bayes_gaussian_predicted

    regressao_logistica = regressao_logistica.fit(data_train, target_train)
    regressao_logistica_predicted = regressao_logistica.predict(data_test)
    predicted_classes['regressao_logistica'][test] = regressao_logistica_predicted

    rede_neural = rede_neural.fit(data_train, target_train)
    rede_neural_predicted = rede_neural.predict(data_test)
    predicted_classes['rede_neural'][test] = rede_neural_predicted

In [ ]:
for classificador in predicted_classes.keys():
    print("================================================================================================")
    print("Resultados do classificador %s\n%s\n"
          %(classificador, metrics.classification_report(ecoli_classes, predicted_classes[classificador])))
    print("Matriz de confusão: \n%s\n\n\n" % metrics.confusion_matrix(ecoli_classes, predicted_classes[classificador]))

