In [117]:
from sklearn import tree, preprocessing
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn import model_selection
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn import metrics
import pandas as pd
import numpy as np


dataset_ecoli = pd.read_csv('ecoli.data', sep=',')
print("\nDataset ecoli:")
dataset_ecoli


Dataset ecoli:


mcg   gvh   lip  chg   aac  alm1  alm2 resultado
0    0.49  0.29  0.48  0.5  0.56  0.24  0.35        cp
1    0.07  0.40  0.48  0.5  0.54  0.35  0.44        cp
2    0.56  0.40  0.48  0.5  0.49  0.37  0.46        cp
3    0.59  0.49  0.48  0.5  0.52  0.45  0.36        cp
4    0.23  0.32  0.48  0.5  0.55  0.25  0.35        cp
5    0.67  0.39  0.48  0.5  0.36  0.38  0.46        cp
6    0.29  0.28  0.48  0.5  0.44  0.23  0.34        cp
7    0.21  0.34  0.48  0.5  0.51  0.28  0.39        cp
8    0.20  0.44  0.48  0.5  0.46  0.51  0.57        cp
9    0.42  0.40  0.48  0.5  0.56  0.18  0.30        cp
10   0.42  0.24  0.48  0.5  0.57  0.27  0.37        cp
11   0.25  0.48  0.48  0.5  0.44  0.17  0.29        cp
12   0.39  0.32  0.48  0.5  0.46  0.24  0.35        cp
13   0.51  0.50  0.48  0.5  0.46  0.32  0.35        cp
14   0.22  0.43  0.48  0.5  0.48  0.16  0.28        cp
15   0.25  0.40  0.48  0.5  0.46  0.44  0.52        cp
16   0.34  0.45  0.48  0.5  0.38  0.24  0.35        cp
17   0.44  0.27  0.48  0.5  0.55  0.52  0.58        cp
18   0.23  0.40  0.48  0.5  0.39  0.28  0.38        cp
19   0.41  0.57  0.48  0.5  0.39  0.21  0.32        cp
20   0.40  0.45  0.48  0.5  0.38  0.22  0.00        cp
21   0.31  0.23  0.48  0.5  0.73  0.05  0.14        cp
22   0.51  0.54  0.48  0.5  0.41  0.34  0.43        cp
23   0.30  0.16  0.48  0.5  0.56  0.11  0.23        cp
24   0.36  0.39  0.48  0.5  0.48  0.22  0.23        cp
25   0.29  0.37  0.48  0.5  0.48  0.44  0.52        cp
26   0.25  0.40  0.48  0.5  0.47  0.33  0.42        cp
27   0.21  0.51  0.48  0.5  0.50  0.32  0.41        cp
28   0.43  0.37  0.48  0.5  0.53  0.35  0.44        cp
29   0.43  0.39  0.48  0.5  0.47  0.31  0.41        cp
..    ...   ...   ...  ...   ...   ...   ...       ...
306  0.63  0.71  0.48  0.5  0.60  0.40  0.39        pp
307  0.71  0.86  0.48  0.5  0.40  0.54  0.32        pp
308  0.68  0.78  0.48  0.5  0.43  0.44  0.42        pp
309  0.64  0.84  0.48  0.5  0.37  0.45  0.40        pp
310  0.74  0.47  0.48  0.5  0.50  0.57  0.42        pp
311  0.75  0.84  0.48  0.5  0.35  0.52  0.33        pp
312  0.63  0.65  0.48  0.5  0.39  0.44  0.35        pp
313  0.69  0.67  0.48  0.5  0.30  0.39  0.24        pp
314  0.70  0.71  0.48  0.5  0.42  0.84  0.85        pp
315  0.69  0.80  0.48  0.5  0.46  0.57  0.26        pp
316  0.64  0.66  0.48  0.5  0.41  0.39  0.20        pp
317  0.63  0.80  0.48  0.5  0.46  0.31  0.29        pp
318  0.66  0.71  0.48  0.5  0.41  0.50  0.35        pp
319  0.69  0.59  0.48  0.5  0.46  0.44  0.52        pp
320  0.68  0.67  0.48  0.5  0.49  0.40  0.34        pp
321  0.64  0.78  0.48  0.5  0.50  0.36  0.38        pp
322  0.62  0.78  0.48  0.5  0.47  0.49  0.54        pp
323  0.76  0.73  0.48  0.5  0.44  0.39  0.39        pp
324  0.64  0.81  0.48  0.5  0.37  0.39  0.44        pp
325  0.29  0.39  0.48  0.5  0.52  0.40  0.48        pp
326  0.62  0.83  0.48  0.5  0.46  0.36  0.40        pp
327  0.56  0.54  0.48  0.5  0.43  0.37  0.30        pp
328  0.69  0.66  0.48  0.5  0.41  0.50  0.25        pp
329  0.69  0.65  0.48  0.5  0.63  0.48  0.41        pp
330  0.43  0.59  0.48  0.5  0.52  0.49  0.56        pp
331  0.74  0.56  0.48  0.5  0.47  0.68  0.30        pp
332  0.71  0.57  0.48  0.5  0.48  0.35  0.32        pp
333  0.61  0.60  0.48  0.5  0.44  0.39  0.38        pp
334  0.59  0.61  0.48  0.5  0.42  0.42  0.37        pp
335  0.74  0.74  0.48  0.5  0.31  0.53  0.52        pp

[336 rows x 8 columns]

In [118]:
dataset_ecoli.columns

Index(['mcg', 'gvh', 'lip', 'chg', 'aac', 'alm1', 'alm2', 'resultado'], dtype='object')

In [119]:
enc = OneHotEncoder(handle_unknown='ignore')
enc_df = pd.DataFrame(enc.fit_transform(dataset_ecoli[['resultado']]).toarray())
dataset_ecoli= dataset_ecoli.join(enc_df)
dataset_ecoli = dataset_ecoli.drop(columns = ['resultado'])
dataset_ecoli

mcg   gvh   lip  chg   aac  alm1  alm2    0    1    2    3    4    5  \
0    0.49  0.29  0.48  0.5  0.56  0.24  0.35  1.0  0.0  0.0  0.0  0.0  0.0   
1    0.07  0.40  0.48  0.5  0.54  0.35  0.44  1.0  0.0  0.0  0.0  0.0  0.0   
2    0.56  0.40  0.48  0.5  0.49  0.37  0.46  1.0  0.0  0.0  0.0  0.0  0.0   
3    0.59  0.49  0.48  0.5  0.52  0.45  0.36  1.0  0.0  0.0  0.0  0.0  0.0   
4    0.23  0.32  0.48  0.5  0.55  0.25  0.35  1.0  0.0  0.0  0.0  0.0  0.0   
5    0.67  0.39  0.48  0.5  0.36  0.38  0.46  1.0  0.0  0.0  0.0  0.0  0.0   
6    0.29  0.28  0.48  0.5  0.44  0.23  0.34  1.0  0.0  0.0  0.0  0.0  0.0   
7    0.21  0.34  0.48  0.5  0.51  0.28  0.39  1.0  0.0  0.0  0.0  0.0  0.0   
8    0.20  0.44  0.48  0.5  0.46  0.51  0.57  1.0  0.0  0.0  0.0  0.0  0.0   
9    0.42  0.40  0.48  0.5  0.56  0.18  0.30  1.0  0.0  0.0  0.0  0.0  0.0   
10   0.42  0.24  0.48  0.5  0.57  0.27  0.37  1.0  0.0  0.0  0.0  0.0  0.0   
11   0.25  0.48  0.48  0.5  0.44  0.17  0.29  1.0  0.0  0.0  0.0  0.0  0.0   
12   0.39  0.32  0.48  0.5  0.46  0.24  0.35  1.0  0.0  0.0  0.0  0.0  0.0   
13   0.51  0.50  0.48  0.5  0.46  0.32  0.35  1.0  0.0  0.0  0.0  0.0  0.0   
14   0.22  0.43  0.48  0.5  0.48  0.16  0.28  1.0  0.0  0.0  0.0  0.0  0.0   
15   0.25  0.40  0.48  0.5  0.46  0.44  0.52  1.0  0.0  0.0  0.0  0.0  0.0   
16   0.34  0.45  0.48  0.5  0.38  0.24  0.35  1.0  0.0  0.0  0.0  0.0  0.0   
17   0.44  0.27  0.48  0.5  0.55  0.52  0.58  1.0  0.0  0.0  0.0  0.0  0.0   
18   0.23  0.40  0.48  0.5  0.39  0.28  0.38  1.0  0.0  0.0  0.0  0.0  0.0   
19   0.41  0.57  0.48  0.5  0.39  0.21  0.32  1.0  0.0  0.0  0.0  0.0  0.0   
20   0.40  0.45  0.48  0.5  0.38  0.22  0.00  1.0  0.0  0.0  0.0  0.0  0.0   
21   0.31  0.23  0.48  0.5  0.73  0.05  0.14  1.0  0.0  0.0  0.0  0.0  0.0   
22   0.51  0.54  0.48  0.5  0.41  0.34  0.43  1.0  0.0  0.0  0.0  0.0  0.0   
23   0.30  0.16  0.48  0.5  0.56  0.11  0.23  1.0  0.0  0.0  0.0  0.0  0.0   
24   0.36  0.39  0.48  0.5  0.48  0.22  0.23  1.0  0.0  0.0  0.0  0.0  0.0   
25   0.29  0.37  0.48  0.5  0.48  0.44  0.52  1.0  0.0  0.0  0.0  0.0  0.0   
26   0.25  0.40  0.48  0.5  0.47  0.33  0.42  1.0  0.0  0.0  0.0  0.0  0.0   
27   0.21  0.51  0.48  0.5  0.50  0.32  0.41  1.0  0.0  0.0  0.0  0.0  0.0   
28   0.43  0.37  0.48  0.5  0.53  0.35  0.44  1.0  0.0  0.0  0.0  0.0  0.0   
29   0.43  0.39  0.48  0.5  0.47  0.31  0.41  1.0  0.0  0.0  0.0  0.0  0.0   
..    ...   ...   ...  ...   ...   ...   ...  ...  ...  ...  ...  ...  ...   
306  0.63  0.71  0.48  0.5  0.60  0.40  0.39  0.0  0.0  0.0  0.0  0.0  0.0   
307  0.71  0.86  0.48  0.5  0.40  0.54  0.32  0.0  0.0  0.0  0.0  0.0  0.0   
308  0.68  0.78  0.48  0.5  0.43  0.44  0.42  0.0  0.0  0.0  0.0  0.0  0.0   
309  0.64  0.84  0.48  0.5  0.37  0.45  0.40  0.0  0.0  0.0  0.0  0.0  0.0   
310  0.74  0.47  0.48  0.5  0.50  0.57  0.42  0.0  0.0  0.0  0.0  0.0  0.0   
311  0.75  0.84  0.48  0.5  0.35  0.52  0.33  0.0  0.0  0.0  0.0  0.0  0.0   
312  0.63  0.65  0.48  0.5  0.39  0.44  0.35  0.0  0.0  0.0  0.0  0.0  0.0   
313  0.69  0.67  0.48  0.5  0.30  0.39  0.24  0.0  0.0  0.0  0.0  0.0  0.0   
314  0.70  0.71  0.48  0.5  0.42  0.84  0.85  0.0  0.0  0.0  0.0  0.0  0.0   
315  0.69  0.80  0.48  0.5  0.46  0.57  0.26  0.0  0.0  0.0  0.0  0.0  0.0   
316  0.64  0.66  0.48  0.5  0.41  0.39  0.20  0.0  0.0  0.0  0.0  0.0  0.0   
317  0.63  0.80  0.48  0.5  0.46  0.31  0.29  0.0  0.0  0.0  0.0  0.0  0.0   
318  0.66  0.71  0.48  0.5  0.41  0.50  0.35  0.0  0.0  0.0  0.0  0.0  0.0   
319  0.69  0.59  0.48  0.5  0.46  0.44  0.52  0.0  0.0  0.0  0.0  0.0  0.0   
320  0.68  0.67  0.48  0.5  0.49  0.40  0.34  0.0  0.0  0.0  0.0  0.0  0.0   
321  0.64  0.78  0.48  0.5  0.50  0.36  0.38  0.0  0.0  0.0  0.0  0.0  0.0   
322  0.62  0.78  0.48  0.5  0.47  0.49  0.54  0.0  0.0  0.0  0.0  0.0  0.0   
323  0.76  0.73  0.48  0.5  0.44  0.39  0.39  0.0  0.0  0.0  0.0  0.0  0.0   
324  0.64  0.81  0.48  0.5  0.37  0.39  0.44  0.0  0.0  0.0  0.0  0.0  0.0   
325  0.29  0.39  0.48  0.5  

In [120]:
ecoli_values = dataset_ecoli.iloc[:,0:7].values
print("\nEcoli features:\n")
print(ecoli_values)


Ecoli features:

[[0.49 0.29 0.48 ... 0.56 0.24 0.35]
 [0.07 0.4  0.48 ... 0.54 0.35 0.44]
 [0.56 0.4  0.48 ... 0.49 0.37 0.46]
 ...
 [0.61 0.6  0.48 ... 0.44 0.39 0.38]
 [0.59 0.61 0.48 ... 0.42 0.42 0.37]
 [0.74 0.74 0.48 ... 0.31 0.53 0.52]]


In [121]:
ecoli_classes = dataset_ecoli.iloc[:,7].values
print("\nEcoli classes:\n")
print(ecoli_classes)
print("\nEcoli classes shape:")
print(ecoli_classes.shape)


Ecoli classes:

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

In [122]:
kf = model_selection.StratifiedKFold(n_splits = 2)
arvore_decisao = tree.DecisionTreeClassifier(criterion='entropy', splitter='best', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, random_state=None, max_leaf_nodes=None, min_impurity_decrease=0.0, min_impurity_split=None, class_weight=None, presort='deprecated', ccp_alpha=0.0)
vizinhos_proximos = KNeighborsClassifier(n_neighbors=3, weights = 'distance')
naive_bayes_gaussian = GaussianNB()
regressao_logistica = LogisticRegression(penalty='l2', dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='saga', max_iter=100, multi_class='auto', verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)
rede_neural = MLPClassifier(hidden_layer_sizes=(5,), activation="logistic", max_iter= 300, alpha=0.001, solver="sgd", tol=1e-4, verbose=True, learning_rate_init=.01)

In [123]:
predicted_classes = dict()
predicted_classes['arvore_decisao'] = np.zeros(ecoli_classes.shape)
predicted_classes['vizinhos_proximos'] = np.zeros(ecoli_classes.shape)
predicted_classes['naive_bayes_gaussian'] = np.zeros(ecoli_classes.shape)
predicted_classes['regressao_logistica'] = np.zeros(ecoli_classes.shape)
predicted_classes['rede_neural'] = np.zeros(ecoli_classes.shape)

In [124]:

for train, test in kf.split(ecoli_values, ecoli_classes):
    data_train, target_train = ecoli_values[train], ecoli_classes[train]
    data_test, target_test = ecoli_values[test], ecoli_classes[test]

    arvore_decisao = arvore_decisao.fit(data_train, target_train)
    arvore_decisao_predicted = arvore_decisao.predict(data_test)
    predicted_classes['arvore_decisao'][test] = arvore_decisao_predicted

    vizinhos_proximos = vizinhos_proximos.fit(data_train, target_train)
    vizinhos_proximos_predicted = vizinhos_proximos.predict(data_test)
    predicted_classes['vizinhos_proximos'][test] = vizinhos_proximos_predicted

    naive_bayes_gaussian = naive_bayes_gaussian.fit(data_train, target_train)
    naive_bayes_gaussian_predicted = naive_bayes_gaussian.predict(data_test)
    predicted_classes['naive_bayes_gaussian'][test] = naive_bayes_gaussian_predicted

    regressao_logistica = regressao_logistica.fit(data_train, target_train)
    regressao_logistica_predicted = regressao_logistica.predict(data_test)
    predicted_classes['regressao_logistica'][test] = regressao_logistica_predicted

    rede_neural = rede_neural.fit(data_train, target_train)
    rede_neural_predicted = rede_neural.predict(data_test)
    predicted_classes['rede_neural'][test] = rede_neural_predicted

Iteration 1, loss = 0.84504780
Iteration 2, loss = 0.84106986
Iteration 3, loss = 0.83551365
Iteration 4, loss = 0.82865434
Iteration 5, loss = 0.82075861
Iteration 6, loss = 0.81207922
Iteration 7, loss = 0.80285095
Iteration 8, loss = 0.79328779
Iteration 9, loss = 0.78358103
Iteration 10, loss = 0.77389830
Iteration 11, loss = 0.76438328
Iteration 12, loss = 0.75515605
Iteration 13, loss = 0.74631394
Iteration 14, loss = 0.73793280
Iteration 15, loss = 0.73006859
Iteration 16, loss = 0.72275922
Iteration 17, loss = 0.71602658
Iteration 18, loss = 0.70987854
Iteration 19, loss = 0.70431110
Iteration 20, loss = 0.69931039
Iteration 21, loss = 0.69485462
Iteration 22, loss = 0.69091590
Iteration 23, loss = 0.68746183
Iteration 24, loss = 0.68445702
Iteration 25, loss = 0.68186431
Iteration 26, loss = 0.67964590
Iteration 27, loss = 0.67776420
Iteration 28, loss = 0.67618258
Iteration 29, loss = 0.67486593
Iteration 30, loss = 0.67378110
Iteration 31, loss = 0.67289714
Iteration 32, los

In [125]:
for classificador in predicted_classes.keys():
    print("================================================================================================")
    print("Resultados do classificador %s\n%s\n"
          %(classificador, metrics.classification_report(ecoli_classes, predicted_classes[classificador])))
    print("Matriz de confusão: \n%s\n\n\n" % metrics.confusion_matrix(ecoli_classes, predicted_classes[classificador]))


Resultados do classificador arvore_decisao
              precision    recall  f1-score   support

         0.0       0.95      0.58      0.72       193
         1.0       0.63      0.96      0.76       143

    accuracy                           0.74       336
   macro avg       0.79      0.77      0.74       336
weighted avg       0.81      0.74      0.73       336


Matriz de confusão: 
[[111  82]
 [  6 137]]



Resultados do classificador rede_neural
              precision    recall  f1-score   support

         0.0       0.57      1.00      0.73       193
         1.0       0.00      0.00      0.00       143

    accuracy                           0.57       336
   macro avg       0.29      0.50      0.36       336
weighted avg       0.33      0.57      0.42       336


Matriz de confusão: 
[[193   0]
 [143   0]]



Resultados do classificador vizinhos_proximos
              precision    recall  f1-score   support

         0.0       0.98      0.64      0.78       193
         1.0

/home/larissa/.local/lib/python3.5/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
