In [16]:
from sklearn import tree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn import model_selection
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
import pandas as pd
import numpy as np


dataset_haberman = pd.read_table('haberman.data', sep=',')
print("\nDataset Haberman:")
dataset_haberman


Dataset Haberman:


Age of patient at time of operation  Patients year of operation  \
0                                     30                          64   
1                                     30                          62   
2                                     30                          65   
3                                     31                          59   
4                                     31                          65   
..                                   ...                         ...   
301                                   75                          62   
302                                   76                          67   
303                                   77                          65   
304                                   78                          65   
305                                   83                          58   

     Number of positive axillary nodes detected  Survival status  
0                                             1                1  
1                                             3                1  
2                                             0                1  
3                                             2                1  
4                                             4                1  
..                                          ...              ...  
301                                           1                1  
302                                           0                1  
303                                           3                1  
304                                           1                2  
305                                           2                2  

[306 rows x 4 columns]

In [17]:
dataset_haberman.columns

Index(['Age of patient at time of operation', 'Patients year of operation',
       'Number of positive axillary nodes detected', 'Survival status'],
      dtype='object')

In [30]:
haberman_normalised = dataset_haberman.values.copy()
normalizador =  StandardScaler()

haberman_normalised = normalizador.fit_transform(dataset_haberman)
dataset_haberman['Age of patient at time of operation'] = haberman_normalised[:,0]
dataset_haberman['Patients year of operation'] = haberman_normalised[:,1]
dataset_haberman['Number of positive axillary nodes detected'] = haberman_normalised[:,2]

print("\nDataset Haberman Normalized:")
dataset_haberman


Dataset Haberman Normalized:


Age of patient at time of operation  Patients year of operation  \
0                              -2.082140                    0.353584   
1                              -2.082140                   -0.262921   
2                              -2.082140                    0.661837   
3                              -1.989426                   -1.187680   
4                              -1.989426                    0.661837   
..                                   ...                         ...   
301                             2.090018                   -0.262921   
302                             2.182732                    1.278342   
303                             2.275447                    0.661837   
304                             2.368162                    0.661837   
305                             2.831735                   -1.495933   

     Number of positive axillary nodes detected  Survival status  
0                                     -0.421592                1  
1                                     -0.142959                1  
2                                     -0.560909                1  
3                                     -0.282275                1  
4                                     -0.003642                1  
..                                          ...              ...  
301                                   -0.421592                1  
302                                   -0.560909                1  
303                                   -0.142959                1  
304                                   -0.421592                2  
305                                   -0.282275                2  

[306 rows x 4 columns]

In [31]:
haberman_values = dataset_haberman.iloc[:,0:3].values
print("\nHaberman features:\n")
print(haberman_values)


Haberman features:

[[-2.08214014e+00  3.53584065e-01 -4.21592031e-01]
 [-2.08214014e+00 -2.62921484e-01 -1.42958853e-01]
 [-2.08214014e+00  6.61836839e-01 -5.60908620e-01]
 [-1.98942552e+00 -1.18767981e+00 -2.82275442e-01]
 [-1.98942552e+00  6.61836839e-01 -3.64226377e-03]
 [-1.80399628e+00 -1.49593258e+00  8.32257270e-01]
 [-1.80399628e+00 -8.79427033e-01 -5.60908620e-01]
 [-1.71128165e+00 -1.18767981e+00 -5.60908620e-01]
 [-1.71128165e+00  9.70089614e-01  6.92940681e-01]
 [-1.71128165e+00 -1.49593258e+00  3.61858905e+00]
 [-1.71128165e+00 -8.79427033e-01 -4.21592031e-01]
 [-1.71128165e+00 -5.71174259e-01  8.32257270e-01]
 [-1.71128165e+00  1.27834239e+00  4.14307503e-01]
 [-1.71128165e+00 -8.79427033e-01 -5.60908620e-01]
 [-1.61856703e+00  3.53584065e-01  1.25020704e+00]
 [-1.61856703e+00  4.53312904e-02 -5.60908620e-01]
 [-1.52585241e+00 -8.79427033e-01 -4.21592031e-01]
 [-1.52585241e+00  1.89484794e+00 -5.60908620e-01]
 [-1.43313779e+00 -8.79427033e-01 -5.60908620e-01]
 [-1.43313

In [32]:
haberman_classes = dataset_haberman.iloc[:,3].values
print("\nHaberman classes:\n")
print(haberman_classes)
print("\nHaberman classes shape:")
print(haberman_classes.shape)


Haberman classes:

[1 1 1 1 1 1 1 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 2 1 1
 1 1 1 1 1 1 2 2 2 1 1 1 1 1 1 1 2 2 1 1 1 1 1 1 1 2 2 2 2 1 1 1 1 1 1 1 2
 2 2 1 1 1 1 2 2 2 1 1 1 1 1 1 2 2 2 2 1 1 1 2 2 2 1 1 1 1 1 1 1 1 2 2 2 1
 1 1 1 2 2 1 1 1 1 1 1 1 1 2 2 1 1 1 1 1 1 1 1 1 1 2 2 1 1 1 1 2 2 2 2 1 1
 1 1 1 1 1 1 1 1 2 2 2 2 2 2 1 1 1 1 1 2 2 2 2 1 1 1 1 1 1 1 1 1 2 2 1 1 1
 1 1 1 1 1 2 2 1 1 1 1 1 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1
 1 2 2 1 1 1 1 2 2 2 1 1 1 1 1 1 2 2 2 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 2
 2 2 2 1 1 1 1 1 1 2 2 1 1 1 2 2 1 1 1 1 1 1 2 1 1 1 2 2 1 1 1 1 1 1 2 1 1
 1 1 1 2 1 1 1 1 2 2]

Haberman classes shape:
(306,)


In [1]:
kf = model_selection.StratifiedKFold(n_splits = 5)
arvore_decisao = tree.DecisionTreeClassifier(criterion='entropy', splitter='best', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, random_state=None, max_leaf_nodes=None, min_impurity_decrease=0.0, min_impurity_split=None, class_weight=None, presort='deprecated', ccp_alpha=0.0)
vizinhos_proximos = KNeighborsClassifier(n_neighbors=3, weights = 'distance')
naive_bayes_gaussian = GaussianNB()
regressao_logistica = LogisticRegression(penalty='l2', dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='saga', max_iter=100, multi_class='auto', verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)
rede_neural = MLPClassifier(hidden_layer_sizes=(5,), activation="logistic", max_iter= 300, alpha=0.001, solver="sgd", tol=1e-4, verbose=True, learning_rate_init=.01)

NameError: name 'model_selection' is not defined

In [2]:
predicted_classes = dict()
predicted_classes['arvore_decisao'] = np.zeros(haberman_classes.shape)
predicted_classes['vizinhos_proximos'] = np.zeros(haberman_classes.shape)
predicted_classes['naive_bayes_gaussian'] = np.zeros(haberman_classes.shape)
predicted_classes['regressao_logistica'] = np.zeros(haberman_classes.shape)
predicted_classes['rede_neural'] = np.zeros(haberman_classes.shape)

NameError: name 'np' is not defined

In [35]:
for train, test in kf.split(haberman_values, haberman_classes):
    data_train, target_train = haberman_values[train], haberman_classes[train]
    data_test, target_test = haberman_values[test], haberman_classes[test]

    arvore_decisao = arvore_decisao.fit(data_train, target_train)
    arvore_decisao_predicted = arvore_decisao.predict(data_test)
    predicted_classes['arvore_decisao'][test] = arvore_decisao_predicted

    vizinhos_proximos = vizinhos_proximos.fit(data_train, target_train)
    vizinhos_proximos_predicted = vizinhos_proximos.predict(data_test)
    predicted_classes['vizinhos_proximos'][test] = vizinhos_proximos_predicted

    naive_bayes_gaussian = naive_bayes_gaussian.fit(data_train, target_train)
    naive_bayes_gaussian_predicted = naive_bayes_gaussian.predict(data_test)
    predicted_classes['naive_bayes_gaussian'][test] = naive_bayes_gaussian_predicted

    regressao_logistica = regressao_logistica.fit(data_train, target_train)
    regressao_logistica_predicted = regressao_logistica.predict(data_test)
    predicted_classes['regressao_logistica'][test] = regressao_logistica_predicted

    rede_neural = rede_neural.fit(data_train, target_train)
    rede_neural_predicted = rede_neural.predict(data_test)
    predicted_classes['rede_neural'][test] = rede_neural_predicted

Iteration 1, loss = 0.61122274
Iteration 2, loss = 0.60926748
Iteration 3, loss = 0.60634432
Iteration 4, loss = 0.60283139
Iteration 5, loss = 0.59903407
Iteration 6, loss = 0.59530129
Iteration 7, loss = 0.59168329
Iteration 8, loss = 0.58804081
Iteration 9, loss = 0.58490598
Iteration 10, loss = 0.58218204
Iteration 11, loss = 0.57951788
Iteration 12, loss = 0.57737187
Iteration 13, loss = 0.57542480
Iteration 14, loss = 0.57397735
Iteration 15, loss = 0.57273296
Iteration 16, loss = 0.57163436
Iteration 17, loss = 0.57099857
Iteration 18, loss = 0.57027721
Iteration 19, loss = 0.56979271
Iteration 20, loss = 0.56923843
Iteration 21, loss = 0.56882959
Iteration 22, loss = 0.56840195
Iteration 23, loss = 0.56807932
Iteration 24, loss = 0.56784671
Iteration 25, loss = 0.56743994
Iteration 26, loss = 0.56723510
Iteration 27, loss = 0.56695184
Iteration 28, loss = 0.56672689
Iteration 29, loss = 0.56651386
Iteration 30, loss = 0.56629256
Iteration 31, loss = 0.56613011
Iteration 32, los

/home/anapedroso/Documentos/IA-desempenho-algoritmos-classificacao/env/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/anapedroso/Documentos/IA-desempenho-algoritmos-classificacao/env/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/anapedroso/Documentos/IA-desempenho-algoritmos-classificacao/env/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/anapedroso/Documentos/IA-desempenho-algoritmos-classificacao/env/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_pe

In [29]:
for classificador in predicted_classes.keys():
    print("================================================================================================")
    print("Resultados do classificador %s\n%s\n"
          %(classificador, metrics.classification_report(haberman_classes, predicted_classes[classificador])))
    print("Matriz de confusão: \n%s\n\n\n" % metrics.confusion_matrix(haberman_classes, predicted_classes[classificador]))



Resultados do classificador arvore_decisao
              precision    recall  f1-score   support

           1       0.77      0.74      0.76       225
           2       0.35      0.38      0.36        81

    accuracy                           0.65       306
   macro avg       0.56      0.56      0.56       306
weighted avg       0.66      0.65      0.65       306


Matriz de confusão: 
[[167  58]
 [ 50  31]]



Resultados do classificador vizinhos_proximos
              precision    recall  f1-score   support

           1       0.77      0.83      0.80       225
           2       0.39      0.30      0.34        81

    accuracy                           0.69       306
   macro avg       0.58      0.56      0.57       306
weighted avg       0.67      0.69      0.68       306


Matriz de confusão: 
[[187  38]
 [ 57  24]]



Resultados do classificador naive_bayes_gaussian
              precision    recall  f1-score   support

           1       0.77      0.95      0.85       225
   