In [1]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn import model_selection
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier


dataset_haberman = pd.read_table('haberman.data', sep=',')
print("\nDataset Haberman:")
dataset_haberman


Dataset Haberman:


Age of patient at time of operation  Patients year of operation  \
0                                     30                          64   
1                                     30                          62   
2                                     30                          65   
3                                     31                          59   
4                                     31                          65   
..                                   ...                         ...   
301                                   75                          62   
302                                   76                          67   
303                                   77                          65   
304                                   78                          65   
305                                   83                          58   

     Number of positive axillary nodes detected  Survival status  
0                                             1                1  
1                                             3                1  
2                                             0                1  
3                                             2                1  
4                                             4                1  
..                                          ...              ...  
301                                           1                1  
302                                           0                1  
303                                           3                1  
304                                           1                2  
305                                           2                2  

[306 rows x 4 columns]

In [2]:
dataset_haberman.columns

Index(['Age of patient at time of operation', 'Patients year of operation',
       'Number of positive axillary nodes detected', 'Survival status'],
      dtype='object')

In [3]:
haberman_normalised = dataset_haberman.values.copy()
normalizador =  StandardScaler()

haberman_normalised = normalizador.fit_transform(dataset_haberman)
dataset_haberman['Age of patient at time of operation'] = haberman_normalised[:,0]
dataset_haberman['Patients year of operation'] = haberman_normalised[:,1]
dataset_haberman['Number of positive axillary nodes detected'] = haberman_normalised[:,2]

print("\nDataset Haberman Normalized:")
dataset_haberman


Dataset Haberman Normalized:


Age of patient at time of operation  Patients year of operation  \
0                              -2.082140                    0.353584   
1                              -2.082140                   -0.262921   
2                              -2.082140                    0.661837   
3                              -1.989426                   -1.187680   
4                              -1.989426                    0.661837   
..                                   ...                         ...   
301                             2.090018                   -0.262921   
302                             2.182732                    1.278342   
303                             2.275447                    0.661837   
304                             2.368162                    0.661837   
305                             2.831735                   -1.495933   

     Number of positive axillary nodes detected  Survival status  
0                                     -0.421592                1  
1                                     -0.142959                1  
2                                     -0.560909                1  
3                                     -0.282275                1  
4                                     -0.003642                1  
..                                          ...              ...  
301                                   -0.421592                1  
302                                   -0.560909                1  
303                                   -0.142959                1  
304                                   -0.421592                2  
305                                   -0.282275                2  

[306 rows x 4 columns]

In [4]:
haberman_values = dataset_haberman.iloc[:,0:3].values
print("\nHaberman valores dos atributos:\n")
print(haberman_values)


Haberman valores dos atributos:

[[-2.08214014e+00  3.53584065e-01 -4.21592031e-01]
 [-2.08214014e+00 -2.62921484e-01 -1.42958853e-01]
 [-2.08214014e+00  6.61836839e-01 -5.60908620e-01]
 [-1.98942552e+00 -1.18767981e+00 -2.82275442e-01]
 [-1.98942552e+00  6.61836839e-01 -3.64226377e-03]
 [-1.80399628e+00 -1.49593258e+00  8.32257270e-01]
 [-1.80399628e+00 -8.79427033e-01 -5.60908620e-01]
 [-1.71128165e+00 -1.18767981e+00 -5.60908620e-01]
 [-1.71128165e+00  9.70089614e-01  6.92940681e-01]
 [-1.71128165e+00 -1.49593258e+00  3.61858905e+00]
 [-1.71128165e+00 -8.79427033e-01 -4.21592031e-01]
 [-1.71128165e+00 -5.71174259e-01  8.32257270e-01]
 [-1.71128165e+00  1.27834239e+00  4.14307503e-01]
 [-1.71128165e+00 -8.79427033e-01 -5.60908620e-01]
 [-1.61856703e+00  3.53584065e-01  1.25020704e+00]
 [-1.61856703e+00  4.53312904e-02 -5.60908620e-01]
 [-1.52585241e+00 -8.79427033e-01 -4.21592031e-01]
 [-1.52585241e+00  1.89484794e+00 -5.60908620e-01]
 [-1.43313779e+00 -8.79427033e-01 -5.60908620e-0

In [5]:
haberman_classes = dataset_haberman.iloc[:,3].values
print("\nHaberman classes:\n")
print(haberman_classes)
print("\nHaberman classes shape:")
print(haberman_classes.shape)


Haberman classes:

[1 1 1 1 1 1 1 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 2 1 1
 1 1 1 1 1 1 2 2 2 1 1 1 1 1 1 1 2 2 1 1 1 1 1 1 1 2 2 2 2 1 1 1 1 1 1 1 2
 2 2 1 1 1 1 2 2 2 1 1 1 1 1 1 2 2 2 2 1 1 1 2 2 2 1 1 1 1 1 1 1 1 2 2 2 1
 1 1 1 2 2 1 1 1 1 1 1 1 1 2 2 1 1 1 1 1 1 1 1 1 1 2 2 1 1 1 1 2 2 2 2 1 1
 1 1 1 1 1 1 1 1 2 2 2 2 2 2 1 1 1 1 1 2 2 2 2 1 1 1 1 1 1 1 1 1 2 2 1 1 1
 1 1 1 1 1 2 2 1 1 1 1 1 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1
 1 2 2 1 1 1 1 2 2 2 1 1 1 1 1 1 2 2 2 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 2
 2 2 2 1 1 1 1 1 1 2 2 1 1 1 2 2 1 1 1 1 1 1 2 1 1 1 2 2 1 1 1 1 1 1 2 1 1
 1 1 1 2 1 1 1 1 2 2]

Haberman classes shape:
(306,)


In [6]:
kfold_treinamento = model_selection.StratifiedKFold(n_splits=5, shuffle=True, random_state=None)
kfold_ajuste_parametros = model_selection.StratifiedKFold(n_splits=3, shuffle=True, random_state=None)

In [7]:
arvore_decisao = DecisionTreeClassifier()
print("====== Iniciando busca pelos melhores parâmetros do algoritmo Arvore de decisao no dataset Transfusion ....\n")

param_dist = {'max_depth':[3,4,5,6,7,8,9,10], 'criterion': ['entropy'], 'splitter':['best','random']}
grid_search = GridSearchCV(arvore_decisao, param_grid=param_dist, cv=kfold_ajuste_parametros, scoring='accuracy', refit=False)
grid_search.fit(haberman_values, haberman_classes)
decisionTreeBestParams = grid_search.best_params_
print("Decision Tree: %s \n\n" % decisionTreeBestParams)

====== Iniciando busca pelos melhores parâmetros do algoritmo Arvore de decisao no dataset Transfusion ....

Decision Tree: {'criterion': 'entropy', 'max_depth': 3, 'splitter': 'best'} 




In [8]:
knn_vizinhos_proximos = KNeighborsClassifier()
print("====== Iniciando busca pelos melhores parâmetros do algoritmo KNN no dataset Transfusion ....\n")

param_dist = {'n_neighbors': list(np.arange(1, 10)), 'metric':['euclidean'], 'weights':['uniform', 'distance']} #Parâmetros testados
grid_search = GridSearchCV(knn_vizinhos_proximos, param_grid=param_dist, cv=kfold_ajuste_parametros, scoring='accuracy', refit=False)
grid_search.fit(haberman_values, haberman_classes)
knnBestParams = grid_search.best_params_
print("KNN: %s \n\n" % knnBestParams)

====== Iniciando busca pelos melhores parâmetros do algoritmo KNN no dataset Transfusion ....

KNN: {'metric': 'euclidean', 'n_neighbors': 9, 'weights': 'uniform'} 




In [9]:
regressao_logistica = LogisticRegression()
print("====== Iniciando busca pelos melhores parâmetros do algoritmo Regressao logistica no dataset Transfusion ....\n")

param_dist = {'penalty':['l2','none'],'tol':[0.0001,0.001, 0.01, 0.1, 1], 'max_iter':[300,400,500,600],'solver':['lbfgs','saga']} #Parâmetros testados

grid_search = GridSearchCV(regressao_logistica, param_grid=param_dist, cv=kfold_ajuste_parametros, scoring='accuracy', refit=False)
grid_search.fit(haberman_values, haberman_classes)
regressao_logistica_param = grid_search.best_params_
print("Regressão logistica: %s \n\n" % regressao_logistica_param)


====== Iniciando busca pelos melhores parâmetros do algoritmo Regressao logistica no dataset Transfusion ....

Regressão logistica: {'max_iter': 600, 'penalty': 'none', 'solver': 'saga', 'tol': 1} 




In [ ]:
rede_neural = MLPClassifier()
print("====== Iniciando busca pelos melhores parâmetros do algoritmo Redes neurais no dataset Transfusion ....\n")

param_dist = {'hidden_layer_sizes':list(np.arange(5, 10)),'activation':['logistic'], 'max_iter':[300,400,500,600],'alpha':[0.0001,0.001, 0.01, 0.1], 'solver':['sgd','adam'], 'learning_rate':['constant','invscaling','adaptive'], 'learning_rate_init':[0.001, 0.01, 0.1]} #Parâmetros testados

grid_search = GridSearchCV(rede_neural, param_grid=param_dist, cv=kfold_ajuste_parametros, scoring='accuracy', refit=False)
grid_search.fit(haberman_values, haberman_classes)
redes_neurais_param = grid_search.best_params_
print("Redes neurais: %s \n\n" % redes_neurais_param)

====== Iniciando busca pelos melhores parâmetros do algoritmo Redes neurais no dataset Transfusion ....



/home/anapedroso/Documentos/IA-desempenho-algoritmos-classificacao/env/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/anapedroso/Documentos/IA-desempenho-algoritmos-classificacao/env/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/anapedroso/Documentos/IA-desempenho-algoritmos-classificacao/env/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (400) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/anapedroso/Documentos/IA-desempenho-algoritmos-classificacao/env/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_pe

In [ ]:
predicted_classes = dict()
predicted_classes['Arvore_decisao'] = np.zeros(haberman_classes.shape)
predicted_classes['KNN_Vizinhos_proximos'] = np.zeros(haberman_classes.shape)
predicted_classes['Naive_bayes_gaussian'] = np.zeros(haberman_classes.shape)
predicted_classes['Regressao_logistica'] = np.zeros(haberman_classes.shape)
predicted_classes['Rede_neural'] = np.zeros(haberman_classes.shape)

arvore_decisao_best_param = DecisionTreeClassifier(**decisionTreeBestParams)
knn_vizinhos_proximos_best_param = KNeighborsClassifier(**knnBestParams)
naive_bayes_gaussian = GaussianNB()
regressao_logistica_best_param = LogisticRegression(**regressao_logistica_param)
rede_neural_best_param = MLPClassifier(**redes_neurais_param)

In [ ]:
for train, test in kfold_treinamento.split(haberman_values, haberman_classes):
    data_train, target_train = haberman_values[train], haberman_classes[train]
    data_test, target_test = haberman_values[test], haberman_classes[test]

    arvore_decisao = arvore_decisao_best_param.fit(data_train, target_train)
    arvore_decisao_predicted = arvore_decisao.predict(data_test)
    predicted_classes['arvore_decisao'][test] = arvore_decisao_predicted

    vizinhos_proximos = knn_vizinhos_proximos_best_param.fit(data_train, target_train)
    vizinhos_proximos_predicted = vizinhos_proximos.predict(data_test)
    predicted_classes['vizinhos_proximos'][test] = vizinhos_proximos_predicted

    naive_bayes_gaussian = naive_bayes_gaussian.fit(data_train, target_train)
    naive_bayes_gaussian_predicted = naive_bayes_gaussian.predict(data_test)
    predicted_classes['naive_bayes_gaussian'][test] = naive_bayes_gaussian_predicted

    regressao_logistica = regressao_logistica_best_param.fit(data_train, target_train)
    regressao_logistica_predicted = regressao_logistica.predict(data_test)
    predicted_classes['regressao_logistica'][test] = regressao_logistica_predicted

    rede_neural = rede_neural_best_param.fit(data_train, target_train)
    rede_neural_predicted = rede_neural.predict(data_test)
    predicted_classes['rede_neural'][test] = rede_neural_predicted

In [ ]:
for classificador in predicted_classes.keys():
    print("================================================================================================")
    print("Resultados do classificador %s\n%s\n"
          %(classificador, metrics.classification_report(haberman_classes, predicted_classes[classificador])))
    print("Matriz de confusão: \n%s\n\n\n" % metrics.confusion_matrix(haberman_classes, predicted_classes[classificador]))

