In [1]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn import model_selection
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier


dataset_haberman = pd.read_table('haberman.data', sep=',')
print("\nDataset Haberman:")
dataset_haberman


Dataset Haberman:


/home/larissa/.local/lib/python3.5/site-packages/ipykernel_launcher.py:14: FutureWarning: read_table is deprecated, use read_csv instead.
  


Age of patient at time of operation  Patients year of operation  \
0                                     30                          64   
1                                     30                          62   
2                                     30                          65   
3                                     31                          59   
4                                     31                          65   
5                                     33                          58   
6                                     33                          60   
7                                     34                          59   
8                                     34                          66   
9                                     34                          58   
10                                    34                          60   
11                                    34                          61   
12                                    34                          67   
13                                    34                          60   
14                                    35                          64   
15                                    35                          63   
16                                    36                          60   
17                                    36                          69   
18                                    37                          60   
19                                    37                          63   
20                                    37                          58   
21                                    37                          59   
22                                    37                          60   
23                                    37                          63   
24                                    38                          69   
25                                    38                          59   
26                                    38                          60   
27                                    38                          60   
28                                    38                          62   
29                                    38                          64   
..                                   ...                         ...   
276                                   67                          66   
277                                   67                          61   
278                                   67                          65   
279                                   68                          67   
280                                   68                          68   
281                                   69                          67   
282                                   69                          60   
283                                   69                          65   
284                                   69                          66   
285                                   70                          58   
286                                   70                          58   
287                                   70                          66   
288                                   70                          67   
289                                   70                          68   
290                                   70                          59   
291                                   70                          63   
292                                   71                          68   
293                                   72                          63   
294                                   72                          58   
295                                   72                          64   
296                                   72                          67   
297                                   73                          62   
298                                   73                          68   
299                                   74     

In [2]:
dataset_haberman.columns

Index(['Age of patient at time of operation', 'Patients year of operation',
       'Number of positive axillary nodes detected', 'Survival status'],
      dtype='object')

In [3]:
haberman_normalised = dataset_haberman.values.copy()
normalizador =  StandardScaler()

haberman_normalised = normalizador.fit_transform(dataset_haberman)
dataset_haberman['Age of patient at time of operation'] = haberman_normalised[:,0]
dataset_haberman['Patients year of operation'] = haberman_normalised[:,1]
dataset_haberman['Number of positive axillary nodes detected'] = haberman_normalised[:,2]

print("\nDataset Haberman Normalized:")
dataset_haberman


Dataset Haberman Normalized:


Age of patient at time of operation  Patients year of operation  \
0                              -2.082140                    0.353584   
1                              -2.082140                   -0.262921   
2                              -2.082140                    0.661837   
3                              -1.989426                   -1.187680   
4                              -1.989426                    0.661837   
5                              -1.803996                   -1.495933   
6                              -1.803996                   -0.879427   
7                              -1.711282                   -1.187680   
8                              -1.711282                    0.970090   
9                              -1.711282                   -1.495933   
10                             -1.711282                   -0.879427   
11                             -1.711282                   -0.571174   
12                             -1.711282                    1.278342   
13                             -1.711282                   -0.879427   
14                             -1.618567                    0.353584   
15                             -1.618567                    0.045331   
16                             -1.525852                   -0.879427   
17                             -1.525852                    1.894848   
18                             -1.433138                   -0.879427   
19                             -1.433138                    0.045331   
20                             -1.433138                   -1.495933   
21                             -1.433138                   -1.187680   
22                             -1.433138                   -0.879427   
23                             -1.433138                    0.045331   
24                             -1.340423                    1.894848   
25                             -1.340423                   -1.187680   
26                             -1.340423                   -0.879427   
27                             -1.340423                   -0.879427   
28                             -1.340423                   -0.262921   
29                             -1.340423                    0.353584   
..                                   ...                         ...   
276                             1.348301                    0.970090   
277                             1.348301                   -0.571174   
278                             1.348301                    0.661837   
279                             1.441016                    1.278342   
280                             1.441016                    1.586595   
281                             1.533730                    1.278342   
282                             1.533730                   -0.879427   
283                             1.533730                    0.661837   
284                             1.533730                    0.970090   
285                             1.626445                   -1.495933   
286                             1.626445                   -1.495933   
287                             1.626445                    0.970090   
288                             1.626445                    1.278342   
289                             1.626445                    1.586595   
290                             1.626445                   -1.187680   
291                             1.626445                    0.045331   
292                             1.719159                    1.586595   
293                             1.811874                    0.045331   
294                             1.811874                   -1.495933   
295                             1.811874                    0.353584   
296                             1.811874                    1.278342   
297                             1.904589                   -0.262921   
298                             1.904589                    1.586595   
299                             1.997303     

In [4]:
haberman_values = dataset_haberman.iloc[:,0:3].values
print("\nHaberman valores dos atributos:\n")
print(haberman_values)


Haberman valores dos atributos:

[[-2.08214014e+00  3.53584065e-01 -4.21592031e-01]
 [-2.08214014e+00 -2.62921484e-01 -1.42958853e-01]
 [-2.08214014e+00  6.61836839e-01 -5.60908620e-01]
 [-1.98942552e+00 -1.18767981e+00 -2.82275442e-01]
 [-1.98942552e+00  6.61836839e-01 -3.64226377e-03]
 [-1.80399628e+00 -1.49593258e+00  8.32257270e-01]
 [-1.80399628e+00 -8.79427033e-01 -5.60908620e-01]
 [-1.71128165e+00 -1.18767981e+00 -5.60908620e-01]
 [-1.71128165e+00  9.70089614e-01  6.92940681e-01]
 [-1.71128165e+00 -1.49593258e+00  3.61858905e+00]
 [-1.71128165e+00 -8.79427033e-01 -4.21592031e-01]
 [-1.71128165e+00 -5.71174259e-01  8.32257270e-01]
 [-1.71128165e+00  1.27834239e+00  4.14307503e-01]
 [-1.71128165e+00 -8.79427033e-01 -5.60908620e-01]
 [-1.61856703e+00  3.53584065e-01  1.25020704e+00]
 [-1.61856703e+00  4.53312904e-02 -5.60908620e-01]
 [-1.52585241e+00 -8.79427033e-01 -4.21592031e-01]
 [-1.52585241e+00  1.89484794e+00 -5.60908620e-01]
 [-1.43313779e+00 -8.79427033e-01 -5.60908620e-0

In [5]:
haberman_classes = dataset_haberman.iloc[:,3].values
print("\nHaberman classes:\n")
print(haberman_classes)
print("\nHaberman classes shape:")
print(haberman_classes.shape)


Haberman classes:

[1 1 1 1 1 1 1 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 2 1 1
 1 1 1 1 1 1 2 2 2 1 1 1 1 1 1 1 2 2 1 1 1 1 1 1 1 2 2 2 2 1 1 1 1 1 1 1 2
 2 2 1 1 1 1 2 2 2 1 1 1 1 1 1 2 2 2 2 1 1 1 2 2 2 1 1 1 1 1 1 1 1 2 2 2 1
 1 1 1 2 2 1 1 1 1 1 1 1 1 2 2 1 1 1 1 1 1 1 1 1 1 2 2 1 1 1 1 2 2 2 2 1 1
 1 1 1 1 1 1 1 1 2 2 2 2 2 2 1 1 1 1 1 2 2 2 2 1 1 1 1 1 1 1 1 1 2 2 1 1 1
 1 1 1 1 1 2 2 1 1 1 1 1 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1
 1 2 2 1 1 1 1 2 2 2 1 1 1 1 1 1 2 2 2 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 2
 2 2 2 1 1 1 1 1 1 2 2 1 1 1 2 2 1 1 1 1 1 1 2 1 1 1 2 2 1 1 1 1 1 1 2 1 1
 1 1 1 2 1 1 1 1 2 2]

Haberman classes shape:
(306,)


In [6]:
kfold_treinamento = model_selection.StratifiedKFold(n_splits=5, shuffle=True, random_state=None)
kfold_ajuste_parametros = model_selection.StratifiedKFold(n_splits=3, shuffle=True, random_state=None)

In [7]:
arvore_decisao = DecisionTreeClassifier()
print("====== Iniciando busca pelos melhores parâmetros do algoritmo Arvore de decisao no dataset Transfusion ....\n")
param_dist = {'max_depth':list(np.arange(1,10)), 'min_samples_split':list(np.arange(1,10)) ,'criterion':['entropy'], 'splitter':['best','random']}
grid_search = GridSearchCV(arvore_decisao, param_grid=param_dist, cv=kfold_ajuste_parametros, scoring='accuracy', refit=False)
grid_search.fit(haberman_values, haberman_classes)
decisionTreeBestParams = grid_search.best_params_
print("Decision Tree: %s \n\n" % decisionTreeBestParams)

====== Iniciando busca pelos melhores parâmetros do algoritmo Arvore de decisao no dataset Transfusion ....

Decision Tree: {'criterion': 'entropy', 'splitter': 'random', 'min_samples_split': 2, 'max_depth': 1} 




/home/larissa/.local/lib/python3.5/site-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: min_samples_split must be an integer greater than 1 or a float in (0.0, 1.0]; got the integer 1

  FitFailedWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: min_samples_split must be an integer greater than 1 or a float in (0.0, 1.0]; got the integer 1

  FitFailedWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: min_samples_split must be an integer greater than 1 or a floa

In [8]:
knn_vizinhos_proximos = KNeighborsClassifier()
print("====== Iniciando busca pelos melhores parâmetros do algoritmo KNN no dataset Transfusion ....\n")
param_dist = {'n_neighbors':[3,5,7,9], 'metric':['euclidean', 'manhattan'], 'weights':['uniform', 'distance']} #Parâmetros testados
grid_search = GridSearchCV(knn_vizinhos_proximos, param_grid=param_dist, cv=kfold_ajuste_parametros, scoring='accuracy', refit=False)
grid_search.fit(haberman_values, haberman_classes)
knnBestParams = grid_search.best_params_
print("KNN: %s \n\n" % knnBestParams)

====== Iniciando busca pelos melhores parâmetros do algoritmo KNN no dataset Transfusion ....

KNN: {'n_neighbors': 9, 'metric': 'euclidean', 'weights': 'uniform'} 




In [9]:
regressao_logistica = LogisticRegression()
print("====== Iniciando busca pelos melhores parâmetros do algoritmo Regressao logistica no dataset Transfusion ....\n")
param_dist = {'penalty':['l2','l1'], 'max_iter':[200,300,400,500],'solver':['liblinear','sag','saga']} #Parâmetros testados
grid_search = GridSearchCV(regressao_logistica, param_grid=param_dist, cv=kfold_ajuste_parametros, scoring='accuracy', refit=False)
grid_search.fit(haberman_values, haberman_classes)
regressao_logistica_param = grid_search.best_params_
print("Regressão logistica: %s \n\n" % regressao_logistica_param)


====== Iniciando busca pelos melhores parâmetros do algoritmo Regressao logistica no dataset Transfusion ....

Regressão logistica: {'solver': 'liblinear', 'penalty': 'l2', 'max_iter': 200} 




/home/larissa/.local/lib/python3.5/site-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Solver sag supports only 'l2' or 'none' penalties, got l1 penalty.

  FitFailedWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Solver sag supports only 'l2' or 'none' penalties, got l1 penalty.

  FitFailedWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Solver sag supports only 'l2' or 'none' penalties, got l1 penalty.

  FitFailedWarning)
/home/larissa/.local/lib/python

In [10]:
rede_neural = MLPClassifier()
print("====== Iniciando busca pelos melhores parâmetros do algoritmo Redes neurais no dataset Transfusion ....\n")
param_dist = {'hidden_layer_sizes':list(np.arange(10,20)),'activation':['logistic','identity','tanh'], 'max_iter':[100,200,300,400],'alpha':[0.0001,0.001, 0.01, 0.1], 'solver':['sgd','adam']}
grid_search = GridSearchCV(rede_neural, param_grid=param_dist, cv=kfold_ajuste_parametros, scoring='accuracy', refit=False)
grid_search.fit(haberman_values, haberman_classes)
redes_neurais_param = grid_search.best_params_
print("Redes neurais: %s \n\n" % redes_neurais_param)

====== Iniciando busca pelos melhores parâmetros do algoritmo Redes neurais no dataset Transfusion ....

Redes neurais: {'activation': 'tanh', 'solver': 'sgd', 'max_iter': 100, 'alpha': 0.1, 'hidden_layer_sizes': 12} 




/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.

In [11]:
predicted_classes = dict()
predicted_classes['Arvore_decisao'] = np.zeros(haberman_classes.shape)
predicted_classes['KNN_Vizinhos_proximos'] = np.zeros(haberman_classes.shape)
predicted_classes['Naive_bayes_gaussian'] = np.zeros(haberman_classes.shape)
predicted_classes['Regressao_logistica'] = np.zeros(haberman_classes.shape)
predicted_classes['Rede_neural'] = np.zeros(haberman_classes.shape)

arvore_decisao_best_param = DecisionTreeClassifier(**decisionTreeBestParams)
knn_vizinhos_proximos_best_param = KNeighborsClassifier(**knnBestParams)
naive_bayes_gaussian = GaussianNB()
regressao_logistica_best_param = LogisticRegression(**regressao_logistica_param)
rede_neural_best_param = MLPClassifier(**redes_neurais_param)

In [12]:
for train, test in kfold_treinamento.split(haberman_values, haberman_classes):
    data_train, target_train = haberman_values[train], haberman_classes[train]
    data_test, target_test = haberman_values[test], haberman_classes[test]

    arvore_decisao_best_param = arvore_decisao_best_param.fit(data_train, target_train)
    arvore_decisao_predicted = arvore_decisao_best_param.predict(data_test)
    predicted_classes['Arvore_decisao'][test] = arvore_decisao_predicted

    knn_vizinhos_proximos_best_param = knn_vizinhos_proximos_best_param.fit(data_train, target_train)
    vizinhos_proximos_predicted = knn_vizinhos_proximos_best_param.predict(data_test)
    predicted_classes['KNN_Vizinhos_proximos'][test] = vizinhos_proximos_predicted

    naive_bayes_gaussian = naive_bayes_gaussian.fit(data_train, target_train)
    naive_bayes_gaussian_predicted = naive_bayes_gaussian.predict(data_test)
    predicted_classes['Naive_bayes_gaussian'][test] = naive_bayes_gaussian_predicted

    regressao_logistica_best_param = regressao_logistica_best_param.fit(data_train, target_train)
    regressao_logistica_predicted = regressao_logistica_best_param.predict(data_test)
    predicted_classes['Regressao_logistica'][test] = regressao_logistica_predicted

    rede_neural_best_param = rede_neural_best_param.fit(data_train, target_train)
    rede_neural_predicted = rede_neural_best_param.predict(data_test)
    predicted_classes['Rede_neural'][test] = rede_neural_predicted

/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.

In [13]:
for classificador in predicted_classes.keys():
    print("================================================================================================")
    print("Resultados do classificador %s\n%s\n"
          %(classificador, metrics.classification_report(haberman_classes, predicted_classes[classificador])))
    print("Matriz de confusão: \n%s\n\n\n" % metrics.confusion_matrix(haberman_classes, predicted_classes[classificador]))



Resultados do classificador Arvore_decisao
              precision    recall  f1-score   support

           1       0.75      0.97      0.84       225
           2       0.50      0.09      0.15        81

    accuracy                           0.74       306
   macro avg       0.62      0.53      0.50       306
weighted avg       0.68      0.74      0.66       306


Matriz de confusão: 
[[218   7]
 [ 74   7]]



Resultados do classificador Regressao_logistica
              precision    recall  f1-score   support

           1       0.76      0.96      0.85       225
           2       0.58      0.17      0.27        81

    accuracy                           0.75       306
   macro avg       0.67      0.56      0.56       306
weighted avg       0.72      0.75      0.69       306


Matriz de confusão: 
[[215  10]
 [ 67  14]]



Resultados do classificador Naive_bayes_gaussian
              precision    recall  f1-score   support

           1       0.77      0.95      0.85       225
 