In [10]:
from sklearn import tree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn import model_selection
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn import metrics
import pandas as pd
import numpy as np

balanceScale = pd.read_table('balance-scale.data', sep=',')
print("\nDataset Balance Scale:")
balanceScale


Dataset Balance Scale:


Class-Name  Left-Weight  Left-Distance  Light-Weight  Light-Distance
0             2            1              1             1               1
1             1            1              1             1               2
2             1            1              1             1               3
3             1            1              1             1               4
4             1            1              1             1               5
..          ...          ...            ...           ...             ...
620           3            5              5             5               1
621           3            5              5             5               2
622           3            5              5             5               3
623           3            5              5             5               4
624           2            5              5             5               5

[625 rows x 5 columns]

In [11]:
balanceScale.columns

Index(['Class-Name', 'Left-Weight', 'Left-Distance', 'Light-Weight',
       'Light-Distance'],
      dtype='object')

In [12]:
balanceScaleNormalized = balanceScale.values.copy()
normalizador =  StandardScaler()

# Codificar coluna que tenha caractere para numero e depois remover a coluna
# enc = OneHotEncoder(handle_unknown='ignore')
# enc_df = pd.DataFrame(enc.fit_transform(balanceScale[['Class-Name']]).toarray())
# balanceScale = balanceScale.join(enc_df)
# balanceScale = balanceScale.drop(columns = ['Class-Name'])
# balanceScale

# balanceScaleNormalized = normalizador.fit_transform(balanceScale)
# balanceScale['Class-Name'] = balanceScaleNormalized[:,0]
# balanceScale['Left-Weight'] = balanceScaleNormalized[:,1]
# balanceScale['Left-Distance'] = balanceScaleNormalized[:,2]
# balanceScale['Right-Weight'] = balanceScaleNormalized[:,3]
# balanceScale['Right-Distance'] = balanceScaleNormalized[:,4]
#
# print("\nDataset Balance Scale Normalized:")
balanceScale


Class-Name  Left-Weight  Left-Distance  Light-Weight  Light-Distance
0             2            1              1             1               1
1             1            1              1             1               2
2             1            1              1             1               3
3             1            1              1             1               4
4             1            1              1             1               5
..          ...          ...            ...           ...             ...
620           3            5              5             5               1
621           3            5              5             5               2
622           3            5              5             5               3
623           3            5              5             5               4
624           2            5              5             5               5

[625 rows x 5 columns]

In [13]:
balanceScaleValues = balanceScale.iloc[:,0:5].values
print("\nBalance Scale features:\n")
print(balanceScaleValues)



Balance Scale features:

[[2 1 1 1 1]
 [1 1 1 1 2]
 [1 1 1 1 3]
 ...
 [3 5 5 5 3]
 [3 5 5 5 4]
 [2 5 5 5 5]]


In [14]:
balanceScaleClasses = balanceScale.iloc[:,4].values
print("\nBalance Scale classes:\n")
print(balanceScaleClasses)
print("\nBalance Scale classes shape:")
print(balanceScaleClasses.shape)





Balance Scale classes:

[1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2
 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4
 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1
 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3
 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5
 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2
 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4
 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1
 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3
 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5
 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2
 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4
 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1


In [15]:
kf = model_selection.StratifiedKFold(n_splits = 5)
arvore_decisao = tree.DecisionTreeClassifier(criterion='entropy', splitter='best', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, random_state=None, max_leaf_nodes=None, min_impurity_decrease=0.0, min_impurity_split=None, class_weight=None, presort='deprecated', ccp_alpha=0.0)
vizinhos_proximos = KNeighborsClassifier(n_neighbors=3, weights = 'distance')
naive_bayes_gaussian = GaussianNB()
regressao_logistica = LogisticRegression(penalty='l2', dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='saga', max_iter=100, multi_class='auto', verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)
rede_neural = MLPClassifier(hidden_layer_sizes=(5,), activation="logistic", max_iter= 300, alpha=0.001, solver="sgd", tol=1e-4, verbose=True, learning_rate_init=.01)

In [16]:
predicted_classes = dict()
predicted_classes['arvore_decisao'] = np.zeros(balanceScaleClasses.shape)
predicted_classes['vizinhos_proximos'] = np.zeros(balanceScaleClasses.shape)
predicted_classes['naive_bayes_gaussian'] = np.zeros(balanceScaleClasses.shape)
predicted_classes['regressao_logistica'] = np.zeros(balanceScaleClasses.shape)
predicted_classes['rede_neural'] = np.zeros(balanceScaleClasses.shape)

In [17]:
for train, test in kf.split(balanceScaleValues, balanceScaleClasses):
    data_train, target_train = balanceScaleValues[train], balanceScaleClasses[train]
    data_test, target_test = balanceScaleValues[test], balanceScaleClasses[test]

    arvore_decisao = arvore_decisao.fit(data_train, target_train)
    arvore_decisao_predicted = arvore_decisao.predict(data_test)
    predicted_classes['arvore_decisao'][test] = arvore_decisao_predicted

    vizinhos_proximos = vizinhos_proximos.fit(data_train, target_train)
    vizinhos_proximos_predicted = vizinhos_proximos.predict(data_test)
    predicted_classes['vizinhos_proximos'][test] = vizinhos_proximos_predicted

    naive_bayes_gaussian = naive_bayes_gaussian.fit(data_train, target_train)
    naive_bayes_gaussian_predicted = naive_bayes_gaussian.predict(data_test)
    predicted_classes['naive_bayes_gaussian'][test] = naive_bayes_gaussian_predicted

    regressao_logistica = regressao_logistica.fit(data_train, target_train)
    regressao_logistica_predicted = regressao_logistica.predict(data_test)
    predicted_classes['regressao_logistica'][test] = regressao_logistica_predicted

    rede_neural = rede_neural.fit(data_train, target_train)
    rede_neural_predicted = rede_neural.predict(data_test)
    predicted_classes['rede_neural'][test] = rede_neural_predicted

Iteration 1, loss = 1.68298971
Iteration 2, loss = 1.67652829
Iteration 3, loss = 1.66671590
Iteration 4, loss = 1.65727770
Iteration 5, loss = 1.64665213
Iteration 6, loss = 1.63854895
Iteration 7, loss = 1.63065888
Iteration 8, loss = 1.62491272
Iteration 9, loss = 1.61945917
Iteration 10, loss = 1.61584000
Iteration 11, loss = 1.61222134
Iteration 12, loss = 1.60964282
Iteration 13, loss = 1.60702550
Iteration 14, loss = 1.60536307
Iteration 15, loss = 1.60321115
Iteration 16, loss = 1.60148061
Iteration 17, loss = 1.59971245
Iteration 18, loss = 1.59807684
Iteration 19, loss = 1.59660742
Iteration 20, loss = 1.59484174
Iteration 21, loss = 1.59304620
Iteration 22, loss = 1.59104497
Iteration 23, loss = 1.58903737
Iteration 24, loss = 1.58690715
Iteration 25, loss = 1.58460567
Iteration 26, loss = 1.58197501
Iteration 27, loss = 1.57930816
Iteration 28, loss = 1.57630947
Iteration 29, loss = 1.57316832
Iteration 30, loss = 1.56978689
Iteration 31, loss = 1.56622535
Iteration 32, los

c:\users\david\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\linear_model\_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
c:\users\david\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\users\david\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\linear_model\_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
c:\users\david\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't conver

In [18]:
for classificador in predicted_classes.keys():
    print("================================================================================================")
    print("Resultados do classificador %s\n%s\n"
          %(classificador, metrics.classification_report(balanceScaleClasses, predicted_classes[classificador])))
    print("Matriz de confusão: \n%s\n\n\n" % metrics.confusion_matrix(balanceScaleClasses, predicted_classes[classificador]))




Resultados do classificador arvore_decisao
              precision    recall  f1-score   support

           1       1.00      1.00      1.00       125
           2       1.00      1.00      1.00       125
           3       1.00      1.00      1.00       125
           4       1.00      1.00      1.00       125
           5       1.00      1.00      1.00       125

    accuracy                           1.00       625
   macro avg       1.00      1.00      1.00       625
weighted avg       1.00      1.00      1.00       625


Matriz de confusão: 
[[125   0   0   0   0]
 [  0 125   0   0   0]
 [  0   0 125   0   0]
 [  0   0   0 125   0]
 [  0   0   0   0 125]]



Resultados do classificador vizinhos_proximos
              precision    recall  f1-score   support

           1       0.96      0.97      0.96       125
           2       0.91      0.94      0.93       125
           3       0.97      0.92      0.94       125
           4       0.98      0.98      0.98       125
          