In [47]:
from sklearn import tree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn import model_selection
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn import metrics
import pandas as pd
import numpy as np

balanceScale = pd.read_table('balance-scale.data', sep=',')
print("\nDataset Balance Scale:")
balanceScale


Dataset Balance Scale:


Class-Name  Left-Weight  Left-Distance  Right-Weight  Right-Distance
0            B            1              1             1               1
1            R            1              1             1               2
2            R            1              1             1               3
3            R            1              1             1               4
4            R            1              1             1               5
..         ...          ...            ...           ...             ...
620          L            5              5             5               1
621          L            5              5             5               2
622          L            5              5             5               3
623          L            5              5             5               4
624          B            5              5             5               5

[625 rows x 5 columns]

In [48]:
balanceScale.columns

Index(['Class-Name', 'Left-Weight', 'Left-Distance', 'Right-Weight',
       'Right-Distance'],
      dtype='object')

In [49]:
balanceScaleNormalized = balanceScale.values.copy()
normalizador =  StandardScaler()

# Codificar coluna que tenha caractere para numero e depois remover a coluna
enc = OneHotEncoder(handle_unknown='ignore')
enc_df = pd.DataFrame(enc.fit_transform(balanceScale[['Class-Name']]).toarray())
balanceScale = balanceScale.join(enc_df)
balanceScale = balanceScale.drop(columns = ['Class-Name'])
balanceScale

# balanceScaleNormalized = normalizador.fit_transform(balanceScale)
# balanceScale['Class-Name'] = balanceScaleNormalized[:,0]
# balanceScale['Left-Weight'] = balanceScaleNormalized[:,1]
# balanceScale['Left-Distance'] = balanceScaleNormalized[:,2]
# balanceScale['Right-Weight'] = balanceScaleNormalized[:,3]
# balanceScale['Right-Distance'] = balanceScaleNormalized[:,4]
#
# print("\nDataset Balance Scale Normalized:")
# balanceScale
#

Left-Weight  Left-Distance  Right-Weight  Right-Distance    0    1    2
0              1              1             1               1  1.0  0.0  0.0
1              1              1             1               2  0.0  0.0  1.0
2              1              1             1               3  0.0  0.0  1.0
3              1              1             1               4  0.0  0.0  1.0
4              1              1             1               5  0.0  0.0  1.0
..           ...            ...           ...             ...  ...  ...  ...
620            5              5             5               1  0.0  1.0  0.0
621            5              5             5               2  0.0  1.0  0.0
622            5              5             5               3  0.0  1.0  0.0
623            5              5             5               4  0.0  1.0  0.0
624            5              5             5               5  1.0  0.0  0.0

[625 rows x 7 columns]

In [50]:
balanceScaleValues = balanceScale.iloc[:,0:5].values
print("\nBalance Scale features:\n")
print(balanceScaleValues)



Balance Scale features:

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 2. 0.]
 [1. 1. 1. 3. 0.]
 ...
 [5. 5. 5. 3. 0.]
 [5. 5. 5. 4. 0.]
 [5. 5. 5. 5. 1.]]


In [51]:
balanceScaleClasses = balanceScale.iloc[:,4].values
print("\nBalance Scale classes:\n")
print(balanceScaleClasses)
print("\nBalance Scale classes shape:")
print(balanceScaleClasses.shape)





Balance Scale classes:

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 0. 0. 0. 0. 0. 0. 0. 0

In [52]:
kf = model_selection.StratifiedKFold(n_splits = 5)
arvore_decisao = tree.DecisionTreeClassifier(criterion='entropy', splitter='best', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, random_state=None, max_leaf_nodes=None, min_impurity_decrease=0.0, min_impurity_split=None, class_weight=None, presort='deprecated', ccp_alpha=0.0)
vizinhos_proximos = KNeighborsClassifier(n_neighbors=3, weights = 'distance')
naive_bayes_gaussian = GaussianNB()
regressao_logistica = LogisticRegression(penalty='l2', dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='saga', max_iter=100, multi_class='auto', verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)
rede_neural = MLPClassifier(hidden_layer_sizes=(5,), activation="logistic", max_iter= 300, alpha=0.001, solver="sgd", tol=1e-4, verbose=True, learning_rate_init=.01)

In [53]:
predicted_classes = dict()
predicted_classes['arvore_decisao'] = np.zeros(balanceScaleClasses.shape)
predicted_classes['vizinhos_proximos'] = np.zeros(balanceScaleClasses.shape)
predicted_classes['naive_bayes_gaussian'] = np.zeros(balanceScaleClasses.shape)
predicted_classes['regressao_logistica'] = np.zeros(balanceScaleClasses.shape)
predicted_classes['rede_neural'] = np.zeros(balanceScaleClasses.shape)

In [54]:
for train, test in kf.split(balanceScaleValues, balanceScaleClasses):
    data_train, target_train = balanceScaleValues[train], balanceScaleClasses[train]
    data_test, target_test = balanceScaleValues[test], balanceScaleClasses[test]

    arvore_decisao = arvore_decisao.fit(data_train, target_train)
    arvore_decisao_predicted = arvore_decisao.predict(data_test)
    predicted_classes['arvore_decisao'][test] = arvore_decisao_predicted

    vizinhos_proximos = vizinhos_proximos.fit(data_train, target_train)
    vizinhos_proximos_predicted = vizinhos_proximos.predict(data_test)
    predicted_classes['vizinhos_proximos'][test] = vizinhos_proximos_predicted

    naive_bayes_gaussian = naive_bayes_gaussian.fit(data_train, target_train)
    naive_bayes_gaussian_predicted = naive_bayes_gaussian.predict(data_test)
    predicted_classes['naive_bayes_gaussian'][test] = naive_bayes_gaussian_predicted

    regressao_logistica = regressao_logistica.fit(data_train, target_train)
    regressao_logistica_predicted = regressao_logistica.predict(data_test)
    predicted_classes['regressao_logistica'][test] = regressao_logistica_predicted

    rede_neural = rede_neural.fit(data_train, target_train)
    rede_neural_predicted = rede_neural.predict(data_test)
    predicted_classes['rede_neural'][test] = rede_neural_predicted

c:\users\david\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\linear_model\_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
c:\users\david\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\linear_model\_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
c:\users\david\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\linear_model\_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
c:\users\david\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\linear_model\_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
c:\u

Iteration 1, loss = 0.63173028
Iteration 2, loss = 0.60026911
Iteration 3, loss = 0.55577056
Iteration 4, loss = 0.50735210
Iteration 5, loss = 0.46045838
Iteration 6, loss = 0.41987167
Iteration 7, loss = 0.38485362
Iteration 8, loss = 0.35717595
Iteration 9, loss = 0.33548313
Iteration 10, loss = 0.31901997
Iteration 11, loss = 0.30692295
Iteration 12, loss = 0.29684170
Iteration 13, loss = 0.29052391
Iteration 14, loss = 0.28600121
Iteration 15, loss = 0.28174844
Iteration 16, loss = 0.27916865
Iteration 17, loss = 0.27722391
Iteration 18, loss = 0.27563980
Iteration 19, loss = 0.27467011
Iteration 20, loss = 0.27381200
Iteration 21, loss = 0.27318269
Iteration 22, loss = 0.27287749
Iteration 23, loss = 0.27242075
Iteration 24, loss = 0.27214715
Iteration 25, loss = 0.27198579
Iteration 26, loss = 0.27182084
Iteration 27, loss = 0.27165425
Iteration 28, loss = 0.27154512
Iteration 29, loss = 0.27152954
Iteration 30, loss = 0.27140283
Iteration 31, loss = 0.27131524
Iteration 32, los

In [55]:
for classificador in predicted_classes.keys():
    print("================================================================================================")
    print("Resultados do classificador %s\n%s\n"
          %(classificador, metrics.classification_report(balanceScaleClasses, predicted_classes[classificador])))
    print("Matriz de confusão: \n%s\n\n\n" % metrics.confusion_matrix(balanceScaleClasses, predicted_classes[classificador]))




Resultados do classificador arvore_decisao
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       576
         1.0       1.00      1.00      1.00        49

    accuracy                           1.00       625
   macro avg       1.00      1.00      1.00       625
weighted avg       1.00      1.00      1.00       625


Matriz de confusão: 
[[576   0]
 [  0  49]]



Resultados do classificador vizinhos_proximos
              precision    recall  f1-score   support

         0.0       0.95      1.00      0.97       576
         1.0       1.00      0.37      0.54        49

    accuracy                           0.95       625
   macro avg       0.97      0.68      0.76       625
weighted avg       0.95      0.95      0.94       625


Matriz de confusão: 
[[576   0]
 [ 31  18]]



Resultados do classificador naive_bayes_gaussian
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       576
   

c:\users\david\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
