In [28]:
from sklearn import tree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn import model_selection
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
import pandas as pd
import numpy as np


dataset_contraceptive = pd.read_table('contraceptive.data', sep=',')
print("\nDataset Contraceptive:")
dataset_contraceptive


Dataset Contraceptive:


Wifes age  Wifes education  Husbands education  \
0            24                2                   3   
1            45                1                   3   
2            43                2                   3   
3            42                3                   2   
4            36                3                   3   
...         ...              ...                 ...   
1468         33                4                   4   
1469         33                4                   4   
1470         39                3                   3   
1471         33                3                   3   
1472         17                3                   3   

      Number of children ever born  Wifes religion   Wifes now working  \
0                                3               1                   1   
1                               10               1                   1   
2                                7               1                   1   
3                                9               1                   1   
4                                8               1                   1   
...                            ...             ...                 ...   
1468                             2               1                   0   
1469                             3               1                   1   
1470                             8               1                   0   
1471                             4               1                   0   
1472                             1               1                   1   

      Husbands occupation  Standard-of-living index  Media exposure  \
0                       2                         3               0   
1                       3                         4               0   
2                       3                         4               0   
3                       3                         3               0   
4                       3                         2               0   
...                   ...                       ...             ...   
1468                    2                         4               0   
1469                    1                         4               0   
1470                    1                         4               0   
1471                    2                         2               0   
1472                    2                         4               0   

      Contraceptive method used  
0                             1  
1                             1  
2                             1  
3                             1  
4                             1  
...                         ...  
1468                          3  
1469                          3  
1470                          3  
1471                          3  
1472                          3  

[1473 rows x 10 columns]

In [18]:
dataset_contraceptive.columns


Index(['Wifes age', 'Wifes education', 'Husbands education',
       'Number of children ever born', 'Wifes religion', ' Wifes now working',
       'Husbands occupation', 'Standard-of-living index', 'Media exposure',
       'Contraceptive method used'],
      dtype='object')

In [22]:
contraceptive_values = dataset_contraceptive.iloc[:,0:9].values
print("\nContraceptive features:\n")
print(contraceptive_values)

print("\nContraceptive features shape:")
print(contraceptive_values.shape)


Contraceptive features:

[[24  2  3 ...  2  3  0]
 [45  1  3 ...  3  4  0]
 [43  2  3 ...  3  4  0]
 ...
 [39  3  3 ...  1  4  0]
 [33  3  3 ...  2  2  0]
 [17  3  3 ...  2  4  0]]

Contraceptive features shape:
(1473, 9)


In [23]:
contraceptive_classes = dataset_contraceptive.iloc[:,9].values
print("\nContraceptive classes:\n")
print(contraceptive_classes)
print("\nContraceptive classes shape:")
print(contraceptive_classes.shape)


Contraceptive classes:

[1 1 1 ... 3 3 3]

Contraceptive classes shape:
(1473,)


In [24]:
kf = model_selection.StratifiedKFold(n_splits = 5)
arvore_decisao = tree.DecisionTreeClassifier(criterion='entropy', splitter='best', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, random_state=None, max_leaf_nodes=None, min_impurity_decrease=0.0, min_impurity_split=None, class_weight=None, presort='deprecated', ccp_alpha=0.0)
vizinhos_proximos = KNeighborsClassifier(n_neighbors=3, weights = 'distance')
naive_bayes_gaussian = GaussianNB()
regressao_logistica = LogisticRegression(penalty='l2', dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='saga', max_iter=100, multi_class='auto', verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)
rede_neural = MLPClassifier(hidden_layer_sizes=(5,), activation="logistic", max_iter= 300, alpha=0.001, solver="sgd", tol=1e-4, verbose=True, learning_rate_init=.01)

In [25]:
predicted_classes = dict()
predicted_classes['arvore_decisao'] = np.zeros(contraceptive_classes.shape)
predicted_classes['vizinhos_proximos'] = np.zeros(contraceptive_classes.shape)
predicted_classes['naive_bayes_gaussian'] = np.zeros(contraceptive_classes.shape)
predicted_classes['regressao_logistica'] = np.zeros(contraceptive_classes.shape)
predicted_classes['rede_neural'] = np.zeros(contraceptive_classes.shape)

In [26]:
for train, test in kf.split(contraceptive_values, contraceptive_classes):
    data_train, target_train = contraceptive_values[train], contraceptive_classes[train]
    data_test, target_test = contraceptive_values[test], contraceptive_classes[test]

    arvore_decisao = arvore_decisao.fit(data_train, target_train)
    arvore_decisao_predicted = arvore_decisao.predict(data_test)
    predicted_classes['arvore_decisao'][test] = arvore_decisao_predicted

    vizinhos_proximos = vizinhos_proximos.fit(data_train, target_train)
    vizinhos_proximos_predicted = vizinhos_proximos.predict(data_test)
    predicted_classes['vizinhos_proximos'][test] = vizinhos_proximos_predicted

    naive_bayes_gaussian = naive_bayes_gaussian.fit(data_train, target_train)
    naive_bayes_gaussian_predicted = naive_bayes_gaussian.predict(data_test)
    predicted_classes['naive_bayes_gaussian'][test] = naive_bayes_gaussian_predicted

    regressao_logistica = regressao_logistica.fit(data_train, target_train)
    regressao_logistica_predicted = regressao_logistica.predict(data_test)
    predicted_classes['regressao_logistica'][test] = regressao_logistica_predicted

    rede_neural = rede_neural.fit(data_train, target_train)
    rede_neural_predicted = rede_neural.predict(data_test)
    predicted_classes['rede_neural'][test] = rede_neural_predicted

/home/anapedroso/Documentos/IA-desempenho-algoritmos-classificacao/env/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/anapedroso/Documentos/IA-desempenho-algoritmos-classificacao/env/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/anapedroso/Documentos/IA-desempenho-algoritmos-classificacao/env/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/anapedroso/Documentos/IA-desempenho-algoritmos-classificacao/env/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:329: ConvergenceWarning: The max_iter 

Iteration 1, loss = 1.07593644
Iteration 2, loss = 1.07136764
Iteration 3, loss = 1.06887229
Iteration 4, loss = 1.06785272
Iteration 5, loss = 1.06749855
Iteration 6, loss = 1.06725973
Iteration 7, loss = 1.06712127
Iteration 8, loss = 1.06717109
Iteration 9, loss = 1.06710908
Iteration 10, loss = 1.06704979
Iteration 11, loss = 1.06708844
Iteration 12, loss = 1.06710580
Iteration 13, loss = 1.06709748
Iteration 14, loss = 1.06701612
Iteration 15, loss = 1.06695209
Iteration 16, loss = 1.06695255
Iteration 17, loss = 1.06699154
Iteration 18, loss = 1.06695342
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.
Iteration 1, loss = 1.12046579
Iteration 2, loss = 1.08771384
Iteration 3, loss = 1.07061444
Iteration 4, loss = 1.06691385
Iteration 5, loss = 1.06745108
Iteration 6, loss = 1.06706597
Iteration 7, loss = 1.06684070
Iteration 8, loss = 1.06622478
Iteration 9, loss = 1.06570574
Iteration 10, loss = 1.06568397
Iteration 11, loss = 1.06516742


In [27]:
for classificador in predicted_classes.keys():
    print("================================================================================================")
    print("Resultados do classificador %s\n%s\n"
          %(classificador, metrics.classification_report(contraceptive_classes, predicted_classes[classificador])))
    print("Matriz de confusão: \n%s\n\n\n" % metrics.confusion_matrix(contraceptive_classes, predicted_classes[classificador]))

Resultados do classificador arvore_decisao
              precision    recall  f1-score   support

           1       0.57      0.59      0.58       629
           2       0.35      0.37      0.36       333
           3       0.43      0.41      0.42       511

    accuracy                           0.48      1473
   macro avg       0.45      0.45      0.45      1473
weighted avg       0.47      0.48      0.48      1473


Matriz de confusão: 
[[370  91 168]
 [104 122 107]
 [171 131 209]]



Resultados do classificador vizinhos_proximos
              precision    recall  f1-score   support

           1       0.54      0.59      0.56       629
           2       0.35      0.33      0.34       333
           3       0.44      0.41      0.42       511

    accuracy                           0.47      1473
   macro avg       0.44      0.44      0.44      1473
weighted avg       0.46      0.47      0.46      1473


Matriz de confusão: 
[[370  98 161]
 [116 109 108]
 [200 101 210]]



Resulta