In [12]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn import model_selection
from sklearn import metrics
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier


dataset_contraceptive = pd.read_table('contraceptive.data', sep=',')
print("\nDataset Contraceptive:")
dataset_contraceptive


Dataset Contraceptive:


Wifes age  Wifes education  Husbands education  \
0            24                2                   3   
1            45                1                   3   
2            43                2                   3   
3            42                3                   2   
4            36                3                   3   
...         ...              ...                 ...   
1468         33                4                   4   
1469         33                4                   4   
1470         39                3                   3   
1471         33                3                   3   
1472         17                3                   3   

      Number of children ever born  Wifes religion   Wifes now working  \
0                                3               1                   1   
1                               10               1                   1   
2                                7               1                   1   
3                                9               1                   1   
4                                8               1                   1   
...                            ...             ...                 ...   
1468                             2               1                   0   
1469                             3               1                   1   
1470                             8               1                   0   
1471                             4               1                   0   
1472                             1               1                   1   

      Husbands occupation  Standard-of-living index  Media exposure  \
0                       2                         3               0   
1                       3                         4               0   
2                       3                         4               0   
3                       3                         3               0   
4                       3                         2               0   
...                   ...                       ...             ...   
1468                    2                         4               0   
1469                    1                         4               0   
1470                    1                         4               0   
1471                    2                         2               0   
1472                    2                         4               0   

      Contraceptive method used  
0                             1  
1                             1  
2                             1  
3                             1  
4                             1  
...                         ...  
1468                          3  
1469                          3  
1470                          3  
1471                          3  
1472                          3  

[1473 rows x 10 columns]

In [13]:
dataset_contraceptive.columns


Index(['Wifes age', 'Wifes education', 'Husbands education',
       'Number of children ever born', 'Wifes religion', ' Wifes now working',
       'Husbands occupation', 'Standard-of-living index', 'Media exposure',
       'Contraceptive method used'],
      dtype='object')

In [14]:
contraceptive_values = dataset_contraceptive.iloc[:,0:9].values
print("\nContraceptive valores dos atributos:\n")
print(contraceptive_values)

print("\nContraceptive shape:")
print(contraceptive_values.shape)


Contraceptive valores dos atributos:

[[24  2  3 ...  2  3  0]
 [45  1  3 ...  3  4  0]
 [43  2  3 ...  3  4  0]
 ...
 [39  3  3 ...  1  4  0]
 [33  3  3 ...  2  2  0]
 [17  3  3 ...  2  4  0]]

Contraceptive shape:
(1473, 9)


In [15]:
contraceptive_classes = dataset_contraceptive.iloc[:,9].values
print("\nContraceptive classes:\n")
print(contraceptive_classes)
print("\nContraceptive classes shape:")
print(contraceptive_classes.shape)


Contraceptive classes:

[1 1 1 ... 3 3 3]

Contraceptive classes shape:
(1473,)


In [16]:
kfold_treinamento = model_selection.StratifiedKFold(n_splits=5, shuffle=True, random_state=None)
kfold_ajuste_parametros = model_selection.StratifiedKFold(n_splits=3, shuffle=True, random_state=None)

In [17]:
arvore_decisao = DecisionTreeClassifier()
print("====== Iniciando busca pelos melhores parâmetros do algoritmo Arvore de decisao no dataset Transfusion ....\n")
param_dist = {'max_depth':list(np.arange(1,10)), 'min_samples_split':list(np.arange(1,10)) ,'criterion':['entropy'], 'splitter':['best','random']}
grid_search = GridSearchCV(arvore_decisao, param_grid=param_dist, cv=kfold_ajuste_parametros, scoring='accuracy', refit=False)
grid_search.fit(contraceptive_values, contraceptive_classes)
decisionTreeBestParams = grid_search.best_params_
print("Decision Tree: %s \n\n" % decisionTreeBestParams)

====== Iniciando busca pelos melhores parâmetros do algoritmo Arvore de decisao no dataset Transfusion ....

Decision Tree: {'criterion': 'entropy', 'max_depth': 5, 'splitter': 'best'} 




In [18]:
knn_vizinhos_proximos = KNeighborsClassifier()
print("====== Iniciando busca pelos melhores parâmetros do algoritmo KNN no dataset Transfusion ....\n")
param_dist = {'n_neighbors':[3,5,7,9], 'metric':['euclidean', 'manhattan'], 'weights':['uniform', 'distance']} #Parâmetros testados
grid_search = GridSearchCV(knn_vizinhos_proximos, param_grid=param_dist, cv=kfold_ajuste_parametros, scoring='accuracy', refit=False)
grid_search.fit(contraceptive_values, contraceptive_classes)
knnBestParams = grid_search.best_params_
print("KNN: %s \n\n" % knnBestParams)

====== Iniciando busca pelos melhores parâmetros do algoritmo KNN no dataset Transfusion ....

KNN: {'metric': 'euclidean', 'n_neighbors': 8, 'weights': 'uniform'} 




In [19]:
regressao_logistica = LogisticRegression()
print("====== Iniciando busca pelos melhores parâmetros do algoritmo Regressao logistica no dataset Transfusion ....\n")
param_dist = {'penalty':['l2','l1'], 'max_iter':[200,300,400,500],'solver':['liblinear','sag','saga']} #Parâmetros testados
grid_search = GridSearchCV(regressao_logistica, param_grid=param_dist, cv=kfold_ajuste_parametros, scoring='accuracy', refit=False)
grid_search.fit(contraceptive_values, contraceptive_classes)
regressao_logistica_param = grid_search.best_params_
print("Regressão logistica: %s \n\n" % regressao_logistica_param)


====== Iniciando busca pelos melhores parâmetros do algoritmo Regressao logistica no dataset Transfusion ....

Regressão logistica: {'max_iter': 500, 'penalty': 'l2', 'solver': 'saga', 'tol': 0.01} 




/home/anapedroso/Documentos/IA-desempenho-algoritmos-classificacao/env/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/anapedroso/Documentos/IA-desempenho-algoritmos-classificacao/env/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alterna

In [20]:
rede_neural = MLPClassifier()
print("====== Iniciando busca pelos melhores parâmetros do algoritmo Redes neurais no dataset Transfusion ....\n")
param_dist = {'hidden_layer_sizes':list(np.arange(10,20)),'activation':['logistic','identity','tanh'], 'max_iter':[100,200,300,400],'alpha':[0.0001,0.001, 0.01, 0.1], 'solver':['sgd','adam']}
grid_search = GridSearchCV(rede_neural, param_grid=param_dist, cv=kfold_ajuste_parametros, scoring='accuracy', refit=False)
grid_search.fit(contraceptive_values, contraceptive_classes)
redes_neurais_param = grid_search.best_params_
print("Redes neurais: %s \n\n" % redes_neurais_param)

====== Iniciando busca pelos melhores parâmetros do algoritmo Redes neurais no dataset Transfusion ....

Redes neurais: {'activation': 'logistic', 'alpha': 0.01, 'hidden_layer_sizes': 9, 'learning_rate': 'invscaling', 'learning_rate_init': 0.01, 'max_iter': 300, 'solver': 'adam'} 




/home/anapedroso/Documentos/IA-desempenho-algoritmos-classificacao/env/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/anapedroso/Documentos/IA-desempenho-algoritmos-classificacao/env/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/anapedroso/Documentos/IA-desempenho-algoritmos-classificacao/env/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/anapedroso/Documentos/IA-desempenho-algoritmos-classificacao/env/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_pe

In [21]:
predicted_classes = dict()
predicted_classes['Arvore_decisao'] = np.zeros(contraceptive_classes.shape)
predicted_classes['KNN_Vizinhos_proximos'] = np.zeros(contraceptive_classes.shape)
predicted_classes['Naive_bayes_gaussian'] = np.zeros(contraceptive_classes.shape)
predicted_classes['Regressao_logistica'] = np.zeros(contraceptive_classes.shape)
predicted_classes['Rede_neural'] = np.zeros(contraceptive_classes.shape)

arvore_decisao_best_param = DecisionTreeClassifier(**decisionTreeBestParams)
knn_vizinhos_proximos_best_param = KNeighborsClassifier(**knnBestParams)
naive_bayes_gaussian = GaussianNB()
regressao_logistica_best_param = LogisticRegression(**regressao_logistica_param)
rede_neural_best_param = MLPClassifier(**redes_neurais_param)

In [22]:
for train, test in kfold_treinamento.split(contraceptive_values, contraceptive_classes):
    data_train, target_train = contraceptive_values[train], contraceptive_classes[train]
    data_test, target_test = contraceptive_values[test], contraceptive_classes[test]

    arvore_decisao_best_param = arvore_decisao_best_param.fit(data_train, target_train)
    arvore_decisao_predicted = arvore_decisao_best_param.predict(data_test)
    predicted_classes['Arvore_decisao'][test] = arvore_decisao_predicted

    vizinhos_proximos = knn_vizinhos_proximos_best_param.fit(data_train, target_train)
    vizinhos_proximos_predicted = vizinhos_proximos.predict(data_test)
    predicted_classes['KNN_Vizinhos_proximos'][test] = vizinhos_proximos_predicted

    naive_bayes_gaussian = naive_bayes_gaussian.fit(data_train, target_train)
    naive_bayes_gaussian_predicted = naive_bayes_gaussian.predict(data_test)
    predicted_classes['Naive_bayes_gaussian'][test] = naive_bayes_gaussian_predicted

    regressao_logistica = regressao_logistica_best_param.fit(data_train, target_train)
    regressao_logistica_predicted = regressao_logistica.predict(data_test)
    predicted_classes['Regressao_logistica'][test] = regressao_logistica_predicted

    rede_neural = rede_neural_best_param.fit(data_train, target_train)
    rede_neural_predicted = rede_neural.predict(data_test)
    predicted_classes['Rede_neural'][test] = rede_neural_predicted



In [23]:
for classificador in predicted_classes.keys():
    print("================================================================================================")
    print("Resultados do classificador %s\n%s\n"
          %(classificador, metrics.classification_report(contraceptive_classes, predicted_classes[classificador])))
    print("Matriz de confusão: \n%s\n\n\n" % metrics.confusion_matrix(contraceptive_classes, predicted_classes[classificador]))

Resultados do classificador Arvore_decisao
              precision    recall  f1-score   support

           1       0.64      0.63      0.64       629
           2       0.50      0.40      0.44       333
           3       0.50      0.58      0.54       511

    accuracy                           0.56      1473
   macro avg       0.55      0.54      0.54      1473
weighted avg       0.56      0.56      0.56      1473


Matriz de confusão: 
[[396  51 182]
 [ 87 132 114]
 [132  83 296]]



Resultados do classificador KNN_Vizinhos_proximos
              precision    recall  f1-score   support

           1       0.60      0.66      0.63       629
           2       0.44      0.40      0.42       333
           3       0.50      0.47      0.48       511

    accuracy                           0.54      1473
   macro avg       0.52      0.51      0.51      1473
weighted avg       0.53      0.54      0.53      1473


Matriz de confusão: 
[[418  71 140]
 [102 134  97]
 [175  97 239]]



Res