In [1]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn import model_selection
from sklearn import metrics
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier


dataset_contraceptive = pd.read_table('contraceptive.data', sep=',')
print("\nDataset Contraceptive:")
dataset_contraceptive


Dataset Contraceptive:


/home/larissa/.local/lib/python3.5/site-packages/ipykernel_launcher.py:13: FutureWarning: read_table is deprecated, use read_csv instead.
  del sys.path[0]


Wifes age  Wifes education  Husbands education  \
0            24                2                   3   
1            45                1                   3   
2            43                2                   3   
3            42                3                   2   
4            36                3                   3   
5            19                4                   4   
6            38                2                   3   
7            21                3                   3   
8            27                2                   3   
9            45                1                   1   
10           38                1                   3   
11           42                1                   4   
12           44                4                   4   
13           42                2                   4   
14           38                3                   4   
15           26                2                   4   
16           48                1                   1   
17           39                2                   2   
18           37                2                   2   
19           39                2                   1   
20           26                3                   4   
21           24                3                   4   
22           46                4                   4   
23           39                4                   4   
24           48                4                   4   
25           40                2                   4   
26           38                4                   4   
27           29                4                   4   
28           24                4                   4   
29           43                1                   2   
...         ...              ...                 ...   
1443         21                2                   2   
1444         22                4                   4   
1445         36                4                   4   
1446         45                2                   3   
1447         34                4                   4   
1448         35                2                   3   
1449         19                4                   4   
1450         27                4                   4   
1451         37                2                   4   
1452         26                3                   2   
1453         28                1                   3   
1454         31                3                   4   
1455         32                2                   2   
1456         40                2                   2   
1457         27                3                   3   
1458         27                2                   2   
1459         37                4                   4   
1460         22                4                   3   
1461         27                4                   4   
1462         21                4                   4   
1463         30                1                   3   
1464         23                2                   2   
1465         25                2                   4   
1466         42                2                   4   
1467         29                4                   4   
1468         33                4                   4   
1469         33                4                   4   
1470         39                3                   3   
1471         33                3                   3   
1472         17                3                   3   

      Number of children ever born  Wifes religion   Wifes now working  \
0                                3               1                   1   
1                               10               1                   1   
2                                7               1                   1   
3                                9               1                   1   
4                                8               1                   1   
5                                0               1                   1   
6              

In [2]:
dataset_contraceptive.columns


Index(['Wifes age', 'Wifes education', 'Husbands education',
       'Number of children ever born', 'Wifes religion', ' Wifes now working',
       'Husbands occupation', 'Standard-of-living index', 'Media exposure',
       'Contraceptive method used'],
      dtype='object')

In [3]:
contraceptive_values = dataset_contraceptive.iloc[:,0:9].values
print("\nContraceptive valores dos atributos:\n")
print(contraceptive_values)

print("\nContraceptive shape:")
print(contraceptive_values.shape)


Contraceptive valores dos atributos:

[[24  2  3 ...  2  3  0]
 [45  1  3 ...  3  4  0]
 [43  2  3 ...  3  4  0]
 ...
 [39  3  3 ...  1  4  0]
 [33  3  3 ...  2  2  0]
 [17  3  3 ...  2  4  0]]

Contraceptive shape:
(1473, 9)


In [4]:
contraceptive_classes = dataset_contraceptive.iloc[:,9].values
print("\nContraceptive classes:\n")
print(contraceptive_classes)
print("\nContraceptive classes shape:")
print(contraceptive_classes.shape)


Contraceptive classes:

[1 1 1 ... 3 3 3]

Contraceptive classes shape:
(1473,)


In [5]:
kfold_treinamento = model_selection.StratifiedKFold(n_splits=5, shuffle=True, random_state=None)
kfold_ajuste_parametros = model_selection.StratifiedKFold(n_splits=3, shuffle=True, random_state=None)

In [6]:
arvore_decisao = DecisionTreeClassifier()
print("====== Iniciando busca pelos melhores parâmetros do algoritmo Arvore de decisao no dataset Transfusion ....\n")
param_dist = {'max_depth':list(np.arange(1,10)), 'min_samples_split':list(np.arange(1,10)) ,'criterion':['entropy'], 'splitter':['best','random']}
grid_search = GridSearchCV(arvore_decisao, param_grid=param_dist, cv=kfold_ajuste_parametros, scoring='accuracy', refit=False)
grid_search.fit(contraceptive_values, contraceptive_classes)
decisionTreeBestParams = grid_search.best_params_
print("Decision Tree: %s \n\n" % decisionTreeBestParams)

====== Iniciando busca pelos melhores parâmetros do algoritmo Arvore de decisao no dataset Transfusion ....

Decision Tree: {'criterion': 'entropy', 'min_samples_split': 8, 'splitter': 'best', 'max_depth': 5} 




/home/larissa/.local/lib/python3.5/site-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: min_samples_split must be an integer greater than 1 or a float in (0.0, 1.0]; got the integer 1

  FitFailedWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: min_samples_split must be an integer greater than 1 or a float in (0.0, 1.0]; got the integer 1

  FitFailedWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: min_samples_split must be an integer greater than 1 or a floa

In [7]:
knn_vizinhos_proximos = KNeighborsClassifier()
print("====== Iniciando busca pelos melhores parâmetros do algoritmo KNN no dataset Transfusion ....\n")
param_dist = {'n_neighbors':[3,5,7,9], 'metric':['euclidean', 'manhattan'], 'weights':['uniform', 'distance']} #Parâmetros testados
grid_search = GridSearchCV(knn_vizinhos_proximos, param_grid=param_dist, cv=kfold_ajuste_parametros, scoring='accuracy', refit=False)
grid_search.fit(contraceptive_values, contraceptive_classes)
knnBestParams = grid_search.best_params_
print("KNN: %s \n\n" % knnBestParams)

====== Iniciando busca pelos melhores parâmetros do algoritmo KNN no dataset Transfusion ....

KNN: {'n_neighbors': 9, 'metric': 'euclidean', 'weights': 'uniform'} 




In [8]:
regressao_logistica = LogisticRegression()
print("====== Iniciando busca pelos melhores parâmetros do algoritmo Regressao logistica no dataset Transfusion ....\n")
param_dist = {'penalty':['l2','l1'], 'max_iter':[200,300,400,500],'solver':['liblinear','sag','saga']} #Parâmetros testados
grid_search = GridSearchCV(regressao_logistica, param_grid=param_dist, cv=kfold_ajuste_parametros, scoring='accuracy', refit=False)
grid_search.fit(contraceptive_values, contraceptive_classes)
regressao_logistica_param = grid_search.best_params_
print("Regressão logistica: %s \n\n" % regressao_logistica_param)


====== Iniciando busca pelos melhores parâmetros do algoritmo Regressao logistica no dataset Transfusion ....

Regressão logistica: {'solver': 'sag', 'max_iter': 400, 'penalty': 'l2'} 




/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reac

In [9]:
rede_neural = MLPClassifier()
print("====== Iniciando busca pelos melhores parâmetros do algoritmo Redes neurais no dataset Transfusion ....\n")
param_dist = {'hidden_layer_sizes':list(np.arange(10,20)),'activation':['logistic','identity','tanh'], 'max_iter':[100,200,300,400],'alpha':[0.0001,0.001, 0.01, 0.1], 'solver':['sgd','adam']}
grid_search = GridSearchCV(rede_neural, param_grid=param_dist, cv=kfold_ajuste_parametros, scoring='accuracy', refit=False)
grid_search.fit(contraceptive_values, contraceptive_classes)
redes_neurais_param = grid_search.best_params_
print("Redes neurais: %s \n\n" % redes_neurais_param)

====== Iniciando busca pelos melhores parâmetros do algoritmo Redes neurais no dataset Transfusion ....

Redes neurais: {'hidden_layer_sizes': 17, 'solver': 'adam', 'max_iter': 300, 'alpha': 0.0001, 'activation': 'logistic'} 




/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.

In [10]:
predicted_classes = dict()
predicted_classes['Arvore_decisao'] = np.zeros(contraceptive_classes.shape)
predicted_classes['KNN_Vizinhos_proximos'] = np.zeros(contraceptive_classes.shape)
predicted_classes['Naive_bayes_gaussian'] = np.zeros(contraceptive_classes.shape)
predicted_classes['Regressao_logistica'] = np.zeros(contraceptive_classes.shape)
predicted_classes['Rede_neural'] = np.zeros(contraceptive_classes.shape)

arvore_decisao_best_param = DecisionTreeClassifier(**decisionTreeBestParams)
knn_vizinhos_proximos_best_param = KNeighborsClassifier(**knnBestParams)
naive_bayes_gaussian = GaussianNB()
regressao_logistica_best_param = LogisticRegression(**regressao_logistica_param)
rede_neural_best_param = MLPClassifier(**redes_neurais_param)

In [11]:
for train, test in kfold_treinamento.split(contraceptive_values, contraceptive_classes):
    data_train, target_train = contraceptive_values[train], contraceptive_classes[train]
    data_test, target_test = contraceptive_values[test], contraceptive_classes[test]

    arvore_decisao_best_param = arvore_decisao_best_param.fit(data_train, target_train)
    arvore_decisao_predicted = arvore_decisao_best_param.predict(data_test)
    predicted_classes['Arvore_decisao'][test] = arvore_decisao_predicted

    knn_vizinhos_proximos_best_param = knn_vizinhos_proximos_best_param.fit(data_train, target_train)
    vizinhos_proximos_predicted = knn_vizinhos_proximos_best_param.predict(data_test)
    predicted_classes['KNN_Vizinhos_proximos'][test] = vizinhos_proximos_predicted

    naive_bayes_gaussian = naive_bayes_gaussian.fit(data_train, target_train)
    naive_bayes_gaussian_predicted = naive_bayes_gaussian.predict(data_test)
    predicted_classes['Naive_bayes_gaussian'][test] = naive_bayes_gaussian_predicted

    regressao_logistica_best_param = regressao_logistica_best_param.fit(data_train, target_train)
    regressao_logistica_predicted = regressao_logistica_best_param.predict(data_test)
    predicted_classes['Regressao_logistica'][test] = regressao_logistica_predicted

    rede_neural = rede_neural_best_param.fit(data_train, target_train)
    rede_neural_predicted = rede_neural_best_param.predict(data_test)
    predicted_classes['Rede_neural'][test] = rede_neural_predicted



/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-pa

In [12]:
for classificador in predicted_classes.keys():
    print("================================================================================================")
    print("Resultados do classificador %s\n%s\n"
          %(classificador, metrics.classification_report(contraceptive_classes, predicted_classes[classificador])))
    print("Matriz de confusão: \n%s\n\n\n" % metrics.confusion_matrix(contraceptive_classes, predicted_classes[classificador]))

Resultados do classificador KNN_Vizinhos_proximos
              precision    recall  f1-score   support

           1       0.59      0.65      0.62       629
           2       0.44      0.39      0.42       333
           3       0.49      0.47      0.48       511

    accuracy                           0.53      1473
   macro avg       0.51      0.50      0.50      1473
weighted avg       0.52      0.53      0.52      1473


Matriz de confusão: 
[[407  73 149]
 [105 131  97]
 [180  93 238]]



Resultados do classificador Rede_neural
              precision    recall  f1-score   support

           1       0.64      0.66      0.65       629
           2       0.48      0.40      0.44       333
           3       0.50      0.53      0.51       511

    accuracy                           0.56      1473
   macro avg       0.54      0.53      0.53      1473
weighted avg       0.55      0.56      0.55      1473


Matriz de confusão: 
[[417  53 159]
 [ 88 134 111]
 [146  95 270]]



Result