In [25]:
from sklearn import tree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn import model_selection
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn import metrics
import pandas as pd
import numpy as np

monkeys = pd.read_table('monkeys.data', sep=',')
print("\nDataset Monkeys:")
monkeys


Dataset Monkeys:


Class  A1  A2  A3  A4  A5  A6
0         1   1   1   1   1   1   1
1         1   1   1   1   1   1   2
2         1   1   1   1   1   2   1
3         1   1   1   1   1   2   2
4         1   1   1   1   1   3   1
...     ...  ..  ..  ..  ..  ..  ..
1707      0   3   3   2   2   2   2
1708      0   3   3   2   2   3   2
1709      0   3   3   2   3   1   1
1710      0   3   3   2   3   3   2
1711      0   3   3   2   3   4   2

[1712 rows x 7 columns]

In [26]:
monkeys.columns

Index(['Class', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6'], dtype='object')

In [27]:
monkeysNormalized = monkeys.values.copy()
normalizador =  StandardScaler()

# monkeysNormalized = normalizador.fit_transform(monkeys)
# monkeys['Class'] = monkeysNormalized[:,0]
# monkeys['A1'] = monkeysNormalized[:,1]
# monkeys['A2'] = monkeysNormalized[:,2]
# monkeys['A3'] = monkeysNormalized[:,3]
# monkeys['A4'] = monkeysNormalized[:,4]
# monkeys['A5'] = monkeysNormalized[:,5]
# monkeys['A6'] = monkeysNormalized[:,6]


print("\nDataset Monkeys Normalized:")
monkeys



Dataset Monkeys Normalized:


Class  A1  A2  A3  A4  A5  A6
0         1   1   1   1   1   1   1
1         1   1   1   1   1   1   2
2         1   1   1   1   1   2   1
3         1   1   1   1   1   2   2
4         1   1   1   1   1   3   1
...     ...  ..  ..  ..  ..  ..  ..
1707      0   3   3   2   2   2   2
1708      0   3   3   2   2   3   2
1709      0   3   3   2   3   1   1
1710      0   3   3   2   3   3   2
1711      0   3   3   2   3   4   2

[1712 rows x 7 columns]

In [28]:
monkeysValues = monkeys.iloc[:,0:6].values
print("\n Monkeys features:\n")
print(monkeysValues)



 Monkeys features:

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 2]
 ...
 [0 3 3 2 3 1]
 [0 3 3 2 3 3]
 [0 3 3 2 3 4]]


In [29]:
monkeysClasses = monkeys.iloc[:,5].values
print("\nMonkeys classes:\n")
print(monkeysClasses)
print("\nMonkeys classes shape:")
print(monkeysClasses.shape)





Monkeys classes:

[1 1 2 ... 1 3 4]

Monkeys classes shape:
(1712,)


In [30]:
kf = model_selection.StratifiedKFold(n_splits = 5)
arvore_decisao = tree.DecisionTreeClassifier(criterion='entropy', splitter='best', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, random_state=None, max_leaf_nodes=None, min_impurity_decrease=0.0, min_impurity_split=None, class_weight=None, presort='deprecated', ccp_alpha=0.0)
vizinhos_proximos = KNeighborsClassifier(n_neighbors=3, weights = 'distance')
naive_bayes_gaussian = GaussianNB()
regressao_logistica = LogisticRegression(penalty='l2', dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='saga', max_iter=100, multi_class='auto', verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)
rede_neural = MLPClassifier(hidden_layer_sizes=(5,), activation="logistic", max_iter= 300, alpha=0.001, solver="sgd", tol=1e-4, verbose=True, learning_rate_init=.01)

In [31]:
predicted_classes = dict()
predicted_classes['arvore_decisao'] = np.zeros(monkeysClasses.shape)
predicted_classes['vizinhos_proximos'] = np.zeros(monkeysClasses.shape)
predicted_classes['naive_bayes_gaussian'] = np.zeros(monkeysClasses.shape)
predicted_classes['regressao_logistica'] = np.zeros(monkeysClasses.shape)
predicted_classes['rede_neural'] = np.zeros(monkeysClasses.shape)

In [32]:
for train, test in kf.split(monkeysValues, monkeysClasses):
    data_train, target_train = monkeysValues[train], monkeysClasses[train]
    data_test, target_test = monkeysValues[test], monkeysClasses[test]

    arvore_decisao = arvore_decisao.fit(data_train, target_train)
    arvore_decisao_predicted = arvore_decisao.predict(data_test)
    predicted_classes['arvore_decisao'][test] = arvore_decisao_predicted

    vizinhos_proximos = vizinhos_proximos.fit(data_train, target_train)
    vizinhos_proximos_predicted = vizinhos_proximos.predict(data_test)
    predicted_classes['vizinhos_proximos'][test] = vizinhos_proximos_predicted

    naive_bayes_gaussian = naive_bayes_gaussian.fit(data_train, target_train)
    naive_bayes_gaussian_predicted = naive_bayes_gaussian.predict(data_test)
    predicted_classes['naive_bayes_gaussian'][test] = naive_bayes_gaussian_predicted

    regressao_logistica = regressao_logistica.fit(data_train, target_train)
    regressao_logistica_predicted = regressao_logistica.predict(data_test)
    predicted_classes['regressao_logistica'][test] = regressao_logistica_predicted

    rede_neural = rede_neural.fit(data_train, target_train)
    rede_neural_predicted = rede_neural.predict(data_test)
    predicted_classes['rede_neural'][test] = rede_neural_predicted

c:\users\david\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\linear_model\_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
c:\users\david\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\users\david\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\linear_model\_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
c:\users\david\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't conver

Iteration 1, loss = 1.45235193
Iteration 2, loss = 1.41806187
Iteration 3, loss = 1.38795226
Iteration 4, loss = 1.37197899
Iteration 5, loss = 1.36385913
Iteration 6, loss = 1.35780584
Iteration 7, loss = 1.35080107
Iteration 8, loss = 1.34310703
Iteration 9, loss = 1.33448478
Iteration 10, loss = 1.32517358
Iteration 11, loss = 1.31522534
Iteration 12, loss = 1.30416860
Iteration 13, loss = 1.29247092
Iteration 14, loss = 1.28008928
Iteration 15, loss = 1.26702916
Iteration 16, loss = 1.25316236
Iteration 17, loss = 1.23891557
Iteration 18, loss = 1.22440042
Iteration 19, loss = 1.20953563
Iteration 20, loss = 1.19430861
Iteration 21, loss = 1.17869224
Iteration 22, loss = 1.16300388
Iteration 23, loss = 1.14707334
Iteration 24, loss = 1.13128784
Iteration 25, loss = 1.11539426
Iteration 26, loss = 1.09982747
Iteration 27, loss = 1.08437817
Iteration 28, loss = 1.06933103
Iteration 29, loss = 1.05448442
Iteration 30, loss = 1.04003180
Iteration 31, loss = 1.02603224
Iteration 32, los

In [33]:
for classificador in predicted_classes.keys():
    print("================================================================================================")
    print("Resultados do classificador %s\n%s\n"
          %(classificador, metrics.classification_report(monkeysClasses, predicted_classes[classificador])))
    print("Matriz de confusão: \n%s\n\n\n" % metrics.confusion_matrix(monkeysClasses, predicted_classes[classificador]))




Resultados do classificador arvore_decisao
              precision    recall  f1-score   support

           1       1.00      1.00      1.00       428
           2       1.00      1.00      1.00       426
           3       1.00      1.00      1.00       432
           4       1.00      1.00      1.00       426

    accuracy                           1.00      1712
   macro avg       1.00      1.00      1.00      1712
weighted avg       1.00      1.00      1.00      1712


Matriz de confusão: 
[[428   0   0   0]
 [  0 426   0   0]
 [  0   0 432   0]
 [  0   0   0 426]]



Resultados do classificador vizinhos_proximos
              precision    recall  f1-score   support

           1       0.98      0.99      0.98       428
           2       0.98      0.98      0.98       426
           3       0.99      0.99      0.99       432
           4       1.00      0.99      0.99       426

    accuracy                           0.99      1712
   macro avg       0.99      0.99      0.99     