In [1]:
from sklearn import tree
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn import model_selection
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn import metrics
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier

monkeys = pd.read_table('monkeys.data', sep=',')
print("\nDataset Monkeys:")
monkeys


Dataset Monkeys:


/home/larissa/.local/lib/python3.5/site-packages/ipykernel_launcher.py:15: FutureWarning: read_table is deprecated, use read_csv instead.
  from ipykernel import kernelapp as app


Class  A1  A2  A3  A4  A5  A6
0         1   1   1   1   1   1   1
1         1   1   1   1   1   1   2
2         1   1   1   1   1   2   1
3         1   1   1   1   1   2   2
4         1   1   1   1   1   3   1
5         1   1   1   1   1   3   2
6         1   1   1   1   1   4   1
7         1   1   1   1   1   4   2
8         1   1   1   1   2   1   1
9         1   1   1   1   2   1   2
10        1   1   1   1   2   2   1
11        1   1   1   1   2   2   2
12        1   1   1   1   2   3   1
13        1   1   1   1   2   3   2
14        1   1   1   1   2   4   1
15        1   1   1   1   2   4   2
16        1   1   1   1   3   1   1
17        1   1   1   1   3   1   2
18        1   1   1   1   3   2   1
19        1   1   1   1   3   2   2
20        1   1   1   1   3   3   1
21        1   1   1   1   3   3   2
22        1   1   1   1   3   4   1
23        1   1   1   1   3   4   2
24        1   1   1   2   1   1   1
25        1   1   1   2   1   1   2
26        1   1   1   2   1   2   1
27        1   1   1   2   1   2   2
28        1   1   1   2   1   3   1
29        1   1   1   2   1   3   2
...     ...  ..  ..  ..  ..  ..  ..
1682      1   3   1   1   3   1   2
1683      0   3   1   1   3   4   2
1684      1   3   1   2   1   2   1
1685      1   3   1   2   2   3   2
1686      0   3   1   2   2   4   2
1687      1   3   1   2   3   1   1
1688      1   3   2   1   1   2   2
1689      0   3   2   1   1   4   1
1690      1   3   2   1   2   3   1
1691      1   3   2   1   3   1   2
1692      1   3   2   2   1   2   2
1693      1   3   2   2   1   3   2
1694      1   3   2   2   2   1   2
1695      1   3   2   2   3   1   1
1696      1   3   2   2   3   3   2
1697      0   3   2   2   3   4   1
1698      1   3   3   1   1   3   2
1699      1   3   3   1   1   4   1
1700      0   3   3   1   2   4   2
1701      0   3   3   1   3   1   1
1702      0   3   3   1   3   2   1
1703      0   3   3   1   3   2   2
1704      0   3   3   1   3   4   1
1705      0   3   3   2   1   1   1
1706      0   3   3   2   1   1   2
1707      0   3   3   2   2   2   2
1708      0   3   3   2   2   3   2
1709      0   3   3   2   3   1   1
1710      0   3   3   2   3   3   2
1711      0   3   3   2   3   4   2

[1712 rows x 7 columns]

In [2]:
monkeys.columns

Index(['Class', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6'], dtype='object')

In [3]:
monkeysNormalized = monkeys.values.copy()
normalizador =  StandardScaler()

# monkeysNormalized = normalizador.fit_transform(monkeys)
# monkeys['Class'] = monkeysNormalized[:,0]
# monkeys['A1'] = monkeysNormalized[:,1]
# monkeys['A2'] = monkeysNormalized[:,2]
# monkeys['A3'] = monkeysNormalized[:,3]
# monkeys['A4'] = monkeysNormalized[:,4]
# monkeys['A5'] = monkeysNormalized[:,5]
# monkeys['A6'] = monkeysNormalized[:,6]


print("\nDataset Monkeys Normalized:")
monkeys



Dataset Monkeys Normalized:


Class  A1  A2  A3  A4  A5  A6
0         1   1   1   1   1   1   1
1         1   1   1   1   1   1   2
2         1   1   1   1   1   2   1
3         1   1   1   1   1   2   2
4         1   1   1   1   1   3   1
5         1   1   1   1   1   3   2
6         1   1   1   1   1   4   1
7         1   1   1   1   1   4   2
8         1   1   1   1   2   1   1
9         1   1   1   1   2   1   2
10        1   1   1   1   2   2   1
11        1   1   1   1   2   2   2
12        1   1   1   1   2   3   1
13        1   1   1   1   2   3   2
14        1   1   1   1   2   4   1
15        1   1   1   1   2   4   2
16        1   1   1   1   3   1   1
17        1   1   1   1   3   1   2
18        1   1   1   1   3   2   1
19        1   1   1   1   3   2   2
20        1   1   1   1   3   3   1
21        1   1   1   1   3   3   2
22        1   1   1   1   3   4   1
23        1   1   1   1   3   4   2
24        1   1   1   2   1   1   1
25        1   1   1   2   1   1   2
26        1   1   1   2   1   2   1
27        1   1   1   2   1   2   2
28        1   1   1   2   1   3   1
29        1   1   1   2   1   3   2
...     ...  ..  ..  ..  ..  ..  ..
1682      1   3   1   1   3   1   2
1683      0   3   1   1   3   4   2
1684      1   3   1   2   1   2   1
1685      1   3   1   2   2   3   2
1686      0   3   1   2   2   4   2
1687      1   3   1   2   3   1   1
1688      1   3   2   1   1   2   2
1689      0   3   2   1   1   4   1
1690      1   3   2   1   2   3   1
1691      1   3   2   1   3   1   2
1692      1   3   2   2   1   2   2
1693      1   3   2   2   1   3   2
1694      1   3   2   2   2   1   2
1695      1   3   2   2   3   1   1
1696      1   3   2   2   3   3   2
1697      0   3   2   2   3   4   1
1698      1   3   3   1   1   3   2
1699      1   3   3   1   1   4   1
1700      0   3   3   1   2   4   2
1701      0   3   3   1   3   1   1
1702      0   3   3   1   3   2   1
1703      0   3   3   1   3   2   2
1704      0   3   3   1   3   4   1
1705      0   3   3   2   1   1   1
1706      0   3   3   2   1   1   2
1707      0   3   3   2   2   2   2
1708      0   3   3   2   2   3   2
1709      0   3   3   2   3   1   1
1710      0   3   3   2   3   3   2
1711      0   3   3   2   3   4   2

[1712 rows x 7 columns]

In [4]:
monkeysValues = monkeys.iloc[:,0:6].values
print("\n Monkeys features:\n")
print(monkeysValues)



 Monkeys features:

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 2]
 ...
 [0 3 3 2 3 1]
 [0 3 3 2 3 3]
 [0 3 3 2 3 4]]


In [5]:
monkeysClasses = monkeys.iloc[:,5].values
print("\nMonkeys classes:\n")
print(monkeysClasses)
print("\nMonkeys classes shape:")
print(monkeysClasses.shape)


Monkeys classes:

[1 1 2 ... 1 3 4]

Monkeys classes shape:
(1712,)


In [6]:
kfold_treinamento = model_selection.StratifiedKFold(n_splits=5, shuffle=True, random_state=None)
kfold_ajuste_parametros = model_selection.StratifiedKFold(n_splits=3, shuffle=True, random_state=None)

In [7]:
arvore_decisao = DecisionTreeClassifier()
print("====== Iniciando busca pelos melhores parâmetros do algoritmo Arvore de decisao no dataset Teaching ....\n")

param_dist = {'max_depth':[3,4,5,6,7,8,9,10], 'criterion': ['entropy'], 'splitter':['best','random']}
grid_search = GridSearchCV(arvore_decisao, param_grid=param_dist, cv=kfold_ajuste_parametros, scoring='accuracy', refit=False)
grid_search.fit(monkeysValues, monkeysClasses)
decisionTreeBestParams = grid_search.best_params_
print("Decision Tree: %s \n\n" % decisionTreeBestParams)

====== Iniciando busca pelos melhores parâmetros do algoritmo Arvore de decisao no dataset Teaching ....

Decision Tree: {'max_depth': 3, 'splitter': 'best', 'criterion': 'entropy'} 




In [8]:
knn_vizinhos_proximos = KNeighborsClassifier()
print("====== Iniciando busca pelos melhores parâmetros do algoritmo KNN no dataset Teaching ....\n")

param_dist = {'n_neighbors': list(np.arange(1, 10)), 'metric':['euclidean'], 'weights':['uniform', 'distance']} #Parâmetros testados
grid_search = GridSearchCV(knn_vizinhos_proximos, param_grid=param_dist, cv=kfold_ajuste_parametros, scoring='accuracy', refit=False)
grid_search.fit(monkeysValues, monkeysClasses)
knnBestParams = grid_search.best_params_
print("KNN: %s \n\n" % knnBestParams)

====== Iniciando busca pelos melhores parâmetros do algoritmo KNN no dataset Teaching ....

KNN: {'metric': 'euclidean', 'n_neighbors': 9, 'weights': 'distance'} 




In [9]:
regressao_logistica = LogisticRegression()
print("====== Iniciando busca pelos melhores parâmetros do algoritmo Regressao logistica no dataset Teaching ....\n")

param_dist = {'penalty':['l2','none'],'tol':[0.0001,0.001, 0.01, 0.1, 1], 'max_iter':[300,400,500,600],'solver':['lbfgs','saga']} #Parâmetros testados

grid_search = GridSearchCV(regressao_logistica, param_grid=param_dist, cv=kfold_ajuste_parametros, scoring='accuracy', refit=False)
grid_search.fit(monkeysValues, monkeysClasses)
regressao_logistica_param = grid_search.best_params_
print("Regressão logistica: %s \n\n" % regressao_logistica_param)

====== Iniciando busca pelos melhores parâmetros do algoritmo Regressao logistica no dataset Teaching ....

Regressão logistica: {'solver': 'lbfgs', 'max_iter': 300, 'tol': 0.0001, 'penalty': 'l2'} 




/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reac

In [ ]:
rede_neural = MLPClassifier()
print("====== Iniciando busca pelos melhores parâmetros do algoritmo Redes neurais no dataset Teaching ....\n")

param_dist = {'hidden_layer_sizes':list(np.arange(5, 10)),'activation':['logistic'], 'max_iter':[300,400,500,600],'alpha':[0.0001,0.001, 0.01, 0.1], 'solver':['sgd','adam'], 'learning_rate':['constant','invscaling','adaptive'], 'learning_rate_init':[0.001, 0.01, 0.1]} #Parâmetros testados

grid_search = GridSearchCV(rede_neural, param_grid=param_dist, cv=kfold_ajuste_parametros, scoring='accuracy', refit=False)
grid_search.fit(monkeysValues, monkeysClasses)
redes_neurais_param = grid_search.best_params_
print("Redes neurais: %s \n\n" % redes_neurais_param)

====== Iniciando busca pelos melhores parâmetros do algoritmo Redes neurais no dataset Teaching ....



/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.

In [ ]:
kf = model_selection.StratifiedKFold(n_splits = 5)
arvore_decisao = tree.DecisionTreeClassifier(criterion='entropy', splitter='best', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, random_state=None, max_leaf_nodes=None, min_impurity_decrease=0.0, min_impurity_split=None, class_weight=None, presort='deprecated', ccp_alpha=0.0)
vizinhos_proximos = KNeighborsClassifier(n_neighbors=3, weights = 'distance')
naive_bayes_gaussian = GaussianNB()
regressao_logistica = LogisticRegression(penalty='l2', dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='saga', max_iter=100, multi_class='auto', verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)
rede_neural = MLPClassifier(hidden_layer_sizes=(5,), activation="logistic", max_iter= 300, alpha=0.001, solver="sgd", tol=1e-4, verbose=True, learning_rate_init=.01)

In [ ]:
predicted_classes = dict()
predicted_classes['arvore_decisao'] = np.zeros(monkeysClasses.shape)
predicted_classes['vizinhos_proximos'] = np.zeros(monkeysClasses.shape)
predicted_classes['naive_bayes_gaussian'] = np.zeros(monkeysClasses.shape)
predicted_classes['regressao_logistica'] = np.zeros(monkeysClasses.shape)
predicted_classes['rede_neural'] = np.zeros(monkeysClasses.shape)

arvore_decisao_best_param = DecisionTreeClassifier(**decisionTreeBestParams)
knn_vizinhos_proximos_best_param = KNeighborsClassifier(**knnBestParams)
naive_bayes_gaussian = GaussianNB()
regressao_logistica_best_param = LogisticRegression(**regressao_logistica_param)
rede_neural_best_param = MLPClassifier(**redes_neurais_param)

In [ ]:
for train, test in kf.split(monkeysValues, monkeysClasses):
    data_train, target_train = monkeysValues[train], monkeysClasses[train]
    data_test, target_test = monkeysValues[test], monkeysClasses[test]

    arvore_decisao = arvore_decisao.fit(data_train, target_train)
    arvore_decisao_predicted = arvore_decisao.predict(data_test)
    predicted_classes['arvore_decisao'][test] = arvore_decisao_predicted

    vizinhos_proximos = vizinhos_proximos.fit(data_train, target_train)
    vizinhos_proximos_predicted = vizinhos_proximos.predict(data_test)
    predicted_classes['vizinhos_proximos'][test] = vizinhos_proximos_predicted

    naive_bayes_gaussian = naive_bayes_gaussian.fit(data_train, target_train)
    naive_bayes_gaussian_predicted = naive_bayes_gaussian.predict(data_test)
    predicted_classes['naive_bayes_gaussian'][test] = naive_bayes_gaussian_predicted

    regressao_logistica = regressao_logistica.fit(data_train, target_train)
    regressao_logistica_predicted = regressao_logistica.predict(data_test)
    predicted_classes['regressao_logistica'][test] = regressao_logistica_predicted

    rede_neural = rede_neural.fit(data_train, target_train)
    rede_neural_predicted = rede_neural.predict(data_test)
    predicted_classes['rede_neural'][test] = rede_neural_predicted

In [ ]:
for classificador in predicted_classes.keys():
    print("================================================================================================")
    print("Resultados do classificador %s\n%s\n"
          %(classificador, metrics.classification_report(monkeysClasses, predicted_classes[classificador])))
    print("Matriz de confusão: \n%s\n\n\n" % metrics.confusion_matrix(monkeysClasses, predicted_classes[classificador]))


