In [1]:
from sklearn import tree, preprocessing
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn import model_selection
from sklearn import metrics
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier


dataset_teaching = pd.read_csv('teachingAssistantEvaluation.data', sep=',')
print("\nDataset teaching Assistant Evaluation:")
dataset_teaching


Dataset teaching Assistant Evaluation:


nativeEnglishSpeaker  courseInstructor  course  summerOrRegularSemester  \
0                       1                23       3                        1   
1                       2                15       3                        1   
2                       1                23       3                        2   
3                       1                 5       2                        2   
4                       2                 7      11                        2   
5                       2                23       3                        1   
6                       2                 9       5                        2   
7                       2                10       3                        2   
8                       1                22       3                        1   
9                       2                15       3                        1   
10                      2                10      22                        2   
11                      2                13       1                        2   
12                      2                18      21                        2   
13                      2                 6      17                        2   
14                      2                 6      17                        2   
15                      2                 6      17                        2   
16                      2                 7      11                        2   
17                      2                22       3                        2   
18                      2                13       3                        1   
19                      2                 7      25                        2   
20                      2                25       7                        2   
21                      2                25       7                        2   
22                      2                 2       9                        2   
23                      2                 1      15                        1   
24                      2                15      13                        2   
25                      2                 7      11                        2   
26                      2                 8       3                        2   
27                      2                14      15                        2   
28                      2                21       2                        2   
29                      2                22       3                        2   
..                    ...               ...     ...                      ...   
121                     2                13      14                        2   
122                     2                 9       6                        2   
123                     1                10       3                        2   
124                     2                14      15                        2   
125                     1                13       1                        2   
126                     1                 8       3                        2   
127                     2                20       2                        2   
128                     2                22       1                        2   
129                     2                18      12                        2   
130                     2                20      15                        2   
131                     1                17      18                        2   
132                     2                14      23                        2   
133                     2                24      26                        2   
134                     2                 9      24                        2   
135                     2                12       8                        2   
136                     2                 9       6                        2   
137                     2                22       1                        2   
138                     2                 7      11                        2   
139  

In [2]:
dataset_teaching.columns

Index(['nativeEnglishSpeaker', 'courseInstructor', 'course',
       'summerOrRegularSemester', 'classSize', 'resultado'],
      dtype='object')

In [3]:
teaching_normalizada = dataset_teaching.values.copy()
normalizador =  StandardScaler()

teaching_normalizada = normalizador.fit_transform(dataset_teaching)
dataset_teaching['courseInstructor'] = teaching_normalizada[:,1]
dataset_teaching['course'] = teaching_normalizada[:,2]
dataset_teaching['classSize'] = teaching_normalizada[:,4]

print("\nDataset Teaching Assistant Evaluation normalizada:")
dataset_teaching


Dataset Teaching Assistant Evaluation normalizada:


nativeEnglishSpeaker  courseInstructor    course  \
0                       1          1.375485 -0.729359   
1                       2          0.199557 -0.729359   
2                       1          1.375485 -0.729359   
3                       1         -1.270352 -0.872203   
4                       2         -0.976370  0.413398   
5                       2          1.375485 -0.729359   
6                       2         -0.682388 -0.443669   
7                       2         -0.535398 -0.729359   
8                       1          1.228494 -0.729359   
9                       2          0.199557 -0.729359   
10                      2         -0.535398  1.984688   
11                      2         -0.094425 -1.015048   
12                      2          0.640530  1.841843   
13                      2         -1.123361  1.270465   
14                      2         -1.123361  1.270465   
15                      2         -1.123361  1.270465   
16                      2         -0.976370  0.413398   
17                      2          1.228494 -0.729359   
18                      2         -0.094425 -0.729359   
19                      2         -0.976370  2.413222   
20                      2          1.669467 -0.157980   
21                      2          1.669467 -0.157980   
22                      2         -1.711325  0.127709   
23                      2         -1.858316  0.984776   
24                      2          0.199557  0.699087   
25                      2         -0.976370  0.413398   
26                      2         -0.829379 -0.729359   
27                      2          0.052566  0.984776   
28                      2          1.081503 -0.872203   
29                      2          1.228494 -0.729359   
..                    ...               ...       ...   
121                     2         -0.094425  0.841931   
122                     2         -0.682388 -0.300825   
123                     1         -0.535398 -0.729359   
124                     2          0.052566  0.984776   
125                     1         -0.094425 -1.015048   
126                     1         -0.829379 -0.729359   
127                     2          0.934512 -0.872203   
128                     2          1.228494 -1.015048   
129                     2          0.640530  0.556242   
130                     2          0.934512  0.984776   
131                     1          0.493539  1.413310   
132                     2          0.052566  2.127532   
133                     2          1.522476  2.556066   
134                     2         -0.682388  2.270377   
135                     2         -0.241416 -0.015136   
136                     2         -0.682388 -0.300825   
137                     2          1.228494 -1.015048   
138                     2         -0.976370  0.413398   
139                     2         -0.535398 -0.729359   
140                     2          1.375485 -0.729359   
141                     2          0.493539  1.413310   
142                     2          0.346548  1.698999   
143                     2         -1.564334 -0.872203   
144                     2          0.787521 -0.586514   
145                     2          1.375485 -0.729359   
146                     2         -1.564334 -0.872203   
147                     2         -0.535398 -0.729359   
148                     1          0.640530 -0.157980   
149                     2          1.228494 -1.015048   
150                     2         -1.711325  0.270553   

     summerOrRegularSemester  classSize  resultado  
0                          1  -0.690028          3  
1                          1  -0.845658          3  
2                          2   1.644422          3  
3                          2   0.399382          3  
4                          2   2.111312          3  
5                          1  -0.612213          3  
6                          2  -0.690028          3  
7                          2  -0.067508       

In [4]:
teaching_values = dataset_teaching.iloc[:,0:6].values
print("\nTeaching Assistant Evaluation features:\n")
print(teaching_values)


Teaching Assistant Evaluation features:

[[ 1.          1.37548494 -0.7293586   1.         -0.69002837  3.        ]
 [ 2.          0.19955726 -0.7293586   1.         -0.84565836  3.        ]
 [ 1.          1.37548494 -0.7293586   2.          1.6444216   3.        ]
 [ 1.         -1.27035233 -0.87220315  2.          0.39938162  3.        ]
 [ 2.         -0.97637041  0.4133978   2.          2.11131159  3.        ]
 [ 2.          1.37548494 -0.7293586   1.         -0.61221337  3.        ]
 [ 2.         -0.68238849 -0.4436695   2.         -0.69002837  3.        ]
 [ 2.         -0.53539753 -0.7293586   2.         -0.06750838  3.        ]
 [ 1.          1.22849398 -0.7293586   1.          2.34475658  3.        ]
 [ 2.          0.19955726 -0.7293586   1.         -0.61221337  3.        ]
 [ 2.         -0.53539753  1.98468785  2.         -1.46817835  3.        ]
 [ 2.         -0.09442466 -1.0150477   2.          0.16593662  3.        ]
 [ 2.          0.64053014  1.8418433   2.          0.08812

In [5]:
teaching_classes = dataset_teaching.iloc[:,5].values
print("\nTeaching Assistant Evaluation features classes:\n")
print(teaching_classes)
print("\nTeaching Assistant Evaluation features classes shape:")
print(teaching_classes.shape)


Teaching Assistant Evaluation features classes:

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1
 1 1 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1
 1 1 1 1 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
 1 1 1]

Teaching Assistant Evaluation features classes shape:
(151,)


In [6]:
kfold_treinamento = model_selection.StratifiedKFold(n_splits=5, shuffle=True, random_state=None)
kfold_ajuste_parametros = model_selection.StratifiedKFold(n_splits=3, shuffle=True, random_state=None)

In [7]:
arvore_decisao = DecisionTreeClassifier()
print("====== Iniciando busca pelos melhores parâmetros do algoritmo Arvore de decisao no dataset Teaching ....\n")

param_dist = {'max_depth':list(np.arange(1,10)), 'min_samples_split':list(np.arange(1,10)) ,'criterion':['entropy'], 'splitter':['best','random']}
grid_search = GridSearchCV(arvore_decisao, param_grid=param_dist, cv=kfold_ajuste_parametros, scoring='accuracy', refit=False)
grid_search.fit(teaching_values, teaching_classes)
decisionTreeBestParams = grid_search.best_params_
print("Decision Tree: %s \n\n" % decisionTreeBestParams)

====== Iniciando busca pelos melhores parâmetros do algoritmo Arvore de decisao no dataset Teaching ....

Decision Tree: {'splitter': 'best', 'criterion': 'entropy', 'max_depth': 3} 




In [8]:
knn_vizinhos_proximos = KNeighborsClassifier()
print("====== Iniciando busca pelos melhores parâmetros do algoritmo KNN no dataset Teaching ....\n")

param_dist = {'n_neighbors':[3,5,7,9], 'metric':['euclidean', 'manhattan'], 'weights':['uniform', 'distance']} #Parâmetros testados

grid_search = GridSearchCV(knn_vizinhos_proximos, param_grid=param_dist, cv=kfold_ajuste_parametros, scoring='accuracy', refit=False)
grid_search.fit(teaching_values, teaching_classes)
knnBestParams = grid_search.best_params_
print("KNN: %s \n\n" % knnBestParams)

====== Iniciando busca pelos melhores parâmetros do algoritmo KNN no dataset Teaching ....

KNN: {'metric': 'euclidean', 'weights': 'uniform', 'n_neighbors': 1} 




In [9]:
regressao_logistica = LogisticRegression()
print("====== Iniciando busca pelos melhores parâmetros do algoritmo Regressao logistica no dataset Teaching ....\n")

param_dist = {'penalty':['l2','l1'], 'max_iter':[200,300,400,500],'solver':['liblinear','sag','saga']} #Parâmetros testados

grid_search = GridSearchCV(regressao_logistica, param_grid=param_dist, cv=kfold_ajuste_parametros, scoring='accuracy', refit=False)
grid_search.fit(teaching_values, teaching_classes)
regressao_logistica_param = grid_search.best_params_
print("Regressão logistica: %s \n\n" % regressao_logistica_param)

====== Iniciando busca pelos melhores parâmetros do algoritmo Regressao logistica no dataset Teaching ....

Regressão logistica: {'penalty': 'l2', 'tol': 0.0001, 'solver': 'lbfgs', 'max_iter': 300} 




/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reac

In [10]:
rede_neural = MLPClassifier()
print("====== Iniciando busca pelos melhores parâmetros do algoritmo Redes neurais no dataset Teaching ....\n")

param_dist = {'hidden_layer_sizes':list(np.arange(10,20)),'activation':['logistic','identity','tanh'], 'max_iter':[100,200,300,400],'alpha':[0.0001,0.001, 0.01, 0.1], 'solver':['sgd','adam']}

grid_search = GridSearchCV(rede_neural, param_grid=param_dist, cv=kfold_ajuste_parametros, scoring='accuracy', refit=False)
grid_search.fit(teaching_values, teaching_classes)
redes_neurais_param = grid_search.best_params_
print("Redes neurais: %s \n\n" % redes_neurais_param)

====== Iniciando busca pelos melhores parâmetros do algoritmo Redes neurais no dataset Teaching ....

Redes neurais: {'learning_rate': 'constant', 'hidden_layer_sizes': 9, 'activation': 'logistic', 'learning_rate_init': 0.01, 'solver': 'adam', 'alpha': 0.0001, 'max_iter': 600} 




/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.

In [11]:
kf = model_selection.StratifiedKFold(n_splits = 5)
arvore_decisao = tree.DecisionTreeClassifier(criterion='entropy', splitter='best', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, random_state=None, max_leaf_nodes=None, min_impurity_decrease=0.0, min_impurity_split=None, class_weight=None, presort='deprecated', ccp_alpha=0.0)
vizinhos_proximos = KNeighborsClassifier(n_neighbors=3, weights = 'distance')
naive_bayes_gaussian = GaussianNB()
regressao_logistica = LogisticRegression(penalty='l2', dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='saga', max_iter=100, multi_class='auto', verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)
rede_neural = MLPClassifier(hidden_layer_sizes=(5,), activation="logistic", max_iter= 300, alpha=0.001, solver="sgd", tol=1e-4, verbose=True, learning_rate_init=.01)

In [12]:
predicted_classes = dict()
predicted_classes['arvore_decisao'] = np.zeros(teaching_classes.shape)
predicted_classes['vizinhos_proximos'] = np.zeros(teaching_classes.shape)
predicted_classes['naive_bayes_gaussian'] = np.zeros(teaching_classes.shape)
predicted_classes['regressao_logistica'] = np.zeros(teaching_classes.shape)
predicted_classes['rede_neural'] = np.zeros(teaching_classes.shape)

arvore_decisao_best_param = DecisionTreeClassifier(**decisionTreeBestParams)
knn_vizinhos_proximos_best_param = KNeighborsClassifier(**knnBestParams)
naive_bayes_gaussian = GaussianNB()
regressao_logistica_best_param = LogisticRegression(**regressao_logistica_param)
rede_neural_best_param = MLPClassifier(**redes_neurais_param)

In [13]:

for train, test in kf.split(teaching_values, teaching_classes):
    data_train, target_train = teaching_values[train], teaching_classes[train]
    data_test, target_test = teaching_values[test], teaching_classes[test]

    arvore_decisao = arvore_decisao.fit(data_train, target_train)
    arvore_decisao_predicted = arvore_decisao.predict(data_test)
    predicted_classes['arvore_decisao'][test] = arvore_decisao_predicted

    vizinhos_proximos = vizinhos_proximos.fit(data_train, target_train)
    vizinhos_proximos_predicted = vizinhos_proximos.predict(data_test)
    predicted_classes['vizinhos_proximos'][test] = vizinhos_proximos_predicted

    naive_bayes_gaussian = naive_bayes_gaussian.fit(data_train, target_train)
    naive_bayes_gaussian_predicted = naive_bayes_gaussian.predict(data_test)
    predicted_classes['naive_bayes_gaussian'][test] = naive_bayes_gaussian_predicted

    regressao_logistica = regressao_logistica.fit(data_train, target_train)
    regressao_logistica_predicted = regressao_logistica.predict(data_test)
    predicted_classes['regressao_logistica'][test] = regressao_logistica_predicted

    rede_neural = rede_neural.fit(data_train, target_train)
    rede_neural_predicted = rede_neural.predict(data_test)
    predicted_classes['rede_neural'][test] = rede_neural_predicted

/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-pa

Iteration 1, loss = 1.16405361
Iteration 2, loss = 1.16234666
Iteration 3, loss = 1.15998056
Iteration 4, loss = 1.15708897
Iteration 5, loss = 1.15380241
Iteration 6, loss = 1.15024446
Iteration 7, loss = 1.14652900
Iteration 8, loss = 1.14275823
Iteration 9, loss = 1.13902124
Iteration 10, loss = 1.13539334
Iteration 11, loss = 1.13193577
Iteration 12, loss = 1.12869598
Iteration 13, loss = 1.12570816
Iteration 14, loss = 1.12299423
Iteration 15, loss = 1.12056497
Iteration 16, loss = 1.11842143
Iteration 17, loss = 1.11655634
Iteration 18, loss = 1.11495571
Iteration 19, loss = 1.11360031
Iteration 20, loss = 1.11246718
Iteration 21, loss = 1.11153098
Iteration 22, loss = 1.11076525
Iteration 23, loss = 1.11014345
Iteration 24, loss = 1.10963988
Iteration 25, loss = 1.10923041
Iteration 26, loss = 1.10889297
Iteration 27, loss = 1.10860798
Iteration 28, loss = 1.10835849
Iteration 29, loss = 1.10813030
Iteration 30, loss = 1.10791190
Iteration 31, loss = 1.10769433
Iteration 32, los

In [14]:
for classificador in predicted_classes.keys():
    print("================================================================================================")
    print("Resultados do classificador %s\n%s\n"
          %(classificador, metrics.classification_report(teaching_classes, predicted_classes[classificador])))
    print("Matriz de confusão: \n%s\n\n\n" % metrics.confusion_matrix(teaching_classes, predicted_classes[classificador]))

Resultados do classificador regressao_logistica
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        49
           2       1.00      1.00      1.00        50
           3       1.00      1.00      1.00        52

    accuracy                           1.00       151
   macro avg       1.00      1.00      1.00       151
weighted avg       1.00      1.00      1.00       151


Matriz de confusão: 
[[49  0  0]
 [ 0 50  0]
 [ 0  0 52]]



Resultados do classificador rede_neural
              precision    recall  f1-score   support

           1       0.96      0.96      0.96        49
           2       0.92      0.70      0.80        50
           3       0.80      0.98      0.88        52

    accuracy                           0.88       151
   macro avg       0.89      0.88      0.88       151
weighted avg       0.89      0.88      0.88       151


Matriz de confusão: 
[[47  2  0]
 [ 2 35 13]
 [ 0  1 51]]



Resultados do classificado