In [2]:
from sklearn import tree, preprocessing
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn import model_selection
from sklearn import metrics
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler


dataset_teaching = pd.read_csv('teachingAssistantEvaluation.data', sep=',')
print("\nDataset teaching Assistant Evaluation:")
dataset_teaching


Dataset teaching Assistant Evaluation:


nativeEnglishSpeaker  courseInstructor  course  summerOrRegularSemester  \
0                       1                23       3                        1   
1                       2                15       3                        1   
2                       1                23       3                        2   
3                       1                 5       2                        2   
4                       2                 7      11                        2   
5                       2                23       3                        1   
6                       2                 9       5                        2   
7                       2                10       3                        2   
8                       1                22       3                        1   
9                       2                15       3                        1   
10                      2                10      22                        2   
11                      2                13       1                        2   
12                      2                18      21                        2   
13                      2                 6      17                        2   
14                      2                 6      17                        2   
15                      2                 6      17                        2   
16                      2                 7      11                        2   
17                      2                22       3                        2   
18                      2                13       3                        1   
19                      2                 7      25                        2   
20                      2                25       7                        2   
21                      2                25       7                        2   
22                      2                 2       9                        2   
23                      2                 1      15                        1   
24                      2                15      13                        2   
25                      2                 7      11                        2   
26                      2                 8       3                        2   
27                      2                14      15                        2   
28                      2                21       2                        2   
29                      2                22       3                        2   
..                    ...               ...     ...                      ...   
121                     2                13      14                        2   
122                     2                 9       6                        2   
123                     1                10       3                        2   
124                     2                14      15                        2   
125                     1                13       1                        2   
126                     1                 8       3                        2   
127                     2                20       2                        2   
128                     2                22       1                        2   
129                     2                18      12                        2   
130                     2                20      15                        2   
131                     1                17      18                        2   
132                     2                14      23                        2   
133                     2                24      26                        2   
134                     2                 9      24                        2   
135                     2                12       8                        2   
136                     2                 9       6                        2   
137                     2                22       1                        2   
138                     2                 7      11                        2   
139  

In [4]:
dataset_teaching.columns

Index(['nativeEnglishSpeaker', 'courseInstructor', 'course',
       'summerOrRegularSemester', 'classSize', 'resultado'],
      dtype='object')

In [5]:
teaching_normalizada = dataset_teaching.values.copy()
normalizador =  StandardScaler()

teaching_normalizada = normalizador.fit_transform(dataset_teaching)
dataset_teaching['courseInstructor'] = teaching_normalizada[:,1]
dataset_teaching['classSize'] = teaching_normalizada[:,4]

print("\nDataset Teaching Assistant Evaluation normalizada:")
dataset_teaching


Dataset Teaching Assistant Evaluation normalizada:


nativeEnglishSpeaker  courseInstructor  course  summerOrRegularSemester  \
0                       1          1.375485       3                        1   
1                       2          0.199557       3                        1   
2                       1          1.375485       3                        2   
3                       1         -1.270352       2                        2   
4                       2         -0.976370      11                        2   
5                       2          1.375485       3                        1   
6                       2         -0.682388       5                        2   
7                       2         -0.535398       3                        2   
8                       1          1.228494       3                        1   
9                       2          0.199557       3                        1   
10                      2         -0.535398      22                        2   
11                      2         -0.094425       1                        2   
12                      2          0.640530      21                        2   
13                      2         -1.123361      17                        2   
14                      2         -1.123361      17                        2   
15                      2         -1.123361      17                        2   
16                      2         -0.976370      11                        2   
17                      2          1.228494       3                        2   
18                      2         -0.094425       3                        1   
19                      2         -0.976370      25                        2   
20                      2          1.669467       7                        2   
21                      2          1.669467       7                        2   
22                      2         -1.711325       9                        2   
23                      2         -1.858316      15                        1   
24                      2          0.199557      13                        2   
25                      2         -0.976370      11                        2   
26                      2         -0.829379       3                        2   
27                      2          0.052566      15                        2   
28                      2          1.081503       2                        2   
29                      2          1.228494       3                        2   
..                    ...               ...     ...                      ...   
121                     2         -0.094425      14                        2   
122                     2         -0.682388       6                        2   
123                     1         -0.535398       3                        2   
124                     2          0.052566      15                        2   
125                     1         -0.094425       1                        2   
126                     1         -0.829379       3                        2   
127                     2          0.934512       2                        2   
128                     2          1.228494       1                        2   
129                     2          0.640530      12                        2   
130                     2          0.934512      15                        2   
131                     1          0.493539      18                        2   
132                     2          0.052566      23                        2   
133                     2          1.522476      26                        2   
134                     2         -0.682388      24                        2   
135                     2         -0.241416       8                        2   
136                     2         -0.682388       6                        2   
137                     2          1.228494       1                        2   
138                     2         -0.976370      11                        2   
139  

In [6]:
teaching_values = dataset_teaching.iloc[:,0:6].values
print("\nTeaching Assistant Evaluation features:\n")
print(teaching_values)


Teaching Assistant Evaluation features:

[[ 1.00000000e+00  1.37548494e+00  3.00000000e+00  1.00000000e+00
  -6.90028366e-01  3.00000000e+00]
 [ 2.00000000e+00  1.99557263e-01  3.00000000e+00  1.00000000e+00
  -8.45658364e-01  3.00000000e+00]
 [ 1.00000000e+00  1.37548494e+00  3.00000000e+00  2.00000000e+00
   1.64442160e+00  3.00000000e+00]
 [ 1.00000000e+00 -1.27035233e+00  2.00000000e+00  2.00000000e+00
   3.99381616e-01  3.00000000e+00]
 [ 2.00000000e+00 -9.76370412e-01  1.10000000e+01  2.00000000e+00
   2.11131159e+00  3.00000000e+00]
 [ 2.00000000e+00  1.37548494e+00  3.00000000e+00  1.00000000e+00
  -6.12213367e-01  3.00000000e+00]
 [ 2.00000000e+00 -6.82388493e-01  5.00000000e+00  2.00000000e+00
  -6.90028366e-01  3.00000000e+00]
 [ 2.00000000e+00 -5.35397534e-01  3.00000000e+00  2.00000000e+00
  -6.75083764e-02  3.00000000e+00]
 [ 1.00000000e+00  1.22849398e+00  3.00000000e+00  1.00000000e+00
   2.34475658e+00  3.00000000e+00]
 [ 2.00000000e+00  1.99557263e-01  3.00000000e+00

In [7]:
teaching_classes = dataset_teaching.iloc[:,5].values
print("\nTeaching Assistant Evaluation features classes:\n")
print(teaching_classes)
print("\nTeaching Assistant Evaluation features classes shape:")
print(teaching_classes.shape)


Teaching Assistant Evaluation features classes:

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1
 1 1 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1
 1 1 1 1 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
 1 1 1]

Teaching Assistant Evaluation features classes shape:
(151,)


In [8]:
kf = model_selection.StratifiedKFold(n_splits = 5)
arvore_decisao = tree.DecisionTreeClassifier(criterion='entropy', splitter='best', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, random_state=None, max_leaf_nodes=None, min_impurity_decrease=0.0, min_impurity_split=None, class_weight=None, presort='deprecated', ccp_alpha=0.0)
vizinhos_proximos = KNeighborsClassifier(n_neighbors=3, weights = 'distance')
naive_bayes_gaussian = GaussianNB()
regressao_logistica = LogisticRegression(penalty='l2', dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='saga', max_iter=100, multi_class='auto', verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)
rede_neural = MLPClassifier(hidden_layer_sizes=(5,), activation="logistic", max_iter= 300, alpha=0.001, solver="sgd", tol=1e-4, verbose=True, learning_rate_init=.01)

In [9]:
predicted_classes = dict()
predicted_classes['arvore_decisao'] = np.zeros(teaching_classes.shape)
predicted_classes['vizinhos_proximos'] = np.zeros(teaching_classes.shape)
predicted_classes['naive_bayes_gaussian'] = np.zeros(teaching_classes.shape)
predicted_classes['regressao_logistica'] = np.zeros(teaching_classes.shape)
predicted_classes['rede_neural'] = np.zeros(teaching_classes.shape)

In [10]:

for train, test in kf.split(teaching_values, teaching_classes):
    data_train, target_train = teaching_values[train], teaching_classes[train]
    data_test, target_test = teaching_values[test], teaching_classes[test]

    arvore_decisao = arvore_decisao.fit(data_train, target_train)
    arvore_decisao_predicted = arvore_decisao.predict(data_test)
    predicted_classes['arvore_decisao'][test] = arvore_decisao_predicted

    vizinhos_proximos = vizinhos_proximos.fit(data_train, target_train)
    vizinhos_proximos_predicted = vizinhos_proximos.predict(data_test)
    predicted_classes['vizinhos_proximos'][test] = vizinhos_proximos_predicted

    naive_bayes_gaussian = naive_bayes_gaussian.fit(data_train, target_train)
    naive_bayes_gaussian_predicted = naive_bayes_gaussian.predict(data_test)
    predicted_classes['naive_bayes_gaussian'][test] = naive_bayes_gaussian_predicted

    regressao_logistica = regressao_logistica.fit(data_train, target_train)
    regressao_logistica_predicted = regressao_logistica.predict(data_test)
    predicted_classes['regressao_logistica'][test] = regressao_logistica_predicted

    rede_neural = rede_neural.fit(data_train, target_train)
    rede_neural_predicted = rede_neural.predict(data_test)
    predicted_classes['rede_neural'][test] = rede_neural_predicted

/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


Iteration 1, loss = 1.11508265
Iteration 2, loss = 1.11457218
Iteration 3, loss = 1.11385808
Iteration 4, loss = 1.11297440
Iteration 5, loss = 1.11195363
Iteration 6, loss = 1.11082606
Iteration 7, loss = 1.10961920
Iteration 8, loss = 1.10835764
Iteration 9, loss = 1.10706279
Iteration 10, loss = 1.10575301
Iteration 11, loss = 1.10444365
Iteration 12, loss = 1.10314727
Iteration 13, loss = 1.10187384
Iteration 14, loss = 1.10063103
Iteration 15, loss = 1.09942446
Iteration 16, loss = 1.09825800
Iteration 17, loss = 1.09713401
Iteration 18, loss = 1.09605358
Iteration 19, loss = 1.09501680
Iteration 20, loss = 1.09402294
Iteration 21, loss = 1.09307063
Iteration 22, loss = 1.09215803
Iteration 23, loss = 1.09128299
Iteration 24, loss = 1.09044311
Iteration 25, loss = 1.08963588
Iteration 26, loss = 1.08885878
Iteration 27, loss = 1.08810929
Iteration 28, loss = 1.08738494
Iteration 29, loss = 1.08668343
Iteration 30, loss = 1.08600253
Iteration 31, loss = 1.08534022
Iteration 32, los

/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


Iteration 53, loss = 1.07191504
Iteration 54, loss = 1.07138715
Iteration 55, loss = 1.07086673
Iteration 56, loss = 1.07035160
Iteration 57, loss = 1.06983998
Iteration 58, loss = 1.06933048
Iteration 59, loss = 1.06882207
Iteration 60, loss = 1.06831404
Iteration 61, loss = 1.06780591
Iteration 62, loss = 1.06729744
Iteration 63, loss = 1.06678853
Iteration 64, loss = 1.06627919
Iteration 65, loss = 1.06576951
Iteration 66, loss = 1.06525958
Iteration 67, loss = 1.06474952
Iteration 68, loss = 1.06423941
Iteration 69, loss = 1.06372929
Iteration 70, loss = 1.06321917
Iteration 71, loss = 1.06270901
Iteration 72, loss = 1.06219869
Iteration 73, loss = 1.06168807
Iteration 74, loss = 1.06117697
Iteration 75, loss = 1.06066517
Iteration 76, loss = 1.06015242
Iteration 77, loss = 1.05963846
Iteration 78, loss = 1.05912302
Iteration 79, loss = 1.05860584
Iteration 80, loss = 1.05808667
Iteration 81, loss = 1.05756524
Iteration 82, loss = 1.05704133
Iteration 83, loss = 1.05651472
Iteratio

/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


Iteration 194, loss = 0.98650221
Iteration 195, loss = 0.98524738
Iteration 196, loss = 0.98397890
Iteration 197, loss = 0.98269655
Iteration 198, loss = 0.98140011
Iteration 199, loss = 0.98008934
Iteration 200, loss = 0.97876399
Iteration 201, loss = 0.97742377
Iteration 202, loss = 0.97606840
Iteration 203, loss = 0.97469753
Iteration 204, loss = 0.97331083
Iteration 205, loss = 0.97190789
Iteration 206, loss = 0.97048829
Iteration 207, loss = 0.96905156
Iteration 208, loss = 0.96759715
Iteration 209, loss = 0.96612449
Iteration 210, loss = 0.96463291
Iteration 211, loss = 0.96312167
Iteration 212, loss = 0.96158993
Iteration 213, loss = 0.96003673
Iteration 214, loss = 0.95846101
Iteration 215, loss = 0.95686155
Iteration 216, loss = 0.95523694
Iteration 217, loss = 0.95358563
Iteration 218, loss = 0.95190580
Iteration 219, loss = 0.95019543
Iteration 220, loss = 0.94845220
Iteration 221, loss = 0.94667354
Iteration 222, loss = 0.94485655
Iteration 223, loss = 0.94299805
Iteration 

/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


Iteration 90, loss = 1.04210557
Iteration 91, loss = 1.04162120
Iteration 92, loss = 1.04113782
Iteration 93, loss = 1.04065539
Iteration 94, loss = 1.04017388
Iteration 95, loss = 1.03969324
Iteration 96, loss = 1.03921343
Iteration 97, loss = 1.03873443
Iteration 98, loss = 1.03825620
Iteration 99, loss = 1.03777869
Iteration 100, loss = 1.03730188
Iteration 101, loss = 1.03682574
Iteration 102, loss = 1.03635024
Iteration 103, loss = 1.03587533
Iteration 104, loss = 1.03540100
Iteration 105, loss = 1.03492721
Iteration 106, loss = 1.03445393
Iteration 107, loss = 1.03398113
Iteration 108, loss = 1.03350878
Iteration 109, loss = 1.03303686
Iteration 110, loss = 1.03256532
Iteration 111, loss = 1.03209414
Iteration 112, loss = 1.03162329
Iteration 113, loss = 1.03115273
Iteration 114, loss = 1.03068245
Iteration 115, loss = 1.03021239
Iteration 116, loss = 1.02974253
Iteration 117, loss = 1.02927284
Iteration 118, loss = 1.02880328
Iteration 119, loss = 1.02833382
Iteration 120, loss 

/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


Iteration 115, loss = 1.05232283
Iteration 116, loss = 1.05180759
Iteration 117, loss = 1.05128995
Iteration 118, loss = 1.05076990
Iteration 119, loss = 1.05024738
Iteration 120, loss = 1.04972238
Iteration 121, loss = 1.04919485
Iteration 122, loss = 1.04866476
Iteration 123, loss = 1.04813207
Iteration 124, loss = 1.04759675
Iteration 125, loss = 1.04705875
Iteration 126, loss = 1.04651805
Iteration 127, loss = 1.04597460
Iteration 128, loss = 1.04542837
Iteration 129, loss = 1.04487932
Iteration 130, loss = 1.04432741
Iteration 131, loss = 1.04377260
Iteration 132, loss = 1.04321486
Iteration 133, loss = 1.04265414
Iteration 134, loss = 1.04209040
Iteration 135, loss = 1.04152361
Iteration 136, loss = 1.04095373
Iteration 137, loss = 1.04038070
Iteration 138, loss = 1.03980450
Iteration 139, loss = 1.03922507
Iteration 140, loss = 1.03864238
Iteration 141, loss = 1.03805639
Iteration 142, loss = 1.03746704
Iteration 143, loss = 1.03687430
Iteration 144, loss = 1.03627812
Iteration 

/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [11]:
for classificador in predicted_classes.keys():
    print("================================================================================================")
    print("Resultados do classificador %s\n%s\n"
          %(classificador, metrics.classification_report(teaching_classes, predicted_classes[classificador])))
    print("Matriz de confusão: \n%s\n\n\n" % metrics.confusion_matrix(teaching_classes, predicted_classes[classificador]))




Resultados do classificador arvore_decisao
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        49
           2       1.00      1.00      1.00        50
           3       1.00      1.00      1.00        52

    accuracy                           1.00       151
   macro avg       1.00      1.00      1.00       151
weighted avg       1.00      1.00      1.00       151


Matriz de confusão: 
[[49  0  0]
 [ 0 50  0]
 [ 0  0 52]]



Resultados do classificador regressao_logistica
              precision    recall  f1-score   support

           1       1.00      0.94      0.97        49
           2       0.94      0.94      0.94        50
           3       0.95      1.00      0.97        52

    accuracy                           0.96       151
   macro avg       0.96      0.96      0.96       151
weighted avg       0.96      0.96      0.96       151


Matriz de confusão: 
[[46  3  0]
 [ 0 47  3]
 [ 0  0 52]]



Resultados do classific