In [1]:
from sklearn import tree
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn import model_selection
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier


dataset_iris = pd.read_table('iris.data', sep=',', index_col=None)
print("Dataset Iris")
dataset_iris

/home/larissa/.local/lib/python3.5/site-packages/ipykernel_launcher.py:15: FutureWarning: read_table is deprecated, use read_csv instead.
  from ipykernel import kernelapp as app


Dataset Iris


sepal length in cm  sepal width in cm  petal length in cm  \
0                   5.1                3.5                 1.4   
1                   4.9                3.0                 1.4   
2                   4.7                3.2                 1.3   
3                   4.6                3.1                 1.5   
4                   5.0                3.6                 1.4   
5                   5.4                3.9                 1.7   
6                   4.6                3.4                 1.4   
7                   5.0                3.4                 1.5   
8                   4.4                2.9                 1.4   
9                   4.9                3.1                 1.5   
10                  5.4                3.7                 1.5   
11                  4.8                3.4                 1.6   
12                  4.8                3.0                 1.4   
13                  4.3                3.0                 1.1   
14                  5.8                4.0                 1.2   
15                  5.7                4.4                 1.5   
16                  5.4                3.9                 1.3   
17                  5.1                3.5                 1.4   
18                  5.7                3.8                 1.7   
19                  5.1                3.8                 1.5   
20                  5.4                3.4                 1.7   
21                  5.1                3.7                 1.5   
22                  4.6                3.6                 1.0   
23                  5.1                3.3                 1.7   
24                  4.8                3.4                 1.9   
25                  5.0                3.0                 1.6   
26                  5.0                3.4                 1.6   
27                  5.2                3.5                 1.5   
28                  5.2                3.4                 1.4   
29                  4.7                3.2                 1.6   
..                  ...                ...                 ...   
120                 6.9                3.2                 5.7   
121                 5.6                2.8                 4.9   
122                 7.7                2.8                 6.7   
123                 6.3                2.7                 4.9   
124                 6.7                3.3                 5.7   
125                 7.2                3.2                 6.0   
126                 6.2                2.8                 4.8   
127                 6.1                3.0                 4.9   
128                 6.4                2.8                 5.6   
129                 7.2                3.0                 5.8   
130                 7.4                2.8                 6.1   
131                 7.9                3.8                 6.4   
132                 6.4                2.8                 5.6   
133                 6.3                2.8                 5.1   
134                 6.1                2.6                 5.6   
135                 7.7                3.0                 6.1   
136                 6.3                3.4                 5.6   
137                 6.4                3.1                 5.5   
138                 6.0                3.0                 4.8   
139                 6.9                3.1                 5.4   
140                 6.7                3.1                 5.6   
141                 6.9                3.1                 5.1   
142                 5.8                2.7                 5.1   
143                 6.8                3.2                 5.9   
144                 6.7                3.3                 5.7   
145                 6.7                3.0                 5.2   
146                 6.3                2.5                 5.0   
147                 6.5                3.0                 5.2   
148                 6.2                3.4   

In [2]:
dataset_iris.columns

Index(['sepal length in cm', 'sepal width in cm', 'petal length in cm',
       'petal width in cm', 'class'],
      dtype='object')

In [3]:
dataset_iris['sepal length in cm'] = dataset_iris['sepal length in cm'].astype(float)
dataset_iris['sepal width in cm'] = dataset_iris['sepal width in cm'].astype(float)
dataset_iris['petal length in cm'] = dataset_iris['petal length in cm'].astype(float)
dataset_iris['petal width in cm'] = dataset_iris['petal width in cm'].astype(float)
dataset_iris

sepal length in cm  sepal width in cm  petal length in cm  \
0                   5.1                3.5                 1.4   
1                   4.9                3.0                 1.4   
2                   4.7                3.2                 1.3   
3                   4.6                3.1                 1.5   
4                   5.0                3.6                 1.4   
5                   5.4                3.9                 1.7   
6                   4.6                3.4                 1.4   
7                   5.0                3.4                 1.5   
8                   4.4                2.9                 1.4   
9                   4.9                3.1                 1.5   
10                  5.4                3.7                 1.5   
11                  4.8                3.4                 1.6   
12                  4.8                3.0                 1.4   
13                  4.3                3.0                 1.1   
14                  5.8                4.0                 1.2   
15                  5.7                4.4                 1.5   
16                  5.4                3.9                 1.3   
17                  5.1                3.5                 1.4   
18                  5.7                3.8                 1.7   
19                  5.1                3.8                 1.5   
20                  5.4                3.4                 1.7   
21                  5.1                3.7                 1.5   
22                  4.6                3.6                 1.0   
23                  5.1                3.3                 1.7   
24                  4.8                3.4                 1.9   
25                  5.0                3.0                 1.6   
26                  5.0                3.4                 1.6   
27                  5.2                3.5                 1.5   
28                  5.2                3.4                 1.4   
29                  4.7                3.2                 1.6   
..                  ...                ...                 ...   
120                 6.9                3.2                 5.7   
121                 5.6                2.8                 4.9   
122                 7.7                2.8                 6.7   
123                 6.3                2.7                 4.9   
124                 6.7                3.3                 5.7   
125                 7.2                3.2                 6.0   
126                 6.2                2.8                 4.8   
127                 6.1                3.0                 4.9   
128                 6.4                2.8                 5.6   
129                 7.2                3.0                 5.8   
130                 7.4                2.8                 6.1   
131                 7.9                3.8                 6.4   
132                 6.4                2.8                 5.6   
133                 6.3                2.8                 5.1   
134                 6.1                2.6                 5.6   
135                 7.7                3.0                 6.1   
136                 6.3                3.4                 5.6   
137                 6.4                3.1                 5.5   
138                 6.0                3.0                 4.8   
139                 6.9                3.1                 5.4   
140                 6.7                3.1                 5.6   
141                 6.9                3.1                 5.1   
142                 5.8                2.7                 5.1   
143                 6.8                3.2                 5.9   
144                 6.7                3.3                 5.7   
145                 6.7                3.0                 5.2   
146                 6.3                2.5                 5.0   
147                 6.5                3.0                 5.2   
148                 6.2                3.4   

In [4]:
iris_values = dataset_iris.iloc[:,0:4].values
print("Iris valores dos atributos:")
print(iris_values)

Iris valores dos atributos:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6

In [5]:
iris_classes = dataset_iris.iloc[:,4].values
print("Iris classes")
print(iris_classes)
print("\nIris classes shape")
print(iris_classes.shape)

Iris classes
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3]

Iris classes shape
(150,)


In [6]:
kfold_treinamento = model_selection.StratifiedKFold(n_splits=5, shuffle=True, random_state=None)
kfold_ajuste_parametros = model_selection.StratifiedKFold(n_splits=3, shuffle=True, random_state=None)

In [7]:
arvore_decisao = DecisionTreeClassifier()
print("====== Iniciando busca pelos melhores parâmetros do algoritmo Arvore de decisao no dataset Transfusion ....\n")

param_dist = {'max_depth':list(np.arange(1,10)), 'min_samples_split':list(np.arange(1,10)) ,'criterion':['entropy'], 'splitter':['best','random']}

grid_search = GridSearchCV(arvore_decisao, param_grid=param_dist, cv=kfold_ajuste_parametros, scoring='accuracy', refit=False)
grid_search.fit(iris_values, iris_classes)
decisionTreeBestParams = grid_search.best_params_
print("Decision Tree: %s \n\n" % decisionTreeBestParams)

====== Iniciando busca pelos melhores parâmetros do algoritmo Arvore de decisao no dataset Transfusion ....

Decision Tree: {'criterion': 'entropy', 'max_depth': 7, 'min_samples_split': 2, 'splitter': 'random'} 




/home/larissa/.local/lib/python3.5/site-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: min_samples_split must be an integer greater than 1 or a float in (0.0, 1.0]; got the integer 1

  FitFailedWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: min_samples_split must be an integer greater than 1 or a float in (0.0, 1.0]; got the integer 1

  FitFailedWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: min_samples_split must be an integer greater than 1 or a floa

In [8]:
knn_vizinhos_proximos = KNeighborsClassifier()
print("====== Iniciando busca pelos melhores parâmetros do algoritmo KNN no dataset Transfusion ....\n")

param_dist = {'n_neighbors':[3,5,7,9], 'metric':['euclidean', 'manhattan'], 'weights':['uniform', 'distance']} #Parâmetros testados

grid_search = GridSearchCV(knn_vizinhos_proximos, param_grid=param_dist, cv=kfold_ajuste_parametros, scoring='accuracy', refit=False)
grid_search.fit(iris_values, iris_classes)
knnBestParams = grid_search.best_params_
print("KNN: %s \n\n" % knnBestParams)

====== Iniciando busca pelos melhores parâmetros do algoritmo KNN no dataset Transfusion ....

KNN: {'weights': 'distance', 'n_neighbors': 5, 'metric': 'euclidean'} 




In [9]:
regressao_logistica = LogisticRegression()
print("====== Iniciando busca pelos melhores parâmetros do algoritmo Regressao logistica no dataset Transfusion ....\n")

param_dist = {'penalty':['l2','l1'], 'max_iter':[200,300,400,500],'solver':['liblinear','sag','saga']} #Parâmetros testados

grid_search = GridSearchCV(regressao_logistica, param_grid=param_dist, cv=kfold_ajuste_parametros, scoring='accuracy', refit=False)
grid_search.fit(iris_values, iris_classes)
regressao_logistica_param = grid_search.best_params_
print("Regressão logistica: %s \n\n" % regressao_logistica_param)


====== Iniciando busca pelos melhores parâmetros do algoritmo Regressao logistica no dataset Transfusion ....

Regressão logistica: {'penalty': 'l2', 'max_iter': 200, 'solver': 'saga'} 




/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reac

In [10]:
rede_neural = MLPClassifier()
print("====== Iniciando busca pelos melhores parâmetros do algoritmo Redes neurais no dataset Transfusion ....\n")

param_dist = {'hidden_layer_sizes':list(np.arange(10,20)),'activation':['logistic','identity','tanh'], 'max_iter':[100,200,300,400],'alpha':[0.0001,0.001, 0.01, 0.1], 'solver':['sgd','adam']}

grid_search = GridSearchCV(rede_neural, param_grid=param_dist, cv=kfold_ajuste_parametros, scoring='accuracy', refit=False)
grid_search.fit(iris_values, iris_classes)
redes_neurais_param = grid_search.best_params_
print("Redes neurais: %s \n\n" % redes_neurais_param)

/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.

====== Iniciando busca pelos melhores parâmetros do algoritmo Redes neurais no dataset Transfusion ....

Redes neurais: {'solver': 'adam', 'alpha': 0.0001, 'max_iter': 400, 'hidden_layer_sizes': 17, 'activation': 'tanh'} 




In [11]:
predicted_classes = dict()
predicted_classes['Arvore_decisao'] = np.zeros(iris_classes.shape)
predicted_classes['KNN_Vizinhos_proximos'] = np.zeros(iris_classes.shape)
predicted_classes['Naive_bayes_gaussian'] = np.zeros(iris_classes.shape)
predicted_classes['Regressao_logistica'] = np.zeros(iris_classes.shape)
predicted_classes['Rede_neural'] = np.zeros(iris_classes.shape)

arvore_decisao_best_param = DecisionTreeClassifier(**decisionTreeBestParams)
knn_vizinhos_proximos_best_param = KNeighborsClassifier(**knnBestParams)
naive_bayes_gaussian = GaussianNB()
regressao_logistica_best_param = LogisticRegression(**regressao_logistica_param)
rede_neural_best_param = MLPClassifier(**redes_neurais_param)

In [12]:
for train, test in kfold_treinamento.split(iris_values, iris_classes):
    data_train, target_train = iris_values[train], iris_classes[train]
    data_test, target_test = iris_values[test], iris_classes[test]

    arvore_decisao_best_param = arvore_decisao_best_param.fit(data_train, target_train)
    arvore_decisao_predicted = arvore_decisao_best_param.predict(data_test)
    predicted_classes['Arvore_decisao'][test] = arvore_decisao_predicted

    knn_vizinhos_proximos_best_param = knn_vizinhos_proximos_best_param.fit(data_train, target_train)
    vizinhos_proximos_predicted = knn_vizinhos_proximos_best_param.predict(data_test)
    predicted_classes['KNN_Vizinhos_proximos'][test] = vizinhos_proximos_predicted

    naive_bayes_gaussian = naive_bayes_gaussian.fit(data_train, target_train)
    naive_bayes_gaussian_predicted = naive_bayes_gaussian.predict(data_test)
    predicted_classes['Naive_bayes_gaussian'][test] = naive_bayes_gaussian_predicted

    regressao_logistica_best_param = regressao_logistica_best_param.fit(data_train, target_train)
    regressao_logistica_predicted = regressao_logistica_best_param.predict(data_test)
    predicted_classes['Regressao_logistica'][test] = regressao_logistica_predicted

    rede_neural_best_param = rede_neural_best_param.fit(data_train, target_train)
    rede_neural_predicted = rede_neural_best_param.predict(data_test)
    predicted_classes['Rede_neural'][test] = rede_neural_predicted

/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (400) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (400) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/larissa/.local/lib/python3.5/site-pa

In [13]:
for classificador in predicted_classes.keys():
    print("================================================================================================")
    print("Resultados do classificador %s\n%s\n"
          %(classificador, metrics.classification_report(iris_classes, predicted_classes[classificador])))
    print("Matriz de confusão: \n%s\n\n\n" % metrics.confusion_matrix(iris_classes, predicted_classes[classificador]))




Resultados do classificador Rede_neural
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        50
           2       0.98      0.94      0.96        50
           3       0.94      0.98      0.96        50

    accuracy                           0.97       150
   macro avg       0.97      0.97      0.97       150
weighted avg       0.97      0.97      0.97       150


Matriz de confusão: 
[[50  0  0]
 [ 0 47  3]
 [ 0  1 49]]



Resultados do classificador Regressao_logistica
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        50
           2       0.98      0.94      0.96        50
           3       0.94      0.98      0.96        50

    accuracy                           0.97       150
   macro avg       0.97      0.97      0.97       150
weighted avg       0.97      0.97      0.97       150


Matriz de confusão: 
[[50  0  0]
 [ 0 47  3]
 [ 0  1 49]]



Resultados do classificado