In [8]:
from sklearn import tree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn import model_selection
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
import pandas as pd
import numpy as np


dataset_iris = pd.read_table('iris.data', sep=',', index_col=None)
print("Dataset Iris")
dataset_iris

Dataset Iris


sepal length in cm  sepal width in cm  petal length in cm  \
0                   5.1                3.5                 1.4   
1                   4.9                3.0                 1.4   
2                   4.7                3.2                 1.3   
3                   4.6                3.1                 1.5   
4                   5.0                3.6                 1.4   
..                  ...                ...                 ...   
145                 6.7                3.0                 5.2   
146                 6.3                2.5                 5.0   
147                 6.5                3.0                 5.2   
148                 6.2                3.4                 5.4   
149                 5.9                3.0                 5.1   

     petal width in cm  class  
0                  0.2      1  
1                  0.2      1  
2                  0.2      1  
3                  0.2      1  
4                  0.2      1  
..                 ...    ...  
145                2.3      3  
146                1.9      3  
147                2.0      3  
148                2.3      3  
149                1.8      3  

[150 rows x 5 columns]

In [3]:
dataset_iris.columns

Index(['sepal length in cm', 'sepal width in cm', 'petal length in cm',
       'petal width in cm', 'class'],
      dtype='object')

In [4]:
dataset_iris['sepal length in cm'] = dataset_iris['sepal length in cm'].astype(float)
dataset_iris['sepal width in cm'] = dataset_iris['sepal width in cm'].astype(float)
dataset_iris['petal length in cm'] = dataset_iris['petal length in cm'].astype(float)
dataset_iris['petal width in cm'] = dataset_iris['petal width in cm'].astype(float)
dataset_iris

sepal length in cm  sepal width in cm  petal length in cm  \
0                   5.1                3.5                 1.4   
1                   4.9                3.0                 1.4   
2                   4.7                3.2                 1.3   
3                   4.6                3.1                 1.5   
4                   5.0                3.6                 1.4   
..                  ...                ...                 ...   
145                 6.7                3.0                 5.2   
146                 6.3                2.5                 5.0   
147                 6.5                3.0                 5.2   
148                 6.2                3.4                 5.4   
149                 5.9                3.0                 5.1   

     petal width in cm  class  
0                  0.2      1  
1                  0.2      1  
2                  0.2      1  
3                  0.2      1  
4                  0.2      1  
..                 ...    ...  
145                2.3      3  
146                1.9      3  
147                2.0      3  
148                2.3      3  
149                1.8      3  

[150 rows x 5 columns]

In [5]:
iris_normalised = dataset_iris.values.copy()
normalizador =  StandardScaler()


transfusion_normalised = normalizador.fit_transform(dataset_iris)
dataset_iris['sepal length in cm'] = iris_normalised[:,0]
dataset_iris['sepal width in cm'] = iris_normalised[:,1]
dataset_iris['petal length in cm'] = iris_normalised[:,2]
dataset_iris['petal width in cm'] = iris_normalised[:,3]

print("Dataset Transfusion Normalized")
dataset_iris

Dataset Transfusion Normalized


sepal length in cm  sepal width in cm  petal length in cm  \
0                   5.1                3.5                 1.4   
1                   4.9                3.0                 1.4   
2                   4.7                3.2                 1.3   
3                   4.6                3.1                 1.5   
4                   5.0                3.6                 1.4   
..                  ...                ...                 ...   
145                 6.7                3.0                 5.2   
146                 6.3                2.5                 5.0   
147                 6.5                3.0                 5.2   
148                 6.2                3.4                 5.4   
149                 5.9                3.0                 5.1   

     petal width in cm  class  
0                  0.2      1  
1                  0.2      1  
2                  0.2      1  
3                  0.2      1  
4                  0.2      1  
..                 ...    ...  
145                2.3      3  
146                1.9      3  
147                2.0      3  
148                2.3      3  
149                1.8      3  

[150 rows x 5 columns]

In [6]:
iris_values = dataset_iris.iloc[:,0:4].values
print("Iris features")
print(iris_values)

Iris features
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5

In [7]:
iris_classes = dataset_iris.iloc[:,4].values
print("Iris classes")
print(iris_classes)
print("\nIris classes shape")
print(iris_classes.shape)

Iris classes
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3]

Iris classes shape
(150,)


In [50]:
kf = model_selection.StratifiedKFold(n_splits = 5)
arvore_decisao = tree.DecisionTreeClassifier(criterion='entropy', splitter='best', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, random_state=None, max_leaf_nodes=None, min_impurity_decrease=0.0, min_impurity_split=None, class_weight=None, presort='deprecated', ccp_alpha=0.0)
vizinhos_proximos = KNeighborsClassifier(n_neighbors=3, weights = 'distance')
naive_bayes_gaussian = GaussianNB()
regressao_logistica = LogisticRegression(penalty='l2', dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='saga', max_iter=100, multi_class='auto', verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)
rede_neural = MLPClassifier(hidden_layer_sizes=(5,), activation="logistic", max_iter= 300, alpha=0.001, solver="sgd", tol=1e-4, verbose=True, learning_rate_init=.01)

In [51]:
predicted_classes = dict()
predicted_classes['arvore_decisao'] = np.zeros(iris_classes.shape)
predicted_classes['vizinhos_proximos'] = np.zeros(iris_classes.shape)
predicted_classes['naive_bayes_gaussian'] = np.zeros(iris_classes.shape)
predicted_classes['regressao_logistica'] = np.zeros(iris_classes.shape)
predicted_classes['rede_neural'] = np.zeros(iris_classes.shape)

In [52]:
for train, test in kf.split(iris_values, iris_classes):
    data_train, target_train = iris_values[train], iris_classes[train]
    data_test, target_test = iris_values[test], iris_classes[test]

    arvore_decisao = arvore_decisao.fit(data_train, target_train)
    arvore_decisao_predicted = arvore_decisao.predict(data_test)
    predicted_classes['arvore_decisao'][test] = arvore_decisao_predicted

    vizinhos_proximos = vizinhos_proximos.fit(data_train, target_train)
    vizinhos_proximos_predicted = vizinhos_proximos.predict(data_test)
    predicted_classes['vizinhos_proximos'][test] = vizinhos_proximos_predicted

    naive_bayes_gaussian = naive_bayes_gaussian.fit(data_train, target_train)
    naive_bayes_gaussian_predicted = naive_bayes_gaussian.predict(data_test)
    predicted_classes['naive_bayes_gaussian'][test] = naive_bayes_gaussian_predicted

    regressao_logistica = regressao_logistica.fit(data_train, target_train)
    regressao_logistica_predicted = regressao_logistica.predict(data_test)
    predicted_classes['regressao_logistica'][test] = regressao_logistica_predicted

    rede_neural = rede_neural.fit(data_train, target_train)
    rede_neural_predicted = rede_neural.predict(data_test)
    predicted_classes['rede_neural'][test] = rede_neural_predicted

/home/anapedroso/Documentos/IA-desempenho-algoritmos-classificacao/env/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/anapedroso/Documentos/IA-desempenho-algoritmos-classificacao/env/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/anapedroso/Documentos/IA-desempenho-algoritmos-classificacao/env/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/home/anapedroso/Documentos/IA-desempenho-algoritmos-classificacao/env/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWa

Iteration 1, loss = 1.21048432
Iteration 2, loss = 1.20742487
Iteration 3, loss = 1.20317958
Iteration 4, loss = 1.19798413
Iteration 5, loss = 1.19206839
Iteration 6, loss = 1.18565018
Iteration 7, loss = 1.17893064
Iteration 8, loss = 1.17209097
Iteration 9, loss = 1.16529023
Iteration 10, loss = 1.15866423
Iteration 11, loss = 1.15232513
Iteration 12, loss = 1.14636179
Iteration 13, loss = 1.14084063
Iteration 14, loss = 1.13580696
Iteration 15, loss = 1.13128671
Iteration 16, loss = 1.12728835
Iteration 17, loss = 1.12380511
Iteration 18, loss = 1.12081730
Iteration 19, loss = 1.11829472
Iteration 20, loss = 1.11619908
Iteration 21, loss = 1.11448636
Iteration 22, loss = 1.11310907
Iteration 23, loss = 1.11201832
Iteration 24, loss = 1.11116567
Iteration 25, loss = 1.11050466
Iteration 26, loss = 1.10999217
Iteration 27, loss = 1.10958928
Iteration 28, loss = 1.10926199
Iteration 29, loss = 1.10898153
Iteration 30, loss = 1.10872446
Iteration 31, loss = 1.10847253
Iteration 32, los

In [53]:
for classificador in predicted_classes.keys():
    print("================================================================================================")
    print("Resultados do classificador %s\n%s\n"
          %(classificador, metrics.classification_report(iris_classes, predicted_classes[classificador])))
    print("Matriz de confusão: \n%s\n\n\n" % metrics.confusion_matrix(iris_classes, predicted_classes[classificador]))




Resultados do classificador arvore_decisao
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        50
           2       0.94      0.94      0.94        50
           3       0.94      0.94      0.94        50

    accuracy                           0.96       150
   macro avg       0.96      0.96      0.96       150
weighted avg       0.96      0.96      0.96       150


Matriz de confusão: 
[[50  0  0]
 [ 0 47  3]
 [ 0  3 47]]



Resultados do classificador vizinhos_proximos
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        50
           2       0.96      0.94      0.95        50
           3       0.94      0.96      0.95        50

    accuracy                           0.97       150
   macro avg       0.97      0.97      0.97       150
weighted avg       0.97      0.97      0.97       150


Matriz de confusão: 
[[50  0  0]
 [ 0 47  3]
 [ 0  2 48]]



Resultados do classificad