In [9]:
from sklearn import tree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn import model_selection
from sklearn.preprocessing import StandardScaler
from sklearn import datasets
from sklearn import metrics
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np


dataset_transfusion = pd.read_table('/home/anapedroso/Documentos/IA-desempenho-algoritmos-classificacao/datasets/transfusion.data', sep=',')
print("Dataset Transfusion")
dataset_transfusion

Dataset Transfusion


Recency (months)  Frequency (times)  Monetary (c.c. blood)  \
0                   2                 50                  12500   
1                   0                 13                   3250   
2                   1                 16                   4000   
3                   2                 20                   5000   
4                   1                 24                   6000   
..                ...                ...                    ...   
743                23                  2                    500   
744                21                  2                    500   
745                23                  3                    750   
746                39                  1                    250   
747                72                  1                    250   

     Time (months)  whether he/she donated blood in March 2007  
0               98                                           1  
1               28                                           1  
2               35                                           1  
3               45                                           1  
4               77                                           0  
..             ...                                         ...  
743             38                                           0  
744             52                                           0  
745             62                                           0  
746             39                                           0  
747             72                                           0  

[748 rows x 5 columns]

In [10]:
transfusion_normalised = dataset_transfusion.values.copy()
normalizador =  StandardScaler()

transfusion_normalised = normalizador.fit_transform(dataset_transfusion)
dataset_transfusion['Recency (months)'] = transfusion_normalised[:,0]
dataset_transfusion['Frequency (times)'] = transfusion_normalised[:,1]
dataset_transfusion['Monetary (c.c. blood)'] = transfusion_normalised[:,2]
dataset_transfusion['Time (months)'] = transfusion_normalised[:,3]

print("Dataset Transfusion Normalized")
dataset_transfusion

Dataset Transfusion Normalized


Recency (months)  Frequency (times)  Monetary (c.c. blood)  \
0           -0.927899           7.623346               7.623346   
1           -1.175118           1.282738               1.282738   
2           -1.051508           1.796842               1.796842   
3           -0.927899           2.482313               2.482313   
4           -1.051508           3.167784               3.167784   
..                ...                ...                    ...   
743          1.667904          -0.602307              -0.602307   
744          1.420685          -0.602307              -0.602307   
745          1.667904          -0.430940              -0.430940   
746          3.645659          -0.773675              -0.773675   
747          7.724778          -0.773675              -0.773675   

     Time (months)  whether he/she donated blood in March 2007  
0         2.615633                                           1  
1        -0.257881                                           1  
2         0.029471                                           1  
3         0.439973                                           1  
4         1.753579                                           0  
..             ...                                         ...  
743       0.152621                                           0  
744       0.727324                                           0  
745       1.137826                                           0  
746       0.193671                                           0  
747       1.548328                                           0  

[748 rows x 5 columns]

In [3]:
transfusion_values = dataset_transfusion.iloc[:,0:4].values
print("Transfusion features")
print(transfusion_values)

Transfusion features
[[-0.92789873  7.62334626  7.62334626  2.61563344]
 [-1.17511806  1.28273826  1.28273826 -0.2578809 ]
 [-1.0515084   1.79684161  1.79684161  0.02947053]
 ...
 [ 1.66790417 -0.43093957 -0.43093957  1.13782607]
 [ 3.64565877 -0.77367514 -0.77367514  0.19367135]
 [ 7.72477762 -0.77367514 -0.77367514  1.54832812]]


In [4]:
transfusion_classes = dataset_transfusion.iloc[:,4].values
print("Transfusion classes")
print(transfusion_classes)
print("Transfusion classes shape")
print(transfusion_classes.shape)

Transfusion classes
[1 1 1 1 0 0 1 0 1 1 0 0 1 0 1 1 1 1 1 1 1 0 1 1 0 0 0 1 1 0 0 1 1 1 0 1 1
 1 1 1 1 0 1 0 1 1 0 0 0 0 0 1 0 0 1 1 1 1 0 0 0 1 0 1 1 0 1 0 0 0 0 0 1 0
 1 1 1 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 1
 0 0 1 0 0 1 0 0 1 1 1 1 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0
 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1
 1 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0
 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 1
 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1
 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 

In [5]:
kf = model_selection.StratifiedKFold(n_splits = 5)
arvore_decisao = tree.DecisionTreeClassifier(criterion='entropy', splitter='best', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, random_state=None, max_leaf_nodes=None, min_impurity_decrease=0.0, min_impurity_split=None, class_weight=None, presort='deprecated', ccp_alpha=0.0)
vizinhos_proximos = KNeighborsClassifier(n_neighbors=3, weights = 'distance')
naive_bayes_gaussian = GaussianNB()
regressao_logistica = LogisticRegression(penalty='l2', dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='saga', max_iter=100, multi_class='auto', verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)
rede_neural = MLPClassifier(hidden_layer_sizes=(5,), activation="logistic", max_iter= 300, alpha=0.001, solver="sgd", tol=1e-4, verbose=True, learning_rate_init=.01)

In [6]:
predicted_classes = dict()
predicted_classes['arvore_decisao'] = np.zeros(transfusion_classes.shape)
predicted_classes['vizinhos_proximos'] = np.zeros(transfusion_classes.shape)
predicted_classes['naive_bayes_gaussian'] = np.zeros(transfusion_classes.shape)
predicted_classes['regressao_logistica'] = np.zeros(transfusion_classes.shape)
predicted_classes['rede_neural'] = np.zeros(transfusion_classes.shape)

In [7]:
for train, test in kf.split(transfusion_values, transfusion_classes):
    data_train, target_train = transfusion_values[train], transfusion_classes[train]
    data_test, target_test = transfusion_values[test], transfusion_classes[test]

    arvore_decisao = arvore_decisao.fit(data_train, target_train)
    arvore_decisao_predicted = arvore_decisao.predict(data_test)
    predicted_classes['arvore_decisao'][test] = arvore_decisao_predicted

    vizinhos_proximos = vizinhos_proximos.fit(data_train, target_train)
    vizinhos_proximos_predicted = vizinhos_proximos.predict(data_test)
    predicted_classes['vizinhos_proximos'][test] = vizinhos_proximos_predicted

    naive_bayes_gaussian = naive_bayes_gaussian.fit(data_train, target_train)
    naive_bayes_gaussian_predicted = naive_bayes_gaussian.predict(data_test)
    predicted_classes['naive_bayes_gaussian'][test] = naive_bayes_gaussian_predicted

    regressao_logistica = regressao_logistica.fit(data_train, target_train)
    regressao_logistica_predicted = regressao_logistica.predict(data_test)
    predicted_classes['regressao_logistica'][test] = regressao_logistica_predicted

    rede_neural = rede_neural.fit(data_train, target_train)
    rede_neural_predicted = rede_neural.predict(data_test)
    predicted_classes['rede_neural'][test] = rede_neural_predicted

Iteration 1, loss = 1.11494724
Iteration 2, loss = 1.05182682
Iteration 3, loss = 0.96505088
Iteration 4, loss = 0.87233082
Iteration 5, loss = 0.78541509
Iteration 6, loss = 0.71449737
Iteration 7, loss = 0.65689075
Iteration 8, loss = 0.61587165
Iteration 9, loss = 0.58907013
Iteration 10, loss = 0.57107551
Iteration 11, loss = 0.55929043
Iteration 12, loss = 0.55252568
Iteration 13, loss = 0.54851275
Iteration 14, loss = 0.54614897
Iteration 15, loss = 0.54500526
Iteration 16, loss = 0.54451002
Iteration 17, loss = 0.54418833
Iteration 18, loss = 0.54411706
Iteration 19, loss = 0.54398938
Iteration 20, loss = 0.54382429
Iteration 21, loss = 0.54368665
Iteration 22, loss = 0.54351037
Iteration 23, loss = 0.54324712
Iteration 24, loss = 0.54297412
Iteration 25, loss = 0.54273251
Iteration 26, loss = 0.54245930
Iteration 27, loss = 0.54217570
Iteration 28, loss = 0.54194407
Iteration 29, loss = 0.54170121
Iteration 30, loss = 0.54139048
Iteration 31, loss = 0.54110481
Iteration 32, los

Iteration 267, loss = 0.45476066
Iteration 268, loss = 0.45462744
Iteration 269, loss = 0.45450331
Iteration 270, loss = 0.45440492
Iteration 271, loss = 0.45428424
Iteration 272, loss = 0.45416522
Iteration 273, loss = 0.45408934
Iteration 274, loss = 0.45397796
Iteration 275, loss = 0.45387168
Iteration 276, loss = 0.45375868
Iteration 277, loss = 0.45364397
Iteration 278, loss = 0.45361535
Iteration 279, loss = 0.45347975
Iteration 280, loss = 0.45341127
Iteration 281, loss = 0.45326696
Iteration 282, loss = 0.45319700
Iteration 283, loss = 0.45309696
Iteration 284, loss = 0.45302160
Iteration 285, loss = 0.45291924
Iteration 286, loss = 0.45284476
Iteration 287, loss = 0.45274869
Iteration 288, loss = 0.45267120
Iteration 289, loss = 0.45260135
Iteration 290, loss = 0.45250857
Iteration 291, loss = 0.45246714
Iteration 292, loss = 0.45236306
Iteration 293, loss = 0.45232728
Iteration 294, loss = 0.45229833
Iteration 295, loss = 0.45213171
Iteration 296, loss = 0.45208381
Iteration 

/home/anapedroso/Documentos/IA-desempenho-algoritmos-classificacao/env/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


Iteration 61, loss = 0.52325948
Iteration 62, loss = 0.52293021
Iteration 63, loss = 0.52262399
Iteration 64, loss = 0.52234948
Iteration 65, loss = 0.52205274
Iteration 66, loss = 0.52172223
Iteration 67, loss = 0.52141646
Iteration 68, loss = 0.52109529
Iteration 69, loss = 0.52081921
Iteration 70, loss = 0.52048607
Iteration 71, loss = 0.52016440
Iteration 72, loss = 0.51989542
Iteration 73, loss = 0.51957454
Iteration 74, loss = 0.51926827
Iteration 75, loss = 0.51897874
Iteration 76, loss = 0.51866452
Iteration 77, loss = 0.51836607
Iteration 78, loss = 0.51805396
Iteration 79, loss = 0.51781989
Iteration 80, loss = 0.51748424
Iteration 81, loss = 0.51717321
Iteration 82, loss = 0.51686193
Iteration 83, loss = 0.51656603
Iteration 84, loss = 0.51628458
Iteration 85, loss = 0.51595385
Iteration 86, loss = 0.51565793
Iteration 87, loss = 0.51538681
Iteration 88, loss = 0.51509225
Iteration 89, loss = 0.51480697
Iteration 90, loss = 0.51449185
Iteration 91, loss = 0.51420176
Iteratio

Iteration 65, loss = 0.53981310
Iteration 66, loss = 0.53956935
Iteration 67, loss = 0.53935543
Iteration 68, loss = 0.53908445
Iteration 69, loss = 0.53883930
Iteration 70, loss = 0.53860338
Iteration 71, loss = 0.53833889
Iteration 72, loss = 0.53809931
Iteration 73, loss = 0.53784563
Iteration 74, loss = 0.53757129
Iteration 75, loss = 0.53732618
Iteration 76, loss = 0.53704310
Iteration 77, loss = 0.53677223
Iteration 78, loss = 0.53651642
Iteration 79, loss = 0.53625914
Iteration 80, loss = 0.53597888
Iteration 81, loss = 0.53569719
Iteration 82, loss = 0.53541507
Iteration 83, loss = 0.53515044
Iteration 84, loss = 0.53485565
Iteration 85, loss = 0.53456828
Iteration 86, loss = 0.53429831
Iteration 87, loss = 0.53401147
Iteration 88, loss = 0.53370353
Iteration 89, loss = 0.53343348
Iteration 90, loss = 0.53315952
Iteration 91, loss = 0.53285240
Iteration 92, loss = 0.53255219
Iteration 93, loss = 0.53229232
Iteration 94, loss = 0.53195800
Iteration 95, loss = 0.53163326
Iteratio

Iteration 16, loss = 0.55614870
Iteration 17, loss = 0.55547196
Iteration 18, loss = 0.55475951
Iteration 19, loss = 0.55423815
Iteration 20, loss = 0.55388458
Iteration 21, loss = 0.55340248
Iteration 22, loss = 0.55296294
Iteration 23, loss = 0.55264189
Iteration 24, loss = 0.55222565
Iteration 25, loss = 0.55182338
Iteration 26, loss = 0.55141391
Iteration 27, loss = 0.55103108
Iteration 28, loss = 0.55062961
Iteration 29, loss = 0.55023810
Iteration 30, loss = 0.54996087
Iteration 31, loss = 0.54948581
Iteration 32, loss = 0.54913074
Iteration 33, loss = 0.54879439
Iteration 34, loss = 0.54837526
Iteration 35, loss = 0.54801946
Iteration 36, loss = 0.54763116
Iteration 37, loss = 0.54725383
Iteration 38, loss = 0.54690364
Iteration 39, loss = 0.54661729


/home/anapedroso/Documentos/IA-desempenho-algoritmos-classificacao/env/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


Iteration 40, loss = 0.54617954
Iteration 41, loss = 0.54586006
Iteration 42, loss = 0.54551498
Iteration 43, loss = 0.54513368
Iteration 44, loss = 0.54479882
Iteration 45, loss = 0.54444856
Iteration 46, loss = 0.54410913
Iteration 47, loss = 0.54376398
Iteration 48, loss = 0.54343851
Iteration 49, loss = 0.54307936
Iteration 50, loss = 0.54276614
Iteration 51, loss = 0.54241684
Iteration 52, loss = 0.54212385
Iteration 53, loss = 0.54173158
Iteration 54, loss = 0.54138617
Iteration 55, loss = 0.54111220
Iteration 56, loss = 0.54073377
Iteration 57, loss = 0.54041836
Iteration 58, loss = 0.54008281
Iteration 59, loss = 0.53973681
Iteration 60, loss = 0.53940652
Iteration 61, loss = 0.53907502
Iteration 62, loss = 0.53876033
Iteration 63, loss = 0.53841614
Iteration 64, loss = 0.53812168
Iteration 65, loss = 0.53775212
Iteration 66, loss = 0.53744226
Iteration 67, loss = 0.53710552
Iteration 68, loss = 0.53678934
Iteration 69, loss = 0.53644063
Iteration 70, loss = 0.53615073
Iteratio

Iteration 293, loss = 0.47137560
Iteration 294, loss = 0.47123504
Iteration 295, loss = 0.47114661
Iteration 296, loss = 0.47096658
Iteration 297, loss = 0.47084297
Iteration 298, loss = 0.47070071
Iteration 299, loss = 0.47058452
Iteration 300, loss = 0.47044403
Iteration 1, loss = 0.57739016
Iteration 2, loss = 0.57510700
Iteration 3, loss = 0.57234506
Iteration 4, loss = 0.56834672
Iteration 5, loss = 0.56473487
Iteration 6, loss = 0.56176123
Iteration 7, loss = 0.55919630
Iteration 8, loss = 0.55669887
Iteration 9, loss = 0.55504546
Iteration 10, loss = 0.55333525
Iteration 11, loss = 0.55213025
Iteration 12, loss = 0.55117760
Iteration 13, loss = 0.55032460
Iteration 14, loss = 0.54972865
Iteration 15, loss = 0.54915420
Iteration 16, loss = 0.54875731
Iteration 17, loss = 0.54837447
Iteration 18, loss = 0.54792934
Iteration 19, loss = 0.54777841
Iteration 20, loss = 0.54728878
Iteration 21, loss = 0.54693015
Iteration 22, loss = 0.54659503
Iteration 23, loss = 0.54629755
Iteration

/home/anapedroso/Documentos/IA-desempenho-algoritmos-classificacao/env/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


Iteration 111, loss = 0.51866721
Iteration 112, loss = 0.51835905
Iteration 113, loss = 0.51806508
Iteration 114, loss = 0.51777753
Iteration 115, loss = 0.51752936
Iteration 116, loss = 0.51717890
Iteration 117, loss = 0.51686522
Iteration 118, loss = 0.51659535
Iteration 119, loss = 0.51630080
Iteration 120, loss = 0.51601365
Iteration 121, loss = 0.51572758
Iteration 122, loss = 0.51544482
Iteration 123, loss = 0.51514525
Iteration 124, loss = 0.51486924
Iteration 125, loss = 0.51456661
Iteration 126, loss = 0.51431658
Iteration 127, loss = 0.51402743
Iteration 128, loss = 0.51372957
Iteration 129, loss = 0.51345692
Iteration 130, loss = 0.51319312
Iteration 131, loss = 0.51292731
Iteration 132, loss = 0.51263107
Iteration 133, loss = 0.51235346
Iteration 134, loss = 0.51211505
Iteration 135, loss = 0.51181481
Iteration 136, loss = 0.51155181
Iteration 137, loss = 0.51127864
Iteration 138, loss = 0.51105711
Iteration 139, loss = 0.51077093
Iteration 140, loss = 0.51055062
Iteration 

In [8]:
for classificador in predicted_classes.keys():
    print("================================================================================================")
    print("Resultados do classificador %s\n%s\n"
          %(classificador, metrics.classification_report(transfusion_classes, predicted_classes[classificador])))
    print("Matriz de confusão: \n%s\n\n\n" % metrics.confusion_matrix(transfusion_classes, predicted_classes[classificador]))

Resultados do classificador arvore_decisao
              precision    recall  f1-score   support

           0       0.77      0.75      0.76       570
           1       0.26      0.29      0.27       178

    accuracy                           0.64       748
   macro avg       0.52      0.52      0.52       748
weighted avg       0.65      0.64      0.64       748


Matriz de confusão: 
[[426 144]
 [127  51]]



Resultados do classificador vizinhos_proximos
              precision    recall  f1-score   support

           0       0.76      0.72      0.74       570
           1       0.24      0.29      0.26       178

    accuracy                           0.62       748
   macro avg       0.50      0.50      0.50       748
weighted avg       0.64      0.62      0.63       748


Matriz de confusão: 
[[411 159]
 [127  51]]



Resultados do classificador naive_bayes_gaussian
              precision    recall  f1-score   support

           0       0.79      0.92      0.85       570
   